### PR TITLE
Flush witness data when consistent (part 2)

### LINKED ISSUE #4680: New instance of assertion `(nd->witnessHeight == -1) || (nd->witnessHeight == indexHeight - 1)' failed
From https://github.com/zcash/zcash/issues/4301#issuecomment-670701619 :

> I just got this again on master, commit [205c7b5](https://github.com/zcash/zcash/commit/205c7b5844856ecf2ac52f8605b10f855c863a1a) :
> 
> ```
> Thank you for running a testnet zcashd v3.1.0 node!
> You're helping to strengthen the network and contributing to a social good :)
> 
> In order to ensure you are adequately protecting your privacy when using Zcash,
> please see <https://z.cash/support/security/>.
> 
>      Downloading blocks | 1019322 (1019626 headers) / ~1031720 (98%)
>                         | [                                                  ]
>            Next upgrade | Canopy at block height 1028500, in around 7 days
>             Connections | 5
>   Network solution rate | 12.000 Sol/s
> 
> Mining is paused while downloading blocks.
> 
> Since starting this node 2 minutes, 22 seconds ago:
> - You have validated 120 transactions!
> - You have completed 0 Equihash solver runs.
> 
> [Press Ctrl+C to exit] [Set 'showmetrics=0' to hide]
> zcashd: wallet/wallet.cpp:1094: void CopyPreviousWitnesses(NoteDataMap&, int, int64_t) [with NoteDataMap = std::map<SaplingOutPoint, SaplingNoteData>; int64_t = long int]: Assertion `(nd->witnessHeight == -1) || (nd->witnessHeight == indexHeight - 1)' failed.
> Aborted
> ```
> 
> This is not the result of bad chainstate from a build before #4573, because the same code was syncing fine just before this. (I had Ctrl-C'd, edited zcash.conf to enable mining, and then restarted.)
> 
> I have the datadir if anyone wants to investigate (ask me for the download link).

### PR DESCRIPTION
**Pull request by LarryRuane**
Closes #4680. After CWallet::ChainTipAdded() updates the witness data, it may flush it to disk (SetBestChain()); make sure the locator part is consistent with the witnesses (height).

### CODE REVIEW

File: src/init.cpp [hunk 1]
```diff
@@ -223,9 +223,6 @@ void Shutdown()
         if (pcoinsTip != NULL) {
             FlushStateToDisk();
         }
-        // Flush the wallet witness cache to disk (no longer done by FlushStateToDisk())
-        GetMainSignals().SetBestChain(chainActive.GetLocator());
```
Comment (LarryRuane) [inline src/init.cpp:227]: Unfortunately, it's not safe to flush the witness data on clean shutdown; removing this restores the code to what it was for years until the recent PR #4627. The effect of removing this is that the last 10 minutes of blocks need to be rescanned even after a clean shutdown. This takes only a few seconds.

The reason this isn't safe is that there is no guarantee that the locator used here (part of the flush data), which is based on the latest block, is consistent with the witness data. The heights of the witness data and the locator must be the same. The fix this PR makes to wallet thread (`ChainTipAdded()`) now guarantees that, and that's really the only place it can be guaranteed.

File: src/main.h [hunk 2]
```diff
@@ -100,6 +100,8 @@ static const unsigned int BLOCK_DOWNLOAD_WINDOW = 1024;
 static const unsigned int DATABASE_WRITE_INTERVAL = 60 * 60;
 /** Time to wait (in seconds) between flushing chainstate to disk. */
 static const unsigned int DATABASE_FLUSH_INTERVAL = 24 * 60 * 60;
+/** Time to wait (in seconds) between writing wallet witness data to disk. */
+static const unsigned int WITNESS_WRITE_INTERVAL = 10 * 60;
```
Comment (LarryRuane) [inline src/main.h:104]: It's okay to flush witness data more often than once per hour, and the `DATABASE_WRITE_INTERVAL` should really have multiple meanings, so give the witness flush its own constant (10 minutes).

File: src/wallet/wallet.cpp [hunk 3]
```diff
@@ -595,10 +595,16 @@ void CWallet::ChainTipAdded(const CBlockIndex *pindex,
         // Don't flush during startup.
         nLastSetChain = nNow;
     }
-    if (nLastSetChain + (int64_t)DATABASE_WRITE_INTERVAL * 1000000 < nNow) {
+    if (nLastSetChain + (int64_t)WITNESS_WRITE_INTERVAL * 1000000 < nNow) {
```
Comment (LarryRuane) [inline src/wallet/wallet.cpp:598]: 10 minutes instead of 60 minutes.

File: src/wallet/wallet.cpp [hunk 4]
```diff
@@ -595,10 +595,16 @@ void CWallet::ChainTipAdded(const CBlockIndex *pindex,
...
-        LOCK(cs_main);
-        SetBestChain(chainActive.GetLocator());
+        CBlockLocator loc;
+        {
+            // The locator must be derived from the pindex used to increment
+            // the witnesses above; pindex can be behind chainActive.Tip().
+            LOCK(cs_main);
+            loc = chainActive.GetLocator(pindex);
+        }
+        SetBestChain(loc);
```
Comment (LarryRuane) [inline src/wallet/wallet.cpp:607]: The `cs_main` lock shouldn't be held during `SetBestChain()` because it synchronously writes to disk.

**Comment by LarryRuane** [comment]
The latest [commit](https://github.com/zcash/zcash/pull/4690/commits/5b0affa13a8e8b052908204bd190324e963d147f) is optional, please share you opinion on whether to include it. It restores flushing the witnesses (call `SetBestChain()`) on clean shutdown, which just seems like the right thing to do (but isn't actually required). The way this is made safe is to have `SetBestChain()` actually compare the witness heights and the locator height, and if they differ, do nothing. (Again, not writing the witnesses is always okay, it just means more blocks get rescanned on the next restart.)

The obvious downside is more code, but this makes `SetBestChain()` more robust, because it doesn't need to trust the callers to provide a locator that matches the witnesses.

The extra code in `SetBestChainINTERNAL()` shouldn't be a performance concern, because it isn't called more often than once every 10 minutes.

File: src/main.h (hunk 2 above)
Comment (daira) [reply src/main.h:104]: Is it necessary to write the witness data and the chain index data at separate intervals, though?

The performance argument for batched database writes is just that there's an overhead to doing any write at all. If we're doing a write, then we might as well flush the block index state as well.

(This argument doesn't apply to DATABASE_FLUSH_INTERVAL because there's currently a conflation between flushing that state to disk vs the cache discard policy. I'll explain this better in #4701.)

**Comment by nuttycom** [comment]
Would it make sense to submit a PR with just this set of changes, and then an additional PR which adds on the changes removed in the last commit on this branch? The order seems upside down to me.

**Comment by daira** [comment]
On further consideration, please just squash the last two commits of this PR, so that the signals are never removed.

**Comment by LarryRuane** [comment]
Force-pushed squash down to one commit. It's not safe to flush the witness data on clean shutdown (so that's been removed), and it _is_ safe to _not_ flush the witness data on clean shutdown (that's how this code worked for years until the recent #4627). The wallet thread flushes the witness data safely sometimes after incrementing the witnesses for a new block, but the latest commit adds a counter in addition to a time interval. In this way, after a certain number of witness updates (in memory), witness data will flush to disk. Without this counter, if we're reindexing or doing IBD with a nonempty wallet, or just syncing with the network after being away for a long time, and blocks are being added quickly, then a lot of work will be lost if the client restarts (many blocks would have to be rescanned because the witness data hasn't been written recently).

I have no more changes planned for this PR; it's ready for review.
@zkbot try

**Review by therealyingtong — APPROVED** [review]
utACK (with @nuttycom and @str4d )

File: src/main.h (hunk 2 above)
Comment (LarryRuane) [reply src/main.h:104]: The wallet database and the index database are independent, so I don't see the advantage of flushing both at the same time.

**Review by str4d — APPROVED** [review]

**Comment by str4d** [comment]
@zkbot r+
