### PR TITLE
#4624 improve IBD sync by eliminating getheaders requests

### LINKED ISSUE #4624: The download traffic is several times larger than the downloaded data
Hello
I ran the program for a new sync and watched the network traffic
For example: File blk00000.dat about 130 MB but was downloaded about 750MB.
Files blk00000.dat and blk00001.dat about 260MB but was downloaded about 1.5GB.
For 40 .dat files (5GB), about 30GB was downloaded.
I think it's wrong. I don’t want download 200GB instead 30GB blockchain.

Zcash Daemon version v3.0.0-e3aae37
Windows 10 x64 and also tried on Windows 7 x64
was set  ibdskiptxverification=1
8 peers were connected
There are no errors in debug.log. Only sometimes:
ERROR: ContextualCheckTransaction(): overwinter is not active yet
ERROR: AcceptToMemoryPool: ContextualCheckTransaction failed

### PR DESCRIPTION
**Pull request by LarryRuane**
Closes #4624. Don't issue redundant `getheaders` P2P requests.

It's not certain that this is a safe change or the best way to solve the problem, but it does dramatically decrease IBD time and network (read) usage. The corresponding upstream code has become quite different, so it's not clear how this problem is solved there. (In my testing, the problem did not occur there; the node seemed to download the minimum amount of data from the network.)

There's no behavior change after IBD completes, so perhaps the only problem with this change (the only way it might be unsafe) is if IBD stalls completely (due to `getheaders` not being sent when necessary). That hasn't happened in my testing so far (I'll continue testing).

### CODE REVIEW

**Comment by bigbrain** [comment]
> There's no behavior change after IBD completes, so perhaps the only problem with this change (the only way it might be unsafe) is if IBD stalls completely (due to `getheaders` not being sent when necessary). That hasn't happened in my testing so far (I'll continue testing).

I think IBD will not be able to stop completely. Because within a few minutes a new block will be generated and `inv` received. `getheaders` will also be sent in response to `inv`. And if the IBD hasn't finished yet, a lot of headers will be received and the sync will continue. But maybe I'm wrong.

File: src/main.cpp [hunk 1]
```diff
@@ -6239,6 +6239,17 @@ bool static ProcessMessage(const CChainParams& chainparams, CNode* pfrom, string
             return true;
         }
 
+        // If we already know the last header in the message, then it contains
```
Comment (nuttycom) [inline src/main.cpp:6242]: This looks okay to me. I think it would be better to move this block of code down below the next block where the chaining of headers is checked, simply because it relies upon the ordering of the headers and its result won't be used until `AcceptBlockHeader` has succeeded anyway. 

Also minor nits on the CLI flag: `-fixibd` is not adequately descriptive, I'd prefer `-no-download-redundant-headers` or something of the sort, and also I'd like to not introduce additional locations where CLI flags are referenced directly because network code shouldn't be directly coupled to CLI arguments; ideally these flags would be passed to this function as an argument. If that's too significant of a change, no big deal.

**Review by nuttycom — COMMENTED** [review]
utACK 46a19e49739c6f6f214c5a303ca14cc516a4f7d1

This looks safe to me. It skips requesting additional headers if the last block is already in `mapBlockIndex`, the behavior can be turned off via a CLI flag, and the order of received headers is validated in the block of code surrounding the new additions. utACK with nonblocking nits, though I would at very least like to see the flag name `-fixibd` changed.

**Review by nuttycom — APPROVED** [review]
Oops, previous utACK comment was intended to be an approval.

**Comment by LarryRuane** [comment]
I set this PR to "draft" because this fix was backed out of Bitcoin Core. But after more investigation, I now think it's safe to merge, see the extensive [comment](https://github.com/zcash/zcash/issues/4624#issuecomment-756498627) I left on the ticket. I'll make those small changes suggested by @nuttycom (thank you for the review!), then remove the "draft" state.

File: src/main.cpp (hunk 1 above)
Comment (LarryRuane) [reply src/main.cpp:6242]: > I think it would be better to move this block of code down below the next block...

[`AcceptBlockHeader()`](https://github.com/zcash/zcash/blob/8c000ae281b5be03dba189ff26c90f95ca8caf05/src/main.cpp#L4321) (called in the block below) (usually) adds the block to the index, so that would break the test we're making here (i.e., `hasNewHeaders` would always be set to false).

> I'd prefer `-no-download-redundant-headers`

I think it's best if we don't start argument names with `-no` because upstream has a [feature](https://github.com/bitcoin/bitcoin/blob/9158d6f34153dc937e109d0e7486e956a26f20aa/src/util/system.cpp#L180) that we haven't pulled in yet that gives a special meaning to such arguments. (It automatically converts `-nofoo=0` to `-foo=1`.)

> I'd like to not introduce additional locations where CLI flags are referenced directly

I think removing the direct access to configuration options could be done in a separate PR so it's done consistently; otherwise, I need to decide how to do it right now. I see there are five existing instances of that in this function (`ProcessMessage()`).

File: src/main.cpp [hunk 2]
```diff
@@ -6259,7 +6273,12 @@ bool static ProcessMessage(const CChainParams& chainparams, CNode* pfrom, string
         if (pindexLast)
             UpdateBlockAvailability(pfrom->GetId(), pindexLast->GetBlockHash());
 
-        if (nCount == MAX_HEADERS_RESULTS && pindexLast) {
+        // Temporary, until we're sure the optimization works
+        if (nCount == MAX_HEADERS_RESULTS && pindexLast && !hasNewHeaders) {
+            LogPrint("net", "NO more getheaders (%d) to send to peer=%d (startheight:%d)\n", pindexLast->nHeight, pfrom->id, pfrom->nStartingHeight);
+        }
```
Comment (LarryRuane) [inline src/main.cpp:6279]: This `if` could be combined with the next one, but this `LogPrint()` probably should be removed once we're sure this works, and it's easier to just remove this `if`.

**Comment by LarryRuane** [comment]
Force-pushed rebase onto latest master. My node is continuing to sync (IBD) and it's looking much better. Since master includes #4944, my node is no longer banning peers, so after 8 hours, it's at 57%. The sum of the `blk.dat` files is about 13GB, compared to the network download at 21.5GB. I think that's pretty normal; it's much better than before by at least an order of magnitude (probably closer to two orders of magnitude). I'll let the sync continue and post here again if anything surprising happens. But I think this PR is okay to merge.

@nuttycom, when you have a chance, please re-ack the latest commit hash if it looks okay.

**Comment by LarryRuane** [comment]
My node just finished syncing. The entire IBD took 12.5 hours. It downloaded 26.3 GB over the network, and created 24 GB of `blknnn.dat` file data (that's very good). I added some debug code to count the total number of headers downloaded, 2087000, versus the number of blocks, 1105000, almost double. With this PR, it's still possible to download headers unnecessarily. But this is far better than before. 

My internet download speed is 103 Mbps. The CPU ran over 100% each time I checked. I recommend we merge this PR after review.

**Review by nuttycom — COMMENTED** [review]
utACK https://github.com/zcash/zcash/commit/addf0b3318cd1da78cd6e1607ad7a61b47b1c6e6

**Review by mdr0id — APPROVED** [review]
testedACK

v4.2.0 indicates issues on the peer receive bytes:
image
Checking the Docker environment is accurate and not causing issues:
image

In roughly an hour the node receives about 20GB over the expected port.

This PR :
image
image

In roughly an hour the node receives about 6GB on the expected port.

Both nodes were ran on a ~80Mbps down internet connection. For completeness, an iteration of `./qa/zcash/performance-measurements.sh time connectblockslow` was ran with a average of `0.1281082 s`. I doubt this test would indicate the findings above, but it is to ensure there is no IBD regression introduced prior to v4.3.0.

**Comment by nuttycom** [comment]
@zkbot r+

**Review by daira — APPROVED** [review]
utACK
