### PR TITLE
Ensure anchor depth is > 0 when selecting an Orchard anchor.

### LINKED ISSUE #5955: Runtime error: TransactionBuilder cannot add Orchard output without Orchard anchor
### Describe the issue
Using z_sendmany in Zcash 5.0.0 on testnet to send t-addr funds to an Orchard address results in "runtime error: TransactionBuilder cannot add Orchard output without Orchard anchor".

#### If so, please list the steps to reproduce below:
1. Restore an old testnet wallet that has t-addr coins. I used `zcash-cli z_importwallet` and all of my coins were coinbase, mined around December 2019.
2. Run `zcash-cli z_getnewaccount` which returns `{"account": 0}`
3. Run `zcash-cli z_getaddressforaccount 0 '["orchard"]'` which returns an orchard address, e.g. `"utest1av6dv..."`
4. Run `zcash-cli z_sendmany "ANY_TADDR" '[{"address": "utest1av6dv...", "amount": AMOUNT}]' 0 0.00001 "AllowRevealedSenders"`. (I seem to be able to reproduce this with any amount up to the everything-but-fee.)
5. Run `zcash-cli z_getoperationresult` to check result of the send. Observe that it contains `"error": {"code": -1, "message": "runtime error: TransactionBuilder cannot add Orchard output without Orchard anchor"}`. The same message also appears in `debug.log`. The message would appear to come from [`src/transaction_builder.cpp`](https://github.com/zcash/zcash/blob/master/src/transaction_builder.cpp#L342).

### Expected behaviour
zcashd wallet should create and broadcast transaction spending t-addr funds into the Orchard address. (Edit: actually, the wallet should have suggested me to use `z_shieldcoinbase`; see the next comment)

### Actual behaviour + errors
I get "runtime error: TransactionBuilder cannot add Orchard output without Orchard anchor" and no transaction gets sent.

### The version of Zcash you were using:
```
$ zcashd --version
Zcash Daemon version v5.0.0
```
I'm using `txindex=1`, `experimentalfeatures=1`, `paymentdisclosure=1`, `insightexplorer=1` but have not tried running without them.

### Machine specs:
A workstation with Intel Xeon CPU and 64 gigabytes of RAM running Ubuntu 20.04 LTS (kernel: 5.4.0-112-generic #126-Ubuntu SMP). I used official APT repo to install Zcash.

### Any extra information that might be useful in the debugging process.
Running `zcashd` with `-debug=1` results in the following log file (slightly cleaned up to improve readability):
```
DEBUG zrpcunsafe: opid-...: z_sendmany initialized (params={"fromaddress":"ANY_TADDR","amounts":[{"address":"utest1av6dv...","amount":1370.00639654}],"minconf":0,"fee":1e-05})
DEBUG zrpcunsafe: opid-...: found unspent transparent UTXO (txid=3ce8602ec2982c65f402d21fd14c9855257309e371528501042dfc7e108488a9, index=0, amount=5.0007, isCoinbase=true)
      (~330 similar lines skipped)
DEBUG zrpcunsafe: opid-...: found unspent transparent UTXO (txid=de77ca1f8e5c8bce9557f576c47378787acfed3627c530f4039d7679ca5393ff, index=0, amount=2.50, isCoinbase=true)
DEBUG zrpcunsafe: opid-...: spending 1370.00640654 to send 1370.00639654 with fee 0.00001
DEBUG zrpc: opid-...: total transparent input: 1370.00640654 (to choose from)
DEBUG zrpcunsafe: opid-...: total shielded input: 0.00 (to choose from)
DEBUG zrpc: opid-...: total transparent output: 0.00
DEBUG zrpcunsafe: opid-...: total shielded Sapling output: 0.00
DEBUG zrpcunsafe: opid-...: total shielded Orchard output: 1370.00639654
DEBUG zrpc: opid-...: fee: 0.00001
 INFO main: opid-...: z_sendmany finished (status=failed, error=runtime error: TransactionBuilder cannot add Orchard output without Orchard anchor)
DEBUG db: Flushing wallet.dat
DEBUG db: Flushed wallet.dat 5ms
```

The node is fully synced: `UpdateTip: new best hash=0057f006a530777f4f6f7f7cfc0fde1f4b3434f63a060655a59d696bc1aa4e57 height=1874209 bits=526400521 log2_work=37.256956 tx=2402661 date=2022-05-12 
22:19:29 progress=1.000000 cache=0.0MiB(23tx)`.

### Do you have a backup of `~/.zcash` directory and/or take a VM snapshot?
Yes. Happy to provide my testnet wallet backup to developers.

### PR DESCRIPTION
**Pull request by nuttycom**
Fixes #5955

### CODE REVIEW

**Review by daira — APPROVED** [review]
utACK

File: src/wallet/rpcwallet.cpp [hunk 1]
```diff
@@ -5522,7 +5527,12 @@ UniValue z_shieldcoinbase(const UniValue& params, bool fHelp)
                 }
             },
             [&](const libzcash::UnifiedAddress& ua) {
-                // OK
+                if (!ua.GetSaplingReceiver().has_value()) {
+                    throw JSONRPCError(
+                            RPC_VERIFY_REJECTED,
+                            "Only Sapling shielding is currently supported by z_shieldcoinbase. "
+                            "Use z_sendmany with a transaction amount that results in no change for Orchard shielding.");
```
Comment (daira) [inline src/wallet/rpcwallet.cpp:5534]: Is there an issue to fix this?

Comment (nuttycom) [reply src/wallet/rpcwallet.cpp:5534]: Yes, https://github.com/zcash/zcash/issues/5511; I'm presently working on it.
