### PR TITLE
Dont log ERROR: spent index not enabled

### LINKED ISSUE #5420: insightexplorer, lightwalletd: excess logging "ERROR main: Unable to get spent index information"
If `zcashd` is configured to be the backend for either an Insight Explorer or a lightwalletd, it can log a message too often. This could fill up the filesystem that `debug.log` resides on. The message -- which does _not_ indicate an actual error condition -- is logged from [`GetSpentIndex()`](https://github.com/zcash/zcash/blob/7aaefab2d7d671951f153e47cdd83ae55d78144f/src/main.cpp#L2040), which is called from [several places](https://github.com/zcash/zcash/search?q=getspentindex). This will happen if the configuration enables either `insightexplorer` or `lightwalletd` (both of which require `experimentalfeatures` to be enabled).

This problem was partially fixed by #4115, but that fixed the problem only when neither `insightexplorer` nor `lightwalletd` are enabled; it still happens if either of them is enabled. 

I was able to reproduce the problem with lightwalletd, by submitting a `GetTransaction` gRPC with a txid argument that corresponds to a transaction that has at least one unspent transparent output.

### PR DESCRIPTION
**Pull request by LarryRuane**
Closes #5420. This PR is an extension of #4114, which fixed this excessive logging
problem for nodes that were not insight explorer or lightwalletd enabled. This PR
extends the fix to nodes that are enabled to support either of those services.

This and related messages can be useful, so they are retained, but are restricted
to only log when `-debug=rpc` logging is enabled.

### CODE REVIEW

**Comment by mdr0id** [comment]
Edited title due to minor issue we have found in other PRs.

File: src/main.cpp [hunk 1]
```diff
@@ -2019,52 +2019,60 @@ bool AcceptToMemoryPool(
...
     std::vector<std::pair<uint256, unsigned int> > &hashes)
 {
-    if (!fTimestampIndex)
-        return error("Timestamp index not enabled");
-
-    if (!pblocktree->ReadTimestampIndex(high, low, fActiveOnly, hashes))
-        return error("Unable to get hashes for timestamps");
-
+    if (!fTimestampIndex) {
+        LogPrint("rpc", "Timestamp index not enabled");
```
Comment (steven-ecc) [inline src/main.cpp:2023]: Should all these `LogPrint`'s use a category of "net"?

Comment (LarryRuane) [reply src/main.cpp:2023]: The `GetSpentIndex()` callers are within the RPC code: https://github.com/zcash/zcash/search?q=GetSpentIndex
and similar for the other 3 `Get*` functions that we're modifying. So, for example, if the `getrawtransaction` RPC doesn't return the "spent" information as expected, and you would like to know why, you can enable the `rpc` logging category, re-run the `getrawtransaction` RPC and look in the log file to see why.

The `net` logging category relates to the P2P network.

Another option I considered would be for these to have their own new category (`insight` perhaps, although that doesn't refer to lightwalletd), but then I thought these message fit pretty naturally in the `rpc` category.

Comment (steven-ecc) [reply src/main.cpp:2023]: The PR description above mentions `-debug=net` which is why I asked.

Comment (LarryRuane) [reply src/main.cpp:2023]: Oh I'm sorry, you're right, fixed!

**Comment by LarryRuane** [comment]
Force-pushed to improve the release notes slightly.

**Review by steven-ecc — APPROVED** [review]
utACK

**Review by nuttycom — APPROVED** [review]
utACK

**Review by nuttycom — APPROVED** [review]
utACK. This just replaces `error` calls with `LogPrint`...`return false`. Looks fine.

**Comment by nuttycom** [comment]
Builds fine locally, we'll see what the re-run does.
