### PR TITLE
Handle errors when getting change addr for account

### LINKED ISSUE #6654: z_sendmany crashes zcashd
On version 5.5.0. Starting with a fresh regtest node.
```bash
zcashd -regtest -printtoconsole -nuparams=5ba81b19:1 -nuparams=76b809bb:1 -nuparams=2bb40e60:1 -nuparams=f5b9230b:1 -nuparams=e9ff75a6:2 -nuparams=c2d6d0b4:3
```
```bash
# coinbase maturity = 100
zcash-cli -regtest generate 110
zcash-cli -regtest z_getnewaccount
zcash-cli -regtest z_getaddressforaccount 0
zcash-cli -regtest z_listunifiedreceivers "unified_addr"
# pick out the transparent address and send to ourselves to de-coinbase utxos.
zcash-cli -regtest sendtoaddress "t_addr" 50
zcash-cli -regtest generate 1
zcash-cli -regtest z_getaddressforaccount 0 '["orchard"]'
zcash-cli -regtest z_sendmany ANY_TADDR '[{"address": "orchard_addr", "amount": 2}]' 1 null AllowRevealedSenders
```
zcashd crashes with
```
zcashd: wallet/wallet_tx_builder.cpp:382: auto WalletTxBuilder::GetChangeAddress(CWallet &, const ZTXOSelector &, const SpendableInputs &, const Payments &, const TransactionStrategy &, bool)::(anonymous class)::operator()(const AccountZTXOPattern &) const: Assertion `addr.has_value()' failed.
Aborted (core dumped)
```

### PR DESCRIPTION
**Pull request by sellout**
This previously hit an assert when we tried to get a change address for the
legacy account without `AllowRevealedRecipient`.

Fixes #6654.

### CODE REVIEW

File: src/wallet/wallet_tx_builder.cpp [hunk 1]
```diff
@@ -376,11 +376,20 @@ WalletTxBuilder::GetChangeAddress(
...
-            return addr.value();
+                    getAllowedChangePools(acct.GetReceiverTypes()))
+                .map_error([](auto err) {
+                    switch (err) {
+                        case AccountChangeAddressFailure::DisjointReceivers:
+                            return AddressResolutionError::CouldNotResolveReceiver;
+                        case AccountChangeAddressFailure::TransparentChangeNotPermitted:
+                            return AddressResolutionError::TransparentChangeNotAllowed;
+                        case AccountChangeAddressFailure::NoSuchAccount:
+                            assert(false);
```
Comment (nuttycom) [inline src/wallet/wallet_tx_builder.cpp:389]: This should probably throw, or at least `assert(err != AccountChangeAddressFailure::NoSuchAccount)`?

**Review by daira — APPROVED** [review]
utACK

File: src/wallet/wallet_tx_builder.cpp (hunk 1 above)
Comment (sellout) [reply src/wallet/wallet_tx_builder.cpp:389]: I’m fine with either. It’s true, I’m not certain that this case is checked in all cases before we get here.

Just an FYI for the future, I have sellout/zcash#4 (that I don’t think should be in the hotfix), which eliminates some of these failures.

**Review by daira — APPROVED** [review]
utACK
