### PR TITLE
Instruct users to run zcash-fetch-params if network params aren't available

### LINKED ISSUE #1786: Add better error reporting when proving and verification keys are not available
For example, when running tests.
```
./qa/pull-tester/rpc-tests.sh
=== Running testscript wallet_protectcoinbase.py ===


************************
EXCEPTION: St13runtime_error       
could not load param file at /home/someuser/.zcash-params/sprout-verifying.key       
Zcash in AppInit()      

zcashd: /home/someuser/zcash/depends/x86_64-unknown-linux-gnu/share/../include/boost/thread/pthread/thread_data.hpp:215: boost::detail::interruption_checker::~interruption_checker(): Assertion `!pthread_mutex_unlock(m)' failed.
```

Whether zcashd or rpc-tests.sh, any component which requires the keys to exist, should return a human friendly error message with instructions to run zcutil/fetch-params.sh.

### PR DESCRIPTION
**Pull request by str4d**
Closes #1786.

### CODE REVIEW

File: src/init.cpp [hunk 1]
```diff
@@ -621,6 +621,17 @@ static void ZC_LoadParams()
...
     boost::filesystem::path vk_path = ZC_GetParamsDir() / "sprout-verifying.key";
 
+    if (!(boost::filesystem::exists(pk_path) && boost::filesystem::exists(vk_path))) {
+        uiInterface.ThreadSafeMessageBox(strprintf(
+            _("Cannot find the Zcash network parameters in the following directory:\n"
+              "%s\n"
+              "Please run 'zcash-fetch-params' and then restart."),
+                ZC_GetParamsDir()),
+            "", CClientUIInterface::MSG_ERROR);
+        StartShutdown();
```
Comment (str4d) [inline src/init.cpp]: If #1972 is merged before this, add `TriggerRefresh();` above this line.

Comment (str4d) [inline src/init.cpp]: #1972 was updated such that this is no longer necessary.

File: src/init.cpp [hunk 2]
```diff
@@ -621,6 +621,17 @@ static void ZC_LoadParams()
     boost::filesystem::path pk_path = ZC_GetParamsDir() / "sprout-proving.key";
     boost::filesystem::path vk_path = ZC_GetParamsDir() / "sprout-verifying.key";
 
+    if (!(boost::filesystem::exists(pk_path) && boost::filesystem::exists(vk_path))) {
+        uiInterface.ThreadSafeMessageBox(strprintf(
+            _("Cannot find the Zcash network parameters in the following directory:\n"
+              "%s\n"
+              "Please run 'zcash-fetch-params' and then restart."),
```
Comment (ebfull) [inline src/init.cpp]: Suggest `or ./src/fetch-params.sh` as a second option for users that compiled from source.

Comment (str4d) [inline src/init.cpp]: Yeah, I wondered about that, but wasn't sure if it would be too confusing. I'll add it, and we can always tweak it later after user feedback.

**Comment by ebfull** [comment]
ACK

**Comment by bitcartel** [comment]
Soft NACK.  After printing the fetch params message, the cursor is left on the first column of the next line... instead of exiting cleanly to a terminal prompt.  It looks like zcashd is waiting for something or is hanging (zcashd process has in fact shut down).  Pressing return shows the terminal prompt again.

**Comment by bitcartel** [comment]
This issue only exists when zcashd is running in daemon mode.  The parent has already returned from calling AppInit2, whilst the background child process is the one printing out to stderr.  Flushing stdout and stderr was a red herring (but we should be mindful of in the general case).

**Comment by bitcartel** [comment]
ACK
@zkbot r+

**Comment by bitcartel** [comment]
@zkbot retry
