### PR TITLE
Replace "Bitcoin" with "Zcash" in strings

### LINKED ISSUE #1756: Clean up "bitcoin" and "btc" in help strings
Zcashd still produces user-visible references to "bitcoin" and "btc", which can be confusing for users. Should consistently change these to "Zcash" and "ZEC".

For example:
```
$ git grep btc src/
rc/rpcblockchain.cpp:            "  \"value\" : x.xxx,           (numeric) The transaction value in btc\n"
src/rpcmisc.cpp:            "  \"paytxfee\": x.xxxx,         (numeric) the transaction fee set in btc/kb\n"
src/rpcmisc.cpp:            "  \"relayfee\": x.xxxx,         (numeric) minimum relay fee for non-free transactions in btc/kb\n"
src/rpcnet.cpp:            "  \"relayfee\": x.xxxxxxxx,                (numeric) minimum relay fee for non-free transactions in btc/kb\n"
src/rpcrawtransaction.cpp:            "       \"value\" : x.xxx,            (numeric) The value in btc\n"
src/rpcrawtransaction.cpp:            "      \"address\": x.xxx   (numeric, required) The key is the bitcoin address, the value is the btc amount\n"
src/rpcrawtransaction.cpp:            "       \"value\" : x.xxx,            (numeric) The value in btc\n"
src/wallet/rpcwallet.cpp:            "2. \"amount\"      (numeric, required) The amount in btc to send. eg 0.1\n"
src/wallet/rpcwallet.cpp:            "      amount,                 (numeric) The amount in btc\n"
src/wallet/rpcwallet.cpp:            "amount   (numeric) The total amount in btc received at this address.\n"
src/wallet/rpcwallet.cpp:            "amount              (numeric) The total amount in btc received for this account.\n"
src/wallet/rpcwallet.cpp:            "amount              (numeric) The total amount in btc received for this account.\n"
src/wallet/rpcwallet.cpp:            "\nMove 0.01 btc from the default account to the account named tabby\n"
src/wallet/rpcwallet.cpp:            "\nMove 0.01 btc timotei to akiko with a comment and funds have 6 confirmations\n"
src/wallet/rpcwallet.cpp:            "3. amount                (numeric, required) The amount in btc. (transaction fee is added on top).\n"
src/wallet/rpcwallet.cpp:            "\nSend 0.01 btc from the default account to the address, must have at least 1 confirmation\n"
src/wallet/rpcwallet.cpp:            "      \"address\":amount   (numeric) The zcash address is the key, the numeric amount in btc is the value\n"
src/wallet/rpcwallet.cpp:            "    \"amount\" : x.xxx,                  (numeric) The total amount in btc received by the address\n"
src/wallet/rpcwallet.cpp:            "    \"amount\": x.xxx,          (numeric) The amount in btc. This is negative for the 'send' category, and for the\n"
src/wallet/rpcwallet.cpp:            "    \"fee\": x.xxx,             (numeric) The amount of the fee in btc. This is negative and only available for the \n"
src/wallet/rpcwallet.cpp:            "    \"amount\": x.xxx,          (numeric) The amount in btc. This is negative for the 'send' category, and for the 'move' category for moves \n"
src/wallet/rpcwallet.cpp:            "    \"fee\": x.xxx,             (numeric) The amount of the fee in btc. This is negative and only available for the 'send' category of transactions.\n"
src/wallet/rpcwallet.cpp:            "  \"amount\" : x.xxx,        (numeric) The transaction amount in btc\n"
src/wallet/rpcwallet.cpp:            "      \"amount\" : x.xxx                  (numeric) The amount in btc\n"
src/wallet/rpcwallet.cpp:            "    \"amount\" : x.xxx,         (numeric) the transaction amount in btc\n"
```

and:

```
$ git grep '[Bb]itcoin[^-].*\\n' src | grep -v Copyright
src/init.cpp:                strErrors << _("Error loading wallet.dat: Wallet requires newer version of Bitcoin Core") << "\n";
src/init.cpp:                strErrors << _("Wallet needed to be rewritten: restart Bitcoin Core to complete") << "\n";
src/key.cpp:    std::string str = "Bitcoin key verification\n";
src/qt/bitcoin.cpp:    QMessageBox::critical(0, "Runaway exception", BitcoinGUI::tr("A fatal error occurred. Bitcoin can no longer continue safely and will quit.") + QString("\n\n") + message);
src/qt/bitcoinstrings.cpp:"rpcuser=bitcoinrpc\n"
src/qt/bitcoinstrings.cpp:"for example: alertnotify=echo %%s | mail -s \"Bitcoin Alert\" admin@foo.com\n"),
src/qt/guiutil.cpp:            optionFile << "Name=Bitcoin (testnet)\n";
src/qt/guiutil.cpp:            optionFile << "Name=Bitcoin (regtest)\n";
src/rpcblockchain.cpp:            "    \"fee\" : n,              (numeric) transaction fee in bitcoins\n"
src/rpcblockchain.cpp:            "     \"addresses\" : [          (array of string) array of bitcoin addresses\n"
src/rpcblockchain.cpp:            "        \"bitcoinaddress\"     (string) bitcoin address\n"
src/rpcmining.cpp:            "See https://en.bitcoin.it/wiki/BIP_0022 for full specification.\n"
src/rpcmining.cpp:            "See https://en.bitcoin.it/wiki/BIP_0022 for full specification.\n"
src/rpcmisc.cpp:            "  \"balance\": xxxxxxx,         (numeric) the total bitcoin balance of the wallet\n"
src/rpcmisc.cpp:            "validateaddress \"bitcoinaddress\"\n"
src/rpcmisc.cpp:            "\nReturn information about the given bitcoin address.\n"
src/rpcmisc.cpp:            "1. \"bitcoinaddress\"     (string, required) The bitcoin address to validate\n"
src/rpcmisc.cpp:            "  \"address\" : \"bitcoinaddress\", (string) The bitcoin address validated\n"
src/rpcmisc.cpp:            "2. \"keys\"       (string, required) A json array of keys which are bitcoin addresses or hex-encoded public keys\n"
src/rpcmisc.cpp:            "       \"key\"    (string) bitcoin address or hex-encoded public key\n"
src/rpcmisc.cpp:            "verifymessage \"bitcoinaddress\" \"signature\" \"message\"\n"
src/rpcmisc.cpp:            "1. \"bitcoinaddress\"  (string, required) The bitcoin address to use for the signature.\n"
src/rpcnet.cpp:            "         \"address\" : \"192.168.0.201:8233\",  (string) The bitcoin server host and port\n"
src/rpcrawtransaction.cpp:            "           \"bitcoinaddress\"        (string) bitcoin address\n"
src/rpcrawtransaction.cpp:            "      \"address\": x.xxx   (numeric, required) The key is the bitcoin address, the value is the btc amount\n"
src/rpcrawtransaction.cpp:            "           \"12tvKAXCxZjSmdNbao16dKXC8tRWfcF5oc\"   (string) bitcoin address\n"
src/rpcrawtransaction.cpp:            "     \"address\"     (string) bitcoin address\n"
```

Also, "Zcash" is misspelled "zcash" in several user-visible strings.

### PR DESCRIPTION
**Pull request by brunoarueira**
Closes #1756

### CODE REVIEW

File: src/qt/bitcoinstrings.cpp [hunk 1]
```diff
@@ -194,7 +194,7 @@ QT_TRANSLATE_NOOP("bitcoin-core", "Connect only to the specified node(s)"),
 QT_TRANSLATE_NOOP("bitcoin-core", "Connect through SOCKS5 proxy"),
 QT_TRANSLATE_NOOP("bitcoin-core", "Connect to a node to retrieve peer addresses, and disconnect"),
 QT_TRANSLATE_NOOP("bitcoin-core", "Connection options:"),
-QT_TRANSLATE_NOOP("bitcoin-core", "Copyright (C) 2009-%i The Bitcoin Core Developers"),
+QT_TRANSLATE_NOOP("bitcoin-core", "Copyright (C) 2009-%i The Zcash Developers"),
```
Comment (daira) [inline src/qt/bitcoinstrings.cpp]: Bitcoin Core copyright notices can't be deleted. In this case it wouldn't matter very much because we're about to remove the QT wallet anyway, but can you remove either this change, or all the QT changes?

File: src/rpcblockchain.cpp [hunk 2]
```diff
@@ -184,7 +184,7 @@ UniValue getrawmempool(const UniValue& params, bool fHelp)
             "{                           (json object)\n"
             "  \"transactionid\" : {       (json object)\n"
             "    \"size\" : n,             (numeric) transaction size in bytes\n"
-            "    \"fee\" : n,              (numeric) transaction fee in bitcoins\n"
+            "    \"fee\" : n,              (numeric) transaction fee in zec\n"
```
Comment (daira) [inline src/rpcblockchain.cpp]: s/zec/ZEC/

File: src/rpcblockchain.cpp [hunk 3]
```diff
@@ -397,21 +397,21 @@ UniValue gettxout(const UniValue& params, bool fHelp)
...
-            "  \"bestblock\" : \"hash\",    (string) the block hash\n"
-            "  \"confirmations\" : n,       (numeric) The number of confirmations\n"
-            "  \"value\" : x.xxx,           (numeric) The transaction value in btc\n"
-            "  \"scriptPubKey\" : {         (json object)\n"
-            "     \"asm\" : \"code\",       (string) \n"
-            "     \"hex\" : \"hex\",        (string) \n"
-            "     \"reqSigs\" : n,          (numeric) Number of required signatures\n"
+            "  \"bestblock\" : \"hash\",     (string) the block hash\n"
+            "  \"confirmations\" : n,        (numeric) The number of confirmations\n"
+            "  \"value\" : x.xxx,            (numeric) The transaction value in zec\n"
```
Comment (daira) [inline src/rpcblockchain.cpp]: ZEC (and similarly below)

File: src/rpcblockchain.cpp [hunk 4]
```diff
@@ -397,21 +397,21 @@ UniValue gettxout(const UniValue& params, bool fHelp)
...
+            "  \"scriptPubKey\" : {          (json object)\n"
+            "     \"asm\" : \"code\",        (string) \n"
+            "     \"hex\" : \"hex\",         (string) \n"
+            "     \"reqSigs\" : n,           (numeric) Number of required signatures\n"
             "     \"type\" : \"pubkeyhash\", (string) The type, eg pubkeyhash\n"
-            "     \"addresses\" : [          (array of string) array of bitcoin addresses\n"
-            "        \"bitcoinaddress\"     (string) bitcoin address\n"
+            "     \"addresses\" : [          (array of string) array of zcash addresses\n"
+            "        \"zcashaddress\"        (string) zcash address\n"
```
Comment (daira) [inline src/rpcblockchain.cpp]: Zcash address

File: src/rpcblockchain.cpp [hunk 5]
```diff
@@ -397,21 +397,21 @@ UniValue gettxout(const UniValue& params, bool fHelp)
...
+            "  \"confirmations\" : n,        (numeric) The number of confirmations\n"
+            "  \"value\" : x.xxx,            (numeric) The transaction value in zec\n"
+            "  \"scriptPubKey\" : {          (json object)\n"
+            "     \"asm\" : \"code\",        (string) \n"
+            "     \"hex\" : \"hex\",         (string) \n"
+            "     \"reqSigs\" : n,           (numeric) Number of required signatures\n"
             "     \"type\" : \"pubkeyhash\", (string) The type, eg pubkeyhash\n"
-            "     \"addresses\" : [          (array of string) array of bitcoin addresses\n"
-            "        \"bitcoinaddress\"     (string) bitcoin address\n"
+            "     \"addresses\" : [          (array of string) array of zcash addresses\n"
```
Comment (daira) [inline src/rpcblockchain.cpp]: Zcash addresses (and similarly below)

File: src/rpcblockchain.cpp [hunk 6]
```diff
@@ -397,21 +397,21 @@ UniValue gettxout(const UniValue& params, bool fHelp)
...
             "\nResult:\n"
             "{\n"
-            "  \"bestblock\" : \"hash\",    (string) the block hash\n"
-            "  \"confirmations\" : n,       (numeric) The number of confirmations\n"
-            "  \"value\" : x.xxx,           (numeric) The transaction value in btc\n"
-            "  \"scriptPubKey\" : {         (json object)\n"
-            "     \"asm\" : \"code\",       (string) \n"
-            "     \"hex\" : \"hex\",        (string) \n"
-            "     \"reqSigs\" : n,          (numeric) Number of required signatures\n"
+            "  \"bestblock\" : \"hash\",     (string) the block hash\n"
```
Comment (daira) [inline src/rpcblockchain.cpp]: If a line has four escaped quotes, the description should appear two characters further to the right than if it has only two escaped quotes (i.e. the escapes are nonprinting characters).

File: src/wallet/rpcwallet.cpp [hunk 7]
```diff
@@ -419,10 +419,10 @@ UniValue sendtoaddress(const UniValue& params, bool fHelp)
             "\nResult:\n"
             "\"transactionid\"  (string) The transaction id.\n"
             "\nExamples:\n"
-            + HelpExampleCli("sendtoaddress", "\"1M72Sfpbz1BPpXFHz9m3CdqATR44Jvaydd\" 0.1")
-            + HelpExampleCli("sendtoaddress", "\"1M72Sfpbz1BPpXFHz9m3CdqATR44Jvaydd\" 0.1 \"donation\" \"seans outpost\"")
-            + HelpExampleCli("sendtoaddress", "\"1M72Sfpbz1BPpXFHz9m3CdqATR44Jvaydd\" 0.1 \"\" \"\" true")
-            + HelpExampleRpc("sendtoaddress", "\"1M72Sfpbz1BPpXFHz9m3CdqATR44Jvaydd\", 0.1, \"donation\", \"seans outpost\"")
+            + HelpExampleCli("sendtoaddress", "\"tb4oHp2v54vfmdgQ3v3SNuQga8JKHTNi2a1\" 0.1")
```
Comment (daira) [inline src/wallet/rpcwallet.cpp]: This would start with t1.

**Comment by arcalinea** [comment]
@daira I incorporated your comments, would love to get this merged in 1.0.8
Thanks for taking the initiative on this @brunoarueira !

**Comment by arcalinea** [comment]
Rebased on master

File: src/init.cpp [hunk 8]
```diff
@@ -383,6 +383,10 @@ std::string HelpMessage(HelpMessageMode mode)
     strUsage += HelpMessageOpt("-walletnotify=<cmd>", _("Execute command when a wallet transaction changes (%s in cmd is replaced by TxID)"));
     strUsage += HelpMessageOpt("-zapwallettxes=<mode>", _("Delete all wallet transactions and only recover those parts of the blockchain through -rescan on startup") +
         " " + _("(1 = keep tx meta data e.g. account owner and payment request information, 2 = drop tx meta data)"));
+<<<<<<< HEAD
+=======
+
+>>>>>>> Removes out bitcoin mention in favor for zcash
```
Comment (str4d) [inline src/init.cpp]: Shouldn't be here.

File: src/rpcmisc.cpp [hunk 9]
```diff
@@ -61,8 +61,8 @@ UniValue getinfo(const UniValue& params, bool fHelp)
             "  \"keypoololdest\": xxxxxx,    (numeric) the timestamp (seconds since GMT epoch) of the oldest pre-generated key in the key pool\n"
             "  \"keypoolsize\": xxxx,        (numeric) how many new keys are pre-generated\n"
             "  \"unlocked_until\": ttt,      (numeric) the timestamp in seconds since epoch (midnight Jan 1 1970 GMT) that the wallet is unlocked for transfers, or 0 if the wallet is locked\n"
-            "  \"paytxfee\": x.xxxx,         (numeric) the transaction fee set in btc/kb\n"
-            "  \"relayfee\": x.xxxx,         (numeric) minimum relay fee for non-free transactions in btc/kb\n"
+            "  \"paytxfee\": x.xxxx,         (numeric) the transaction fee set in ZEC/kb\n"
```
Comment (str4d) [inline src/rpcmisc.cpp]: These kinds of changes are better-handled IMHO by pulling in bitcoin/bitcoin#6504

File: src/init.cpp (hunk 8 above)
Comment (arcalinea) [inline src/init.cpp]: Ugh thought I got rid of this. Deleting. 

Makes sense to pull in bitcoin/bitcoin#6504 first though

**Comment by arcalinea** [comment]
Sounds good, we can wait on bitcoin/bitcoin#6504 then. 

We should also fix #2109 by making sure the help text displays zcash addresses. I'll open a separate PR for that

**Comment by whyrusleeping** [comment]
Any update here? Getting a message talking about bitcoin when i run two zcashd's in regtest on the same computer (also, side note, zcashd's regtest uses the same port as bitcoin core)

**Comment by arcalinea** [comment]
I lost track of what this was blocking on. @str4d did that PR from upstream ever get pulled in? It would be really great to get this in 1.0.9 regardless, even if it seems like a marginal improvement for now, because it's a big improvement for usability. I'm working with the RPC interface a lot and this is a constant source of annoyance and confusion, and users keep opening new issues about it as well. Can we go ahead and merge this if I rebase again?

**Comment by str4d** [comment]
@arcalinea No - it's a big conflicting PR, which is why I was holding off pulling it in until others of my 0.12 PRs were merged, but I can prioritise doing so if this is being targeted for 1.0.9.

**Comment by nathan-at-least** [comment]
Bumped from 1.0.9 due to Str4d's suggested PR dependency. Note: I didn't read the full backlog, but we're already over capacity for 1.0.9 and this is lower priority.

**Comment by nathan-at-least** [comment]
Bumped again. I apologize for the confusion. On Friday I was hunting for 'simple PRs' to pull into 1.0.9 to test some CI changes, and I had forgotten this was blocked on an upstream PR.

**Comment by daira** [comment]
See also #2548.

**Comment by str4d** [comment]
I have opened #2564 with the upstream PR; this PR should be rebased on master once that merges.

**Comment by bitcartel** [comment]
I've rebased (but can't push to the PR to update).  What's the magic git/github incantation to achieve this?

**Comment by str4d** [comment]
@bitcartel `git push -f` (append your local name for the OP's remote repo if your branch isn't tracking it).

**Comment by bitcartel** [comment]
@str4d Thanks, the -f did the trick.

Since #2564 has closed and been merged, this PR is ready for review and merge.

**Comment by bitcartel** [comment]
@str4d Commits tidied up as discussed.

File: src/rpcblockchain.cpp [hunk 10]
```diff
@@ -519,13 +519,13 @@ UniValue gettxout(const UniValue& params, bool fHelp)
             "     \"hex\" : \"hex\",        (string) \n"
             "     \"reqSigs\" : n,          (numeric) Number of required signatures\n"
             "     \"type\" : \"pubkeyhash\", (string) The type, eg pubkeyhash\n"
-            "     \"addresses\" : [          (array of string) array of bitcoin addresses\n"
-            "        \"bitcoinaddress\"     (string) bitcoin address\n"
+            "     \"addresses\" : [          (array of string) array of Zcash addresses\n"
+            "        \"zcashaddress\"        (string) Zcash address\n"
```
Comment (str4d) [inline src/rpcblockchain.cpp]: I'll assume that these whitespace changes actually make the output line up.

**Comment by str4d** [comment]
@zkbot r+

**Comment by str4d** [comment]
@zkbot r-

**Comment by str4d** [comment]
@zkbot force

**Comment by str4d** [comment]
@zkbot clean

**Comment by str4d** [comment]
@zkbot r+
