### PR TITLE
Fix death gtests on macOS by switching to the threadsafe style

### LINKED ISSUE #4802: gtest stage in full test suite fails in death tests on macOS
Moved from #4792, since that ticket has long comments that are mainly about a different (solved) problem. The test output is abridged.

@rex4539 wrote:
> Not sure if this requires a separate bug, but some tests are failing.
> 
> ```
> [==========] Running 236 tests from 39 test cases.
> [----------] Global test environment set-up.
> [----------] 50 tests from ChecktransactionTests
> [----------] 1 test from checktransaction_tests
> [----------] 2 tests from ConsensusTests
>
> [----------] 9 tests from FoundersRewardTest
> [ RUN      ] FoundersRewardTest.General
> gtest/test_foundersreward.cpp:136: Failure
> Death test: params.GetFoundersRewardScriptAtHeight(0)
>     Result: died but not with expected error.
>   Expected: nHeight
> Actual msg:
> [  DEATH   ] 
> gtest/test_foundersreward.cpp:137: Failure
> Death test: params.GetFoundersRewardScriptAtHeight(maxHeight+1)
>     Result: died but not with expected error.
>   Expected: nHeight
> Actual msg:
> [  DEATH   ] 
> gtest/test_foundersreward.cpp:138: Failure
> Death test: params.GetFoundersRewardAddressAtHeight(0)
>     Result: died but not with expected error.
>   Expected: nHeight
> Actual msg:
> [  DEATH   ] 
> gtest/test_foundersreward.cpp:139: Failure
> Death test: params.GetFoundersRewardAddressAtHeight(maxHeight+1)
>     Result: died but not with expected error.
>   Expected: nHeight
> Actual msg:
> [  DEATH   ] 
> [  FAILED  ] FoundersRewardTest.General (21 ms)
> [ RUN      ] FoundersRewardTest.RegtestGetLastBlockBlossom
> [       OK ] FoundersRewardTest.RegtestGetLastBlockBlossom (0 ms)
> [...]
> [----------] 9 tests from FoundersRewardTest (10068 ms total)
> 
> [----------] 2 tests from FundingStreamsRewardTest
> [----------] 5 tests from WalletZkeysTest
> [----------] 1 test from wallet_zkeys_tests
> [----------] 1 test from tautologies
>
> [----------] 2 tests from AllocatorTests
> [ RUN      ] AllocatorTests.LockedPoolAbortOnDoubleFree
> gtest/test_allocator.cpp:13: Failure
> Death test: pool.free(a0)
>     Result: died but not with expected error.
>   Expected: Arena: invalid or double free
> Actual msg:
> [  DEATH   ] 
> [  FAILED  ] AllocatorTests.LockedPoolAbortOnDoubleFree (5 ms)
> [ RUN      ] AllocatorTests.LockedPoolAbortOnFreeInvalidPointer
> gtest/test_allocator.cpp:21: Failure
> Death test: pool.free(&notInPool)
>     Result: died but not with expected error.
>   Expected: LockedPool: invalid address not pointing to any arena
> Actual msg:
> [  DEATH   ] 
> [  FAILED  ] AllocatorTests.LockedPoolAbortOnFreeInvalidPointer (4 ms)
> [----------] 2 tests from AllocatorTests (9 ms total)
> 
> [----------] 2 tests from CheckBlock
> [----------] 9 tests from ContextualCheckBlockTest
> [----------] 10 tests from DeprecationTest
> [----------] 5 tests from RecursiveDynamicUsageTests
> [----------] 5 tests from EquihashTests
> [----------] 3 tests from History
> [----------] 3 tests from HTTPRPC
> [----------] 4 tests from Joinsplit
> [----------] 1 test from Keys
> [----------] 9 tests from KeystoreTests
> [----------] 2 tests from LibzcashUtils
> [----------] 10 tests from NoteEncryption
> [----------] 6 tests from Mempool
> [----------] 5 tests from MempoolLimitTests
> [----------] 11 tests from merkletree
> [----------] 5 tests from Metrics
> [----------] 1 test from PedersenHash
> [----------] 3 tests from PoW
> [----------] 1 test from Random
> [----------] 2 tests from rpc
> [----------] 2 tests from SaplingNote
> [----------] 5 tests from TimeWarning
> [ RUN      ] TimeWarning.Assertions
> [       OK ] TimeWarning.Assertions (27 ms)
> ```

(I've left this here as an example of a death test that succeeds, because it doesn't check the output to `stderr`.)

> ```
> [----------] 5 tests from TimeWarning (28 ms total)
> [----------] 1 test from Transaction
> [----------] 11 tests from TransactionBuilder
> [----------] 2 tests from TxidTests
> [----------] 6 tests from UpgradesTest
> [----------] 3 tests from Validation
> [----------] 1 test from ZIP32
> [----------] 1 test from paymentdisclosure
>
> [----------] 34 tests from WalletTests
> [...]
> [ RUN      ] WalletTests.CachedWitnessesEmptyChain
> wallet/gtest/test_wallet.cpp:1195: Failure
> Death test: wallet.DecrementNoteWitnesses(&index)
>     Result: died but not with expected error.
>   Expected: .*nWitnessCacheSize > 0.*
> Actual msg:
> [  DEATH   ] 
> [  FAILED  ] WalletTests.CachedWitnessesEmptyChain (40 ms)
> [...]
> [----------] 34 tests from WalletTests (86250 ms total)
> 
> [----------] Global test environment tear-down
> [==========] 236 tests from 39 test cases ran. (278106 ms total)
> [  PASSED  ] 232 tests.
> [  FAILED  ] 4 tests, listed below:
> [  FAILED  ] FoundersRewardTest.General
> [  FAILED  ] AllocatorTests.LockedPoolAbortOnDoubleFree
> [  FAILED  ] AllocatorTests.LockedPoolAbortOnFreeInvalidPointer
> [  FAILED  ] WalletTests.CachedWitnessesEmptyChain
> 
>  4 FAILED TESTS
>   YOU HAVE 1 DISABLED TEST
> ```

### PR DESCRIPTION
**Pull request by daira**
[Tested on macOS](https://github.com/zcash/zcash/issues/4802#issuecomment-714770192). fixes #4802

Signed-off-by: Daira Hopwood <daira@jacaranda.org>

### CODE REVIEW

**Comment by daira** [comment]
This actually might not have fixed MinGW because it might already have been fixed (by updating GoogleTest). Bear with me while I check that.

File: src/gtest/main.cpp [hunk 1]
```diff
@@ -38,7 +38,11 @@ int main(int argc, char **argv) {
     );
 
   testing::InitGoogleMock(&argc, argv);
-  
+
+  // The "threadsafe" style is necessary for correct operation of death/exit
+  // tests on Windows (MinGW) and macOS.
```
Comment (daira) [inline src/gtest/main.cpp:43]:
```suggestion
  // tests on macOS (https://github.com/zcash/zcash/issues/4802).
```

**Review by mdr0id — APPROVED** [review]
Tested ACK on local bare metal Mac

I'm not sure we want to include the travis.yml though since is not fully working ATM.

File: .travis.yml [hunk 2]
```diff
@@ -0,0 +1,81 @@
...
+    - $TRAVIS_BUILD_DIR
+
+jobs:
+  include:
+    - stage: test
+      name: "rpc"
+      script:
+        - echo $TRAVIS_BUILD_DIR
+        - python3 --version
+        - pip3 list | grep simplejson
```
Comment (daira) [inline .travis.yml:40]:
```suggestion
        - pip3 list | grep 'simplejson\|pyblake2'
```

**Comment by daira** [comment]
Removed the `.travis.yml`. @zkbot r+
