### PR TITLE
Replace fix-copyright-headers.py with a script that creates a scripted-diff git commit.

### LINKED ISSUE #2921: Update contrib/devtools/fix-copyright-headers.py to handle Zcash copyright headers
As suggested at https://github.com/zcash/zcash/issues/2887#issuecomment-361712150 .

For bonus points, robustify this script and add running it to the automatic release process.

### PR DESCRIPTION
**Pull request by nuttycom**
This fixes #2921 and supersedes #6338 and #4296.

### CODE REVIEW

File: contrib/devtools/fix-copyright-headers.sh [hunk 1]
```diff
@@ -0,0 +1,17 @@
...
+  | awk -F ':' '{print $1}' \
+  | xargs -I {} sed -i"" -e "s#// Copyright (c) \([0-9]\{4\}\)\(-[0-9]\{4\}\)\? The Zcash developers#// Copyright (c) \1-$current_year The Zcash developers#" {}
+
+git commit -a -F - << EOS
+scripted-diff: Update Zcash copyrights to $current_year
+
+-BEGIN VERIFY SCRIPT-
+git grep "// Copyright (c) .* The Zcash developers" \
+  | awk -F ':' '{print $1}' \
+  | xargs -I {} sed -i"" -e "s#// Copyright (c) \([0-9]\{4\}\)\(-[0-9]\{4\}\)\? The Zcash developers#// Copyright (c) \1-$current_year The Zcash developers#" {}
```
Comment (str4d) [inline contrib/devtools/fix-copyright-headers.sh:15]: For some reason, this fails the scripted diff lint (which apparently isn't able to reproduce any of the date updates).

Separately, how easy would it be to make this a pseudo-quine? That is, the script that is placed between the `-BEGIN VERIFY SCRIPT-` and `-END VERIFY SCRIPT-` is precisely the script that was used?

**Comment by str4d** [comment]
The script should also update the other copyright places that #6338 touches.

File: contrib/devtools/fix-copyright-headers.sh (hunk 1 above)
Comment (nuttycom) [reply contrib/devtools/fix-copyright-headers.sh]: I made some attempts at this, but the escaping is just a bear.

Comment (nuttycom) [reply contrib/devtools/fix-copyright-headers.sh]: Aha, got it.

File: contrib/devtools/fix-copyright-headers.sh [hunk 2]
```diff
@@ -0,0 +1,29 @@
...
+read -r -d '' VERIFY_SCRIPT << EOS
+for party in "The Zcash developers" "The Bitcoin Core developers" "Bitcoin Developers"; do
+  sed -i"" -e "s#Copyright (c) \([0-9]\{4\}\)\(-[0-9]\{4\}\)\? \$party#Copyright (c) \1-$current_year \$party#" COPYING
+  sed -i"" -e "s#\(.*\)\([0-9]\{4\}\)\(-[0-9]\{4\}\)\, \$party#\1\2-$current_year, \$party#" contrib/debian/copyright
+done
+
+sed -i"" -e "s/define(_COPYRIGHT_YEAR, [0-9]\{4\})/define(_COPYRIGHT_YEAR, $current_year)/" configure.ac
+sed -i"" -e "s/#define COPYRIGHT_YEAR [0-9]\{4\}/#define COPYRIGHT_YEAR $current_year/" src/clientversion.h
+
+git grep "^// Copyright (c) .* The Zcash developers" \\
```
Comment (str4d) [inline contrib/devtools/fix-copyright-headers.sh:14]: Nit: this is updating _every_ occurrence of the header, even on files that have not been otherwise altered. I thought that the intention was to only bump the year for files that were modified in 2023, but looking at #5950 again I see that what I was thinking of was that _missing_ Zcash copyright headers were added to files from upstream that had been altered by us, and we just set all of the end dates to 2022. I guess it doesn't matter as long as we are internally consistent for the Zcash copyright headers (and we can always switch later).

**Review by str4d — APPROVED** [review]
utACK. I eyeballed a bit under half the files, and the changes look correct.
