### PR TITLE
#4114 Don't call GetSpentIndex() when converting txs to JSON if spent index is disabled

### LINKED ISSUE #4114: Many `ERROR: spent index not enabled` lines in debug.log
Saw some long runs of repeated lines like this one shortly after updating a node to version 2.0.7.

```
2019-08-23 17:47:37 ERROR: spent index not enabled
```

### PR DESCRIPTION
**Pull request by LarryRuane**
Closes #4114.

### CODE REVIEW

**Comment by LarryRuane** [comment]
Summary: This log message occurs each time the `getrawtransaction` RPC executes if the configuration option `-insightexplorer` isn't enabled.

Detailed explanation: This bug occurred because of trying to make `GetSpentIndex()` similar to `GetAddressIndex()` and `GetAddressUnspent()`. These latter two functions return `error()` in the case of any failure, such as the `-insightexplorer` configuration option isn't enabled. But `GetSpentIndex()` is different because it's called from the `getrawtransaction` RPC, which can run often as part of a normal non-explorer workload, whereas the other two only run when Insight-specific RPCs are invoked. 

The `error()` function returns `false` but has the side-effect of logging the given string to `debug.log`.

The fix is to make this code match upstream, which simply returns `false` if `fSpentIndex` (which indicates if `-insightexplorer` is enabled) is `false`, instead of returning `error()`. I manually tested this fix.

File: src/main.cpp [hunk 1]
```diff
@@ -1633,7 +1633,7 @@ bool GetSpentIndex(CSpentIndexKey &key, CSpentIndexValue &value)
 {
     AssertLockHeld(cs_main);
     if (!fSpentIndex)
-        return error("spent index not enabled");
+        return false;
```
Comment (daira) [inline src/main.cpp]: Why is this different from `GetTimestampIndex`?

**Comment by Eirik0** [comment]
@zkbot r+
