### PR TITLE
simplify locking, merge cs_SpendingKeyStore into cs_KeyStore

### LINKED ISSUE #3823: zcashd assertion `onlyMaybeDeadlock' failed (with --enable-debug build)
See also https://github.com/zcash/zcash/issues/1347

I built zcashd master branch with debugging enabled:
```
CONFIGURE_FLAGS='--enable-debug' zcutil/build.sh
```
Then I started `zcashd` with testnet configured, and the following appeared within a couple of minutes:
```
(.....)
Since starting this node 1 minutes, 57 seconds ago:
- You have validated 46 transactions!

Init message: Loading wallet...

[Press Ctrl+C to exit] [Set 'showmetrics=0' to hide]
zcashd: sync.cpp:112: void potential_deadlock_detected(const std::pair<void*, void*>&, const LockStack&, const LockStack&): Assertion 'onlyMaybeDeadlock' failed.
Aborted (core dumped)
```
The following appeared in `~/.zcashd/testnet3/debug.log`
```
2019-02-01 16:14:51 POTENTIAL DEADLOCK DETECTED
2019-02-01 16:14:51 Previous lock order was:
2019-02-01 16:14:51  pwallet->cs_wallet  wallet/walletdb.cpp:878
2019-02-01 16:14:51  (1) cs_SpendingKeyStore  wallet/crypter.cpp:486
2019-02-01 16:14:51  (2) cs_KeyStore  wallet/crypter.cpp:190
2019-02-01 16:14:51 Current lock order is:
2019-02-01 16:14:51  pwallet->cs_wallet  wallet/walletdb.cpp:878
2019-02-01 16:14:51  (2) cs_KeyStore  wallet/crypter.cpp:382
2019-02-01 16:14:51  (2) cs_KeyStore  wallet/crypter.cpp:190
2019-02-01 16:14:51  (1) cs_SpendingKeyStore  wallet/crypter.cpp:190
```
I wasn't able to reproduce this on mainnet. The difference may be that my testnet wallet contains a fairly substantial number keys, while in mainnet I have only a few. 

Note that it is common (I think) for some `POTENTIAL DEADLOCK DETECTED` messages to appear in `debug.log` but they don't cause an assertion failure, even with a debug build, because `onlyMaybeDeadlock` is `true`. (I will create a ticket for these, as I don't see an existing one.) These non-fatal deadlock detections involve a completely different set of locks.

This one is, apparently, a more "certain" deadlock -- although of course it's not at all certain, because, as far as I'm aware, no actual deadlock has occurred with a non-debug build (at least, there's no ticket that I can find). But this one is "certain" enough to trip the assertion.

I believe I have a simple fix for this; I will create the PR in a moment.

### PR DESCRIPTION
**Pull request by LarryRuane**
Closes #3823.

### CODE REVIEW

**Comment by LarryRuane** [comment]
This fix is an alternative to #3824, addresses @daira comment https://github.com/zcash/zcash/pull/3824#issuecomment-465623274. I prefer this simpler solution too, until such time that more complex locking is shown to be important for performance.

File: src/keystore.h [hunk 1]
```diff
@@ -23,7 +23,6 @@ class CKeyStore
 {
 protected:
     mutable CCriticalSection cs_KeyStore;
-    mutable CCriticalSection cs_SpendingKeyStore;
```
Comment (str4d) [inline src/keystore.h]: With this being removed, the PR would fail to compile if any `cs_SpendingKeyStore` had been missed.

File: src/wallet/crypter.cpp [hunk 2]
```diff
@@ -213,7 +213,7 @@ bool CCryptoKeyStore::Lock()
 bool CCryptoKeyStore::Unlock(const CKeyingMaterial& vMasterKeyIn)
```
Comment (daira) [inline src/wallet/crypter.cpp]: In `CryptoKeyStore::Lock()` at line 201, the test of `!SetCrypted()` should be inside the lock (as it is for `Unlock()`).

File: src/wallet/crypter.cpp [hunk 3]
```diff
@@ -551,7 +551,7 @@ bool CCryptoKeyStore::GetSaplingSpendingKey(const libzcash::SaplingFullViewingKe
 bool CCryptoKeyStore::EncryptKeys(CKeyingMaterial& vMasterKeyIn)
 {
     {
-        LOCK2(cs_KeyStore, cs_SpendingKeyStore);
+        LOCK(cs_KeyStore);
         if (!mapCryptedKeys.empty() || IsCrypted())
             return false;
```
Comment (daira) [inline src/wallet/crypter.cpp]: `fUseCrypto` is written inside the lock (expand just below this comment), but read outside the lock, for example at https://github.com/zcash/zcash/blob/0901007ed5743db5c818f8e1d0a7406b6207bf7c/src/wallet/crypter.h#L158-L173 and in other calls to `IsCrypted()`, for example from `GetKeys` and `GetSproutPaymentAddresses` (defined in the header).

If a lock is needed for concurrent writes then all reads must also be locked; otherwise the behaviour is undefined. It's actually unclear that there's any benefit to having an accessor method, since the temptation would be to put the locking there but that is too fine-grained.

File: src/wallet/crypter.h [hunk 4]
```diff
@@ -250,7 +250,7 @@ class CCryptoKeyStore : public CBasicKeyStore
     bool HaveSaplingSpendingKey(const libzcash::SaplingFullViewingKey &fvk) const
```
Comment (daira) [inline src/wallet/crypter.h]: In `GetKeys` and `GetSproutPaymentAddresses`, it's necessary to lock before calling `IsCrypted()`.

File: src/wallet/wallet.cpp [hunk 5]
```diff
@@ -1725,7 +1725,7 @@ boost::optional<uint256> CWallet::GetSproutNoteNullifier(const JSDescription &js
  */
```
Comment (daira) [inline src/wallet/wallet.cpp]: I have not reviewed `wallet.cpp` for thread safety.

File: src/wallet/crypter.cpp (hunk 3 above)
Comment (daira) [reply src/wallet/crypter.cpp]: I see that `IsCrypted()` is used from outside the class, which means that it must explicitly lock. In that case, accesses to `fUseCrypto` from inside the class should probably be bare accesses with the lock already held.

File: src/wallet/crypter.cpp [hunk 6]
```diff
@@ -185,24 +185,22 @@ static bool DecryptSaplingSpendingKey(const CKeyingMaterial& vMasterKey,
     return sk.expsk.full_viewing_key() == extfvk.fvk;
 }
 
+// cs_KeyStore lock must be held by caller
```
Comment (LarryRuane) [inline src/wallet/crypter.cpp]: This function could `AssertLockHeld(cs_KeyStore)` but I think that adds production runtime overhead, doesn't it? (Not just debug build?)

File: src/wallet/crypter.cpp [hunk 7]
```diff
@@ -185,24 +185,22 @@ static bool DecryptSaplingSpendingKey(const CKeyingMaterial& vMasterKey,
...
 {
-    if (!SetCrypted())
-        return false;
-
     {
         LOCK(cs_KeyStore);
+        if (!SetCrypted())
+            return false;
         vMasterKey.clear();
     }
```
Comment (LarryRuane) [inline src/wallet/crypter.cpp]: For performance reasons, calls to `NotifyStatusChanged()` should be made outside the lock, as is done here (and throughout this file, well, there's only one other place).

File: src/wallet/crypter.cpp [hunk 8]
```diff
@@ -356,140 +352,119 @@ bool CCryptoKeyStore::GetHDSeed(HDSeed& seedOut) const
...
+    std::vector<unsigned char> vchCryptedSecret;
+    CKeyingMaterial vchSecret(key.begin(), key.end());
+    if (!EncryptSecret(vMasterKey, vchSecret, pubkey.GetHash(), vchCryptedSecret))
+        return false;
 
-        if (!AddCryptedKey(pubkey, vchCryptedSecret))
-            return false;
-    }
-    return true;
+    return AddCryptedKey(pubkey, vchCryptedSecret);
```
Comment (LarryRuane) [inline src/wallet/crypter.cpp]: Just simplified the `return` logic slightly (here and in a few other places below), no functional change.

File: src/wallet/crypter.cpp (hunk 2 above)
Comment (daira) [reply src/wallet/crypter.cpp]: Yes, I think this fixes a potential race condition.

File: src/wallet/crypter.cpp (hunk 6 above)
Comment (daira) [reply src/wallet/crypter.cpp]: Since we're removing a lock acquisition here, the AssertLockHeld won't add more overhead than that would have had.

File: src/wallet/wallet.cpp (hunk 5 above)
Comment (daira) [reply src/wallet/wallet.cpp]: I still have not, but I don't think that this PR can introduce any additional threading problems in wallet.cpp.

**Comment by LarryRuane** [comment]
Rebased from master.

**Comment by rex4539** [comment]
Except from fixing https://github.com/zcash/zcash/issues/4170, this PR also fixes https://github.com/zcash/zcash/issues/3825.

**Comment by daira** [comment]
reACK

File: src/wallet/crypter.cpp [hunk 9]
```diff
@@ -185,24 +185,22 @@ static bool DecryptSaplingSpendingKey(const CKeyingMaterial& vMasterKey,
...
 bool CCryptoKeyStore::SetCrypted()
 {
-    LOCK2(cs_KeyStore, cs_SpendingKeyStore);
     if (fUseCrypto)
         return true;
     if (!(mapKeys.empty() && mapSproutSpendingKeys.empty() && mapSaplingSpendingKeys.empty()))
         return false;
-    fUseCrypto = true;
-    return true;
+    return fUseCrypto = true;
```
Comment (daira) [inline src/wallet/crypter.cpp]: I suggest reverting this change (just the last two lines). The fact that it's returning the same value that `fUseCrypto` is set to is arguably a coincidence. The return value of `true` means "successful", not "encrypted". Also the original code makes it look less like there might be an `==` vs `=` confusion.

File: src/wallet/crypter.cpp (hunk 7 above)
Comment (daira) [reply src/wallet/crypter.cpp]: There might also be locking order reasons to call it outside the lock. (I'm not sure, but it looks like a cleaner contract to let the notification handler decide what to lock and in what order.)

File: src/wallet/crypter.cpp (hunk 9 above)
Comment (LarryRuane) [reply src/wallet/crypter.cpp]: Good idea, thanks, done, also rebased onto master, https://github.com/zcash/zcash/pull/3932/commits/e33ebdb8bb84b5cef59561dd40c6be9088a30046.

**Comment by LarryRuane** [comment]
Added a commit to address https://github.com/zcash/zcash/pull/3932#discussion_r341710694, force-pushed due only to rebase.

**Comment by daira** [comment]
@zkbot r+
