### PR TITLE
Lazily load the proving key at time of first pour.

### LINKED ISSUE #599: Split proving / verification parameter loading into different subsystems.
Proving key:

* takes a long time to load.
* only needed for the wallet.
* only needed in the wallet when spending confidential coins (aka "protected buckets").

Verification key:

* takes ~1s to load.
* is required immediately upon node start up as soon as blocks come in *either* from the network or during the startup process (which revalidates the past ~1000 blocks).  (in fact, the public alpha branch crashed in the block-revalidation step due to validation parameter being initialized too late.)

Meanwhile, the existing component architecture is:

* block validation must occur immediately upon startup, where by contrast:
* the wallet is optional, and:
* the wallet loads in a background thread, and there's already an RPC protocol for signaling that the wallet in a node is not ready.

### PR DESCRIPTION
**Pull request by ebfull**
This will make node initialization faster (since reading and deserializing that key takes a while) which should speed up some of our test suite.

Closes #599.

### CODE REVIEW

**Comment by ebfull** [comment]
@zkbot try

**Comment by ebfull** [comment]
I haven't tested zkbot's `try` and I want to see how fast the tests run anyway.

**Comment by daira** [comment]
Reviewing now.

File: src/init.cpp [hunk 1]
```diff
@@ -628,8 +619,8 @@ static void ZC_LoadParams()
 
     pzerocashParams = new libzerocash::ZerocashParams(
         INCREMENTAL_MERKLE_TREE_DEPTH,
-        &pk_loaded,
-        &vk_loaded
+        &vk_loaded,
+        pk_path.string()
```
Comment (daira) [inline src/init.cpp]: It seems odd for the pk and vk-related parameters to be in a different order for the two constructors.

**Comment by daira** [comment]
LGTM modulo https://github.com/zcash/zcash/pull/783/commits/8f8c4c6c0cbcb70fa87c5c0d82eb8671a90d21b1#r56240226 .

File: src/init.cpp (hunk 1 above)
Comment (ebfull) [inline src/init.cpp]: Good catch, I'll change this just for consistency sake.

**Comment by ebfull** [comment]
This saved the RPC tests almost an hour!

**Comment by ebfull** [comment]
@zkbot r+

**Comment by nathan-at-least** [comment]
Concept/Design NACK. I dislike lazy loading API for a few reasons (see https://github.com/zcash/zcash/issues/599#issuecomment-197052973).

However, given the benefit of increased test productivity and the fact that this is already done, I'd be willing to accept it if my preferred design of loading the proving key in the "wallet subcomponent" is too difficult to implement quickly.

**Comment by ebfull** [comment]
I can understand wanting to add a `zcloadpublicparameters` RPC command which pre-loads the proving key at the discretion of the user, as we should not force anyone using the wallet to load the proving keys, since they may not be using pours. And we shouldn't necessarily require a wallet to use pours anyway.

I don't see any benefit to loading if the wallet is enabled. In pretty much all cases, including in our rpc tests, the wallet is enabled.

**Comment by ebfull** [comment]
By the way, the pour takes about 4x the time of performing the pour itself, so this is a small-impact high-benefit change with few good alternatives.

**Comment by zookozcash** [comment]
I dislike the API of automatically doing something the first time it is needed. Many users of the API (programmers) will be confused by this, and either think that it takes that extra time on *every* invocation of the API to generate a proof, or else conversely will think that it never takes that extra time. That's because many programmers don't read API docs, instead they just try a thing and see what it does. Those who try generating a proof, and when they try it, it is the first time in that process will think that generating a proof always takes extra time. Those who try it, and it is not the first time in that process will think that generating a proof never takes the extra time.

I strongly prefer an API where you have an explicit `initialize_proving_key()` or some such call which is the thing that takes the extra time, and then if you try to use the API that generates a proof when you haven't already called `initialize_proving_key()` then you get an exception.

That way programmers will (a) understand that there's a one-time (per process) cost, and (b) be able to control when their app pays that cost.

I'm -2 on "auto-load first time it is needed" API and I'm -1 on "auto-load first time it is needed and also have an optional `initialize_proving_key()` call". I'm +1 on "error if not loaded, and have a required `initialize_proving_key()` call".

**Comment by ebfull** [comment]
I `r+`'d this before I realized how controversial it would be. I filed #789 so we can revisit this ASAP.
