### PR TITLE
Use multithreaded batched trial decryption for Sapling outputs

### LINKED ISSUE #6052: Rescanning wallets on mainnet is slower after height 1,700,000
I just completed a reindex of my node, and the node crashed near the end (for unrelated system issues) in a way that meant when I restarted it, it happened to rescan from almost the beginning to the end (so to be clear, I didn't use `-rescan`, but it was running the rescanning logic). I extracted the times and block heights from the log ("Still rescanning. At block N." lines), and you can see a distinct phase shift in scanning speed:

image

This should not be due to slow block validation speed (#6049) because rescanning happens over the already-indexed local chain state. However they may share a common cause in the recent stretch of very full blocks (though I haven't checked if the slowdown started before the large blocks started).

### PR DESCRIPTION
**Pull request by str4d**
Part of #6052.

### CODE REVIEW

**Comment by str4d** [comment]
Currently a draft PR for two reasons:
- There is a bug somewhere in the fourth and fifth commits: batched trial decryption is working, but the resulting notes aren't being counted in address balances correctly.
- Orchard batching has not yet been implemented.

File: src/rust/src/wallet_scanner.rs [hunk 1]
```diff
@@ -0,0 +1,470 @@
...
+/// Extension trait for things `zcash_note_encryption` doesn't provide that the `zcashd`
+/// wallet needs.
+trait DomainExt: BatchDomain {
+    /// Figures out which incoming viewing key matches the given recipient.
+    ///
+    /// This is linear in the size of `ivks`, but importantly this is only run when an
+    /// output is successfully decrypted, and therefore is not linear in the number of
+    /// on-chain outputs.
+    fn ivk_for_recipient(
+        ivks: &[Self::IncomingViewingKey],
```
Comment (daira) [inline src/rust/src/wallet_scanner.rs:207]: The implementation doesn't depend on this being a slice, it could be an iterable.

File: src/rust/src/wallet_scanner.rs [hunk 2]
```diff
@@ -0,0 +1,470 @@
...
+/// The heights are only for constructing a regtest network, and are ignored otherwise.
+fn network(
+    network: &str,
+    overwinter: i32,
+    sapling: i32,
+    blossom: i32,
+    heartwood: i32,
+    canopy: i32,
+    nu5: i32,
+) -> Result<Box<Network>, &'static str> {
```
[the remark this answers is not in the document]
Comment (str4d) [reply src/rust/src/wallet_scanner.rs:87]: That would require switching everywhere we want to do this (instead of only here) on the C++ side (where we don't have things as nice as the Rust `match`). I might have done this if I could hook it directly into the chainparams logic, but:
- I don't think the compilation units are set up to enable that at the moment, so it would be a more invasive change.
- `cxx` doesn't let you reuse FFI definitions yet, so it can't be a 1:1 mapping for now.

File: src/rust/src/wallet_scanner.rs (hunk 1 above)
Comment (str4d) [reply src/rust/src/wallet_scanner.rs:207]: I've deleted this as it was actually unnecessary.

**Comment by str4d** [comment]
[Force-pushed](https://github.com/zcash/zcash/compare/0b091b236a920ea367c87c6e62c74b5373cea3ef..20adc26341b9c1235781b8032a943bb48d6713e1) earlier to fix lint issues and bugs.

I also pushed a commit (6855dab6e47c9d4bca1f5b73b63527186066a813) that @nuttycom and I discussed in our pairing, reverting some changes made in https://github.com/zcash/zcash/pull/5976/commits/f403f0001707d22d248587986fc90baa41ffba7d that enabled the buggy version of this PR to drop data from the wallet that it shouldn't have.

File: src/validationinterface.cpp [hunk 3]
```diff
@@ -185,6 +215,151 @@ void ThreadNotifyWallets(CBlockIndex *pindexLastTip)
...
+        // Steps 2️⃣, 3️⃣, 5️⃣, 7️⃣, 8️⃣, and 🅰️ are where wallet state is updated,
+        // and the relative order of these updates must be preserved in order to
+        // avoid breaking any internal assumptions that the wallet makes.
+        //
+        // Steps 1️⃣, 4️⃣, 6️⃣, and 9️⃣ can be performed at any time, as long as
+        // their results are available when their respective conditionals are
+        // evaluated. We therefore refactor the above workflow to enable the
+        // trial-decryption work to be batched and parallelised:
+        //
+        // - For each block in the old chain:
```
Comment (daira) [inline src/validationinterface.cpp:253]:
```suggestion
        // - For each block in the old chain, from its tip to the fork point:
```

File: src/validationinterface.cpp [hunk 4]
```diff
@@ -185,6 +215,151 @@ void ThreadNotifyWallets(CBlockIndex *pindexLastTip)
...
+        //   - For each transaction in the block:
+        //     - Accumulate its Sprout, Sapling, and Orchard outputs.
+        // - For each block in the new chain:
```
Comment (daira) [inline src/validationinterface.cpp:256]:
```suggestion
        // - For each block in the new chain, from the fork point to its tip:
```

File: src/validationinterface.cpp [hunk 5]
```diff
@@ -185,6 +215,151 @@ void ThreadNotifyWallets(CBlockIndex *pindexLastTip)
...
+        //   - For each transaction in the block:
+        //     - Accumulate its Sprout, Sapling, and Orchard outputs.
+        //
+        // - 1️⃣4️⃣6️⃣9️⃣ Trial-decrypt the Sprout, Sapling, and Orchard outputs.
+        //   - This can split up and batch the work however is most efficient.
+        //
+        // - For each block in the old chain, from its tip to the fork point:
+        //   - For each transaction in the block:
+        //     - If the transaction has decrypted outputs, or transparent inputs
+        //       that belong to the wallet:
```
Comment (daira) [inline src/validationinterface.cpp:268]: What about spent notes belonging to this wallet that become unspent?

File: src/validationinterface.cpp [hunk 6]
```diff
@@ -185,6 +215,151 @@ void ThreadNotifyWallets(CBlockIndex *pindexLastTip)
...
+        //       - 2️⃣ Add or update the transaction, and mark it as dirty.
+        //   - Update the wallet's view of the chain tip.
+        //     - 3️⃣ In `zcashd`, this is when we decrement note witnesses.
+        // - For each block in the new chain, from the fork point to its tip:
+        //   - For each transaction that became conflicted by this block:
+        //     - If the transaction has decrypted outputs, or transparent inputs
+        //       that belong to the wallet:
```
Comment (daira) [inline src/validationinterface.cpp:275]: What about notes belonging to this wallet that become spent? Also what about transparent outputs belonging to the wallet?

File: src/validationinterface.cpp [hunk 7]
```diff
@@ -185,6 +215,151 @@ void ThreadNotifyWallets(CBlockIndex *pindexLastTip)
...
+        //       - 5️⃣ Add or update the transaction, and mark it as dirty.
+        //   - For each transaction in the block:
+        //     - If the transaction has decrypted outputs, or transparent inputs
+        //       that belong to the wallet:
```
Comment (daira) [inline src/validationinterface.cpp:279]: What about notes belonging to this wallet that become spent? Also what about transparent outputs belonging to the wallet?

File: src/validationinterface.cpp (hunk 6 above)
Comment (daira) [inline src/validationinterface.cpp:275]: I'm not sure whether this needs to take into account spent notes or transparent outputs.

File: src/validationinterface.cpp [hunk 8]
```diff
@@ -185,6 +215,151 @@ void ThreadNotifyWallets(CBlockIndex *pindexLastTip)
...
+        //       - 7️⃣ Add or update the transaction, and mark it as dirty.
+        //   - Update the wallet's view of the chain tip.
+        //     - 8️⃣ In `zcashd`, this is when we increment note witnesses.
+        // - For each transaction in the mempool:
+        //     - If the transaction has decrypted outputs, or transparent inputs
+        //       that belong to the wallet:
```
Comment (daira) [inline src/validationinterface.cpp:285]: I'm not sure whether this needs to take into account spent notes or transparent outputs.

File: src/validationinterface.cpp [hunk 9]
```diff
@@ -185,6 +215,151 @@ void ThreadNotifyWallets(CBlockIndex *pindexLastTip)
...
+        //     - 🅰️ Add or update the transaction, and mark it as dirty.
+
```
Comment (daira) [inline src/validationinterface.cpp:287]: Please add the above labels 1️⃣-9️⃣ and 🅰️ to the implementation below.

File: src/validationinterface.cpp (hunk 5 above)
Comment (daira) [reply src/validationinterface.cpp:268]: At first sight the implementation is calling `SyncWithWallets` for all transactions in the block (and similarly for the other loops below); it isn't filtering outside `SyncWithWallets` as I first read this description as implying.

File: src/validationinterface.h [hunk 10]
```diff
@@ -56,10 +84,55 @@ class CValidationInterface {
...
+    /**
+     * Requests a pointer to the listener's batch scanner for shielded outputs,
+     * if it has one.
+     *
+     * The listener is responsible for managing the memory of the batch scanner.
+     * In practice each listener will have a single persistent batch scanner.
+     *
+     * This is an opportunity for the listener to perform any updating of the
+     * batch scanner's internal state (such as updating its set of incoming
+     * viewing keys).
```
Comment (daira) [inline src/validationinterface.h:122]: Document when `GetBatchScanner` is called (I think it is whenever we move between blocks).

File: src/validationinterface.cpp (hunk 5 above)
Comment (daira) [reply src/validationinterface.cpp:268]: I misunderstood where detection of spentness changes is done; this code is not responsible for that.

File: src/wallet/wallet.cpp [hunk 11]
```diff
@@ -3494,13 +3517,115 @@ bool CWallet::AddToWalletIfInvolvingMe(
     }
 }
 
-void CWallet::SyncTransaction(const CTransaction& tx, const CBlock* pblock, const int nHeight)
+    rust::Box<wallet::BatchScanner> WalletBatchScanner::CreateBatchScanner(CWallet* pwallet) {
```
Comment (daira) [inline src/wallet/wallet.cpp:3520]: Unindent here.

File: src/validationinterface.h [hunk 12]
```diff
@@ -24,6 +24,33 @@ class CValidationInterface;
...
+    /**
+     * Adds a transaction to the batch scanner.
+     */
+    virtual void AddTransaction(
+        const CTransaction &tx,
+        const std::vector<unsigned char> &txBytes,
+        const int nHeight) = 0;
+
+    /**
+     * Flushes any pending batches.
```
Comment (daira) [inline src/validationinterface.h:38]: Can you expand on what this guarantees?

File: src/rust/src/wallet_scanner.rs [hunk 13]
```diff
@@ -0,0 +1,478 @@
...
+{
+    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
+        f.debug_struct("DecryptedNote")
+            .field("ivk", &self.ivk)
+            .field("recipient", &self.recipient)
+            .field("note", &self.note)
+            .field("memo", &self.memo)
+            .finish()
+    }
+}
```
Comment (daira) [inline src/rust/src/wallet_scanner.rs:204]: Why is this not derivable?

Comment (str4d) [reply src/rust/src/wallet_scanner.rs:204]: Because none of the associated types of `Domain` have the `Debug` bound.

File: src/rust/src/wallet_scanner.rs [hunk 14]
```diff
@@ -0,0 +1,478 @@
...
+
+/// A value correlated with an output index.
+struct OutputIndex<V> {
+    /// The index of the output within the corresponding shielded bundle.
+    output_index: usize,
+    /// The value for the output index.
+    value: V,
+}
```
Comment (daira) [inline src/rust/src/wallet_scanner.rs:212]: We don't appear to use any other `V` than `Option<DecryptedNote<D>>`, so could this more simply be
```suggestion
/// An output index and possibly decrypted note.
struct Output<D> {
    /// The index of the output within the corresponding shielded bundle.
    output_index: usize,
    /// The decrypted note if available.
    note: Option<DecryptedNote<D>>,
}
```

File: src/rust/src/wallet_scanner.rs [hunk 15]
```diff
@@ -0,0 +1,478 @@
...
+
+impl BatchScanner {
+    /// Adds the given transaction's shielded outputs to the various batch runners.
+    ///
+    /// After adding the outputs, any accumulated batch of sufficient size is run on the
+    /// global threadpool. Subsequent calls to `Self::add_transaction` will accumulate
+    /// those output kinds into new batches.
+    fn add_transaction(&mut self, tx_bytes: &[u8], height: u32) -> Result<(), io::Error> {
+        // The consensusBranchId parameter is ignored; it is not used in trial decryption.
+        let tx = Transaction::read(tx_bytes, consensus::BranchId::Sprout)?;
```
Comment (daira) [inline src/rust/src/wallet_scanner.rs:416]: I confirmed that the consensus branch ID is just copied into the `data: TransactionData` field of the `Transaction` and does not affect parsing (for v4; it isn't used at all for v5). https://github.com/zcash/librustzcash/blob/37fc28634e811fdf8db9274a0080cff17c6b6a09/zcash_primitives/src/transaction/mod.rs#L507-L618

**Review by daira — APPROVED** [review]
utACK with comments.

**Review by nuttycom — APPROVED** [review]
utACK with minor comments.

File: src/wallet/wallet.cpp [hunk 16]
```diff
@@ -3494,13 +3516,63 @@ bool CWallet::AddToWalletIfInvolvingMe(
...
-void CWallet::SyncTransaction(const CTransaction& tx, const CBlock* pblock, const int nHeight)
-{
-    LOCK(cs_wallet);
-    if (!AddToWalletIfInvolvingMe(Params().GetConsensus(), tx, pblock, nHeight, true))
-        return; // Not one of ours
+    void WalletBatchScanner::AddTransactionToBatch(const CTransaction &tx, const int nHeight)
+    {
+        decryptedNotes.insert(std::make_pair(
+            tx.GetHash(),
+            pwallet->TryDecryptShieldedOutputs(Params().GetConsensus(), tx, nHeight)));
```
[the remark this answers is not in the document]
Comment (str4d) [reply src/wallet/wallet.cpp]: I did that elsewhere, but here specifically this is the interface between the node and its validation listeners, and none of the other listener APIs take the parameters.

I decided it would be both inconsistent for only one of the listener APIs to do so (hence I followed the existing pattern), and also inconsistent with future plans to split the wallet into a separate process: there, you'd set up / agree on the parameters when you register the listener, not in every individual API call.

File: src/rust/src/wallet_scanner.rs [hunk 17]
```diff
@@ -0,0 +1,478 @@
...
+        outputs: &[Output],
+        replier: mpsc::Sender<OutputIndex<Option<DecryptedNote<D>>>>,
+    ) {
+        self.outputs
+            .extend(outputs.iter().cloned().map(|output| (domain(), output)));
+        self.repliers
+            .extend((0..outputs.len()).map(|output_index| OutputIndex {
+                output_index,
+                value: replier.clone(),
+            }));
```
[the remark this answers is not in the document]
Comment (str4d) [reply src/rust/src/wallet_scanner.rs:296]: There's a very good reason for the parallel vectors: the batch trial decryption API takes a `&[(domain, output)]` which can't be obtained as a view over a single vector of tuples. We can consider alternate API designs, but not on the timescale of this PR.

**Comment by str4d** [comment]
[Force-pushed](https://github.com/zcash/zcash/compare/b63e19635f161effa370391694c818b1677915c2..e2f1832d1afb3bcb14be33929f4e864cad4ced49) to fix the bug that was breaking the `wallet_doublespend` test (due to the same transaction being processed multiple times in a `ThreadNotifyWallets` run, but only the first instance getting results), and a small performance cleanup (connected blocks were being batched in the wrong order).

File: src/validationinterface.cpp [hunk 18]
```diff
@@ -185,6 +215,151 @@ void ThreadNotifyWallets(CBlockIndex *pindexLastTip)
...
+        //     - 3️⃣ In `zcashd`, this is when we decrement note witnesses.
+        // - For each block in the new chain, from the fork point to its tip:
+        //   - For each transaction that became conflicted by this block:
+        //     - 4️⃣ Trial-decrypt the transaction's shielded outputs.
+        //     - If the transaction belongs to the wallet:
+        //       - 5️⃣ Add or update the transaction, and mark it as dirty.
+        //   - For each transaction in the block:
+        //     - 6️⃣ Trial-decrypt the transaction's shielded outputs.
+        //     - If the transaction belongs to the wallet:
+        //       - 7️⃣ Add or update the transaction, and mark it as dirty.
```
[the remark this answers is not in the document]
Comment (str4d) [reply src/validationinterface.cpp:237]: No. Every transaction in a block is by definition unconflicted; there cannot exist conflicted transactions in a block.

**Comment by str4d** [comment]
[Force-pushed](https://github.com/zcash/zcash/compare/e2f1832d1afb3bcb14be33929f4e864cad4ced49..1caf6f70df84a4b3ae1a22aa9a17d226bdea691b?w=1) to address comments from @daira and @nuttycom.

File: src/rust/src/wallet_scanner.rs [hunk 19]
```diff
@@ -0,0 +1,525 @@
...
+    /// global threadpool. Subsequent calls to `Self::add_transaction` will accumulate
+    /// those output kinds into new batches.
+    fn add_transaction(
+        &mut self,
+        block_tag: [u8; 32],
+        tx_bytes: &[u8],
+        height: u32,
+    ) -> Result<(), io::Error> {
+        let block_tag = BlockHash(block_tag);
+        // The consensusBranchId parameter is ignored; it is not used in trial decryption.
```
Comment (daira) [inline src/rust/src/wallet_scanner.rs:456]:
```suggestion
        // The consensusBranchId parameter is ignored; it is not used in trial decryption
        // and does not affect transaction parsing.
```

File: src/validationinterface.cpp [hunk 20]
```diff
@@ -62,10 +64,39 @@ void UnregisterAllValidationInterfaces() {
...
     g_signals.SyncTransaction.disconnect_all_slots();
+    g_signals.GetBatchScanner.disconnect_all_slots();
     g_signals.UpdatedBlockTip.disconnect_all_slots();
 }
 
-void SyncWithWallets(const CTransaction &tx, const CBlock *pblock, const int nHeight) {
+void AddTxToBatches(
+    std::vector<BatchScanner*> &batchScanners,
+    const CTransaction &tx,
+    const uint256 &blockTag,
```
Comment (daira) [inline src/validationinterface.cpp:74]: In all the functions in `wallet_scanner.rs` that take a block tag argument, that argument comes before the tx information. Non-blocking suggestion: do the same in the C++ code for consistency.

Comment (daira) [reply src/validationinterface.cpp:74]: Oh, pblock came after tx already in `SyncWithWallets`. Ok I guess this order makes sense as-is, then.

**Review by nuttycom — APPROVED** [review]
utACK https://github.com/zcash/zcash/pull/6088/commits/1caf6f70df84a4b3ae1a22aa9a17d226bdea691b

File: src/validationinterface.h [hunk 21]
```diff
@@ -56,10 +94,56 @@ class CValidationInterface {
...
+     * updating its set of incoming viewing keys).
+     *
+     * Listeners of this signal should not listen to `SyncTransaction` or they
+     * will be notified about transactions twice.
+     */
+    boost::signals2::signal<
+        BatchScanner* (),
+        aggregate_non_null_values<std::vector<BatchScanner*>>> GetBatchScanner;
+    /**
+     * Notifies listeners of updated transaction data (transaction, and optionally the block it is found in.
```
Comment (daira) [inline src/validationinterface.h:142]:
```suggestion
     * Notifies listeners of updated transaction data (the transaction, and
     * optionally the block it is found in).
```

File: src/wallet/wallet.cpp [hunk 22]
```diff
@@ -3494,13 +3517,120 @@ bool CWallet::AddToWalletIfInvolvingMe(
...
+    const int nHeight,
+    bool fUpdate)
 {
-    LOCK(cs_wallet);
-    if (!AddToWalletIfInvolvingMe(Params().GetConsensus(), tx, pblock, nHeight, true))
+    AssertLockHeld(pwallet->cs_wallet);
+
+    auto decryptedNotesForTx = decryptedNotes.find(tx.GetHash());
+    if (decryptedNotesForTx == decryptedNotes.end()) {
+        throw std::logic_error("Called SyncTransaction with a tx that wasn't passed to AddTransaction");
```
Comment (daira) [inline src/wallet/wallet.cpp:3557]:
```suggestion
        throw std::logic_error("Called WalletBatchScanner::AddToWalletIfInvolvingMe with a tx that wasn't passed to AddTransaction");
```

**Comment by daira** [comment]
This PR relies on `std::sync::mpsc`. Reading through all of https://github.com/rust-lang/rust/issues/39364 and the description of https://github.com/rust-lang/rust/pull/93563, I think the reliability of that API is highly questionable. Note that https://github.com/rust-lang/rust/issues/39364 was opened in January 2017 and has not been fixed despite frequent discussion and several *proposed* fixes during that time. Some quotes from people who seem to know what they're talking about:

> All is still not rosy, since a some new race condition can rear their head with among other things "impossible asserts" in inherit blocker - after some 10000s iterations.

> It could be that "let sleeper = match p.upgrade(rx)" triggers a pointer swap in the RX thread, that modifies the newly created shared channel before inherit sleepers gets a chance to do the asserts. This kind of makes me question the soundness of the whole mpsc lib :-(

and

> The reason https://github.com/rust-lang/rust/issues/39364 has not been fixed in over 5 years is that the current [mpsc] channel is incredibly complex. It was written many years ago and has sat mostly untouched since.

My impression is that no-one understands the race conditions in its implementation (which are **not** limited to `recv_timeout` as the doc might suggest) well enough to be confident merging any particular fix. The most recent proposed fix (https://github.com/rust-lang/rust/pull/93563) rips out the whole implementation and replaces it with a wrapper over (a fork of) `crossbeam_channel`.

I recommend switching this PR to directly use `crossbeam_channel`, which we already depend on via `rayon` and `tracing_appender`. The doc of that crate describes it as follows:
> This crate is an alternative to [std::sync::mpsc](https://doc.rust-lang.org/nightly/std/sync/mpsc/index.html) with more features and better performance.

The API seems very similar to `std::sync::mpsc`.

While in principle it *should* be possible to implement an MPSC channel that is more performant than an MPMC channel, that doesn't matter in practice if the implementation of the former is broken.

File: src/rust/src/wallet_scanner.rs [hunk 23]
```diff
@@ -1,8 +1,8 @@
 use core::fmt;
+use crossbeam_channel::{self, Receiver, Sender};
```
Comment (str4d) [inline src/rust/src/wallet_scanner.rs:2]: This was added to the wrong block of imports.

**Comment by nuttycom** [comment]
> While in principle it should be possible to implement an MPSC channel that is more performant than an MPMC channel, that doesn't matter in practice if the implementation of the former is broken or not well-maintained.

Also, the performance of the channel is *not* going to be a limiting factor in our use case.

**Review by str4d — COMMENTED** [review]
`crossbeam` change is fine with me.

**Review by nuttycom — APPROVED** [review]
utACK https://github.com/zcash/zcash/pull/6088/commits/7d1e14ac3d876f2f019e22c1adbf15c5949e9f84

**Review by ebfull — APPROVED** [review]
