### PR TITLE
Fix use after free in transaction_tests.

### LINKED ISSUE #2026: heap-use-after-free in usage of JSDescription
I was trying to diagnose [this ASan failure in Boost](https://ci.z.cash/builders/zcashASan/builds/114/steps/full-test-suite.sh/logs/stdio). I haven't been able to recreate it locally - instead the test code continues, and throws an actual problem with our code:

```
$ ./src/test/test_bitcoin 
Running 198 test cases...
(enter) Call to r1cs_ppzksnark_generator   	[             ]	(1484746581.9428s x0.00 from start)
  (enter) Call to r1cs_constraint_system::swap_AB_if_beneficial	[             ]	(1484746582.9143s x0.00 from start)
    (enter) Estimate densities                 	[             ]	(1484746582.9143s x0.00 from start)
      * Non-zero A-count (estimate): 1141154
      * Non-zero B-count (estimate): 1379738
    (leave) Estimate densities                 	[0.3403s x1.00]	(1484746583.2546s x0.00 from start)
    (enter) Perform the swap                   	[             ]	(1484746583.2546s x0.00 from start)
    (leave) Perform the swap                   	[0.0170s x1.00]	(1484746583.2716s x0.00 from start)
  (leave) Call to r1cs_constraint_system::swap_AB_if_beneficial	[0.3574s x1.00]	(1484746583.2717s x0.00 from start)
  (enter) Call to r1cs_to_qap_instance_map_with_evaluation	[             ]	(1484746583.2717s x0.00 from start)
    * Selected domain: basic_radix2
    (enter) Compute evaluations of A, B, C, H at t	[             ]	(1484746583.4642s x0.00 from start)
    (leave) Compute evaluations of A, B, C, H at t	[7.3208s x1.00]	(1484746590.7851s x0.00 from start)
  (leave) Call to r1cs_to_qap_instance_map_with_evaluation	[7.5134s x1.00]	(1484746590.7851s x0.00 from start)
  * QAP number of variables: 1887090
  * QAP pre degree: 2068650
  * QAP degree: 2097152
  * QAP number of input variables: 9
  (enter) Compute query densities            	[             ]	(1484746590.8079s x0.00 from start)
  (leave) Compute query densities            	[0.0317s x1.00]	(1484746590.8396s x0.00 from start)
  Choosing window size 20 for 11258419 elements
  Choosing window size 17 for 1141154 elements
  * G1 window: 20
  * G2 window: 17
  (enter) Generating G1 multiexp table       	[             ]	(1484746591.5090s x0.00 from start)
  (leave) Generating G1 multiexp table       	[15.2282s x1.00]	(1484746606.7372s x0.00 from start)
  (enter) Generating G2 multiexp table       	[             ]	(1484746606.7372s x0.00 from start)
  (leave) Generating G2 multiexp table       	[11.3182s x1.00]	(1484746618.0554s x0.00 from start)
  (enter) Generate R1CS proving key          	[             ]	(1484746618.0555s x0.00 from start)
    (enter) Generate knowledge commitments     	[             ]	(1484746618.0555s x0.00 from start)
      (enter) Compute the A-query                	[             ]	(1484746618.0555s x0.00 from start)
      Non-zero coordinate count: 1379738/1887092 (73.11%)
      (leave) Compute the A-query                	[24.6005s x3.78]	(1484746642.6560s x0.00 from start)
      (enter) Compute the B-query                	[             ]	(1484746642.6560s x0.00 from start)
      Non-zero coordinate count: 1141155/1887092 (60.47%)
      (leave) Compute the B-query                	[63.0438s x3.88]	(1484746705.6998s x0.00 from start)
      (enter) Compute the C-query                	[             ]	(1484746705.6998s x0.00 from start)
      Non-zero coordinate count: 1686772/1887092 (89.38%)
      (leave) Compute the C-query                	[30.7996s x3.82]	(1484746736.4994s x0.00 from start)
      (enter) Compute the H-query                	[             ]	(1484746736.4995s x0.00 from start)
      .................................................................................................................................................................................................................. DONE!
      (leave) Compute the H-query                	[18.3822s x3.87]	(1484746754.8817s x0.00 from start)
      (enter) Compute the K-query                	[             ]	(1484746754.8817s x0.00 from start)
      ............................................................................................................................................................................................. DONE!
      (leave) Compute the K-query                	[17.1414s x3.77]	(1484746772.0231s x0.00 from start)
    (leave) Generate knowledge commitments     	[153.9677s x3.84]	(1484746772.0232s x0.00 from start)
  (leave) Generate R1CS proving key          	[153.9678s x3.84]	(1484746772.0233s x0.00 from start)
  (enter) Generate R1CS verification key     	[             ]	(1484746772.0233s x0.00 from start)
    (enter) Encode IC query for R1CS verification key	[             ]	(1484746772.0352s x0.00 from start)
      . DONE!
    (leave) Encode IC query for R1CS verification key	[0.0013s x3.41]	(1484746772.0365s x0.00 from start)
  (leave) Generate R1CS verification key     	[0.0133s x3.82]	(1484746772.0366s x0.00 from start)
(leave) Call to r1cs_ppzksnark_generator   	[190.0939s x3.30]	(1484746772.0367s x0.00 from start)
* G1 elements in PK: 13419707
* Non-zero G1 elements in PK: 11258422
* G2 elements in PK: 1887092
* Non-zero G2 elements in PK: 1141155
* PK size in bits: 3721036065
* G1 elements in VK: 11
* G2 elements in VK: 5
* VK size in bits: 6181
(enter) Call to r1cs_ppzksnark_verifier_process_vk	[             ]	(1484746774.5154s x0.00 from start)
  (enter) Call to alt_bn128_ate_precompute_G2	[             ]	(1484746774.5154s x0.00 from start)
  (leave) Call to alt_bn128_ate_precompute_G2	[0.0007s x1.00]	(1484746774.5161s x0.00 from start)
  (enter) Call to alt_bn128_ate_precompute_G2	[             ]	(1484746774.5161s x0.00 from start)
  (leave) Call to alt_bn128_ate_precompute_G2	[0.0007s x1.00]	(1484746774.5168s x0.00 from start)
  (enter) Call to alt_bn128_ate_precompute_G1	[             ]	(1484746774.5168s x0.00 from start)
  (leave) Call to alt_bn128_ate_precompute_G1	[0.0000s x1.12]	(1484746774.5168s x0.00 from start)
  (enter) Call to alt_bn128_ate_precompute_G2	[             ]	(1484746774.5168s x0.00 from start)
  (leave) Call to alt_bn128_ate_precompute_G2	[0.0007s x1.00]	(1484746774.5175s x0.00 from start)
  (enter) Call to alt_bn128_ate_precompute_G2	[             ]	(1484746774.5175s x0.00 from start)
  (leave) Call to alt_bn128_ate_precompute_G2	[0.0007s x1.00]	(1484746774.5182s x0.00 from start)
  (enter) Call to alt_bn128_ate_precompute_G2	[             ]	(1484746774.5182s x0.00 from start)
  (leave) Call to alt_bn128_ate_precompute_G2	[0.0006s x1.00]	(1484746774.5188s x0.00 from start)
  (enter) Call to alt_bn128_ate_precompute_G1	[             ]	(1484746774.5188s x0.00 from start)
  (leave) Call to alt_bn128_ate_precompute_G1	[0.0000s x1.05]	(1484746774.5188s x0.00 from start)
  (enter) Call to alt_bn128_ate_precompute_G2	[             ]	(1484746774.5188s x0.00 from start)
  (leave) Call to alt_bn128_ate_precompute_G2	[0.0006s x1.00]	(1484746774.5195s x0.00 from start)
(leave) Call to r1cs_ppzksnark_verifier_process_vk	[0.0041s x1.00]	(1484746774.5195s x0.00 from start)
(enter) Call to r1cs_constraint_system::swap_AB_if_beneficial	[             ]	(1484746788.8671s x0.00 from start)
  (enter) Estimate densities                 	[             ]	(1484746788.8672s x0.00 from start)
    * Non-zero A-count (estimate): 1141154
    * Non-zero B-count (estimate): 1379738
  (leave) Estimate densities                 	[0.4284s x1.00]	(1484746789.2956s x0.00 from start)
  (enter) Perform the swap                   	[             ]	(1484746789.2956s x0.00 from start)
  (leave) Perform the swap                   	[0.0175s x1.00]	(1484746789.3132s x0.00 from start)
(leave) Call to r1cs_constraint_system::swap_AB_if_beneficial	[0.4460s x1.00]	(1484746789.3132s x0.00 from start)
(enter) Call to r1cs_ppzksnark_prover      	[             ]	(1484746789.3132s x0.00 from start)
  (enter) Compute the polynomial H           	[             ]	(1484746789.3132s x0.00 from start)
    (enter) Call to r1cs_to_qap_witness_map    	[             ]	(1484746789.3132s x0.00 from start)
      * Selected domain: basic_radix2
      (enter) Compute evaluation of polynomials A, B on set S	[             ]	(1484746791.1899s x0.00 from start)
      (leave) Compute evaluation of polynomials A, B on set S	[1.2154s x1.00]	(1484746792.4053s x0.00 from start)
      (enter) Compute coefficients of polynomial A	[             ]	(1484746792.4054s x0.00 from start)
        (enter) Execute inverse FFT                	[             ]	(1484746792.4054s x0.00 from start)
          (enter) Shuffle inputs                     	[             ]	(1484746792.4054s x0.00 from start)
          (leave) Shuffle inputs                     	[0.5905s x3.64]	(1484746792.9959s x0.00 from start)
          (enter) Execute sub-FFTs                   	[             ]	(1484746792.9960s x0.00 from start)
          (leave) Execute sub-FFTs                   	[1.5625s x3.95]	(1484746794.5584s x0.00 from start)
          (enter) Re-shuffle outputs                 	[             ]	(1484746794.5586s x0.00 from start)
          (leave) Re-shuffle outputs                 	[0.0136s x3.68]	(1484746794.5722s x0.00 from start)
        (leave) Execute inverse FFT                	[2.3012s x3.72]	(1484746794.7066s x0.00 from start)
      (leave) Compute coefficients of polynomial A	[2.3012s x3.72]	(1484746794.7066s x0.00 from start)
      (enter) Compute coefficients of polynomial B	[             ]	(1484746794.7066s x0.00 from start)
        (enter) Execute inverse FFT                	[             ]	(1484746794.7066s x0.00 from start)
          (enter) Shuffle inputs                     	[             ]	(1484746794.7066s x0.00 from start)
          (leave) Shuffle inputs                     	[0.6137s x3.51]	(1484746795.3203s x0.00 from start)
          (enter) Execute sub-FFTs                   	[             ]	(1484746795.3203s x0.00 from start)
          (leave) Execute sub-FFTs                   	[1.6137s x3.92]	(1484746796.9340s x0.00 from start)
          (enter) Re-shuffle outputs                 	[             ]	(1484746796.9340s x0.00 from start)
          (leave) Re-shuffle outputs                 	[0.0093s x4.00]	(1484746796.9433s x0.00 from start)
        (leave) Execute inverse FFT                	[2.3390s x3.70]	(1484746797.0456s x0.00 from start)
      (leave) Compute coefficients of polynomial B	[2.3391s x3.70]	(1484746797.0456s x0.00 from start)
      (enter) Compute ZK-patch                   	[             ]	(1484746797.0457s x0.00 from start)
      (leave) Compute ZK-patch                   	[0.1907s x3.06]	(1484746797.2364s x0.00 from start)
      (enter) Compute evaluation of polynomial A on set T	[             ]	(1484746797.2364s x0.00 from start)
        (enter) Execute coset FFT                  	[             ]	(1484746797.2364s x0.00 from start)
          (enter) Execute FFT                        	[             ]	(1484746797.4471s x0.00 from start)
            (enter) Shuffle inputs                     	[             ]	(1484746797.4472s x0.00 from start)
            (leave) Shuffle inputs                     	[0.6193s x3.74]	(1484746798.0664s x0.00 from start)
            (enter) Execute sub-FFTs                   	[             ]	(1484746798.0665s x0.00 from start)
            (leave) Execute sub-FFTs                   	[1.6235s x3.95]	(1484746799.6900s x0.00 from start)
            (enter) Re-shuffle outputs                 	[             ]	(1484746799.6901s x0.00 from start)
            (leave) Re-shuffle outputs                 	[0.0183s x3.52]	(1484746799.7085s x0.00 from start)
          (leave) Execute FFT                        	[2.2696s x3.89]	(1484746799.7168s x0.00 from start)
        (leave) Execute coset FFT                  	[2.4804s x3.66]	(1484746799.7168s x0.00 from start)
      (leave) Compute evaluation of polynomial A on set T	[2.4805s x3.66]	(1484746799.7169s x0.00 from start)
      (enter) Compute evaluation of polynomial B on set T	[             ]	(1484746799.7169s x0.00 from start)
        (enter) Execute coset FFT                  	[             ]	(1484746799.7169s x0.00 from start)
          (enter) Execute FFT                        	[             ]	(1484746799.9316s x0.00 from start)
            (enter) Shuffle inputs                     	[             ]	(1484746799.9316s x0.00 from start)
            (leave) Shuffle inputs                     	[0.6307s x3.71]	(1484746800.5623s x0.00 from start)
            (enter) Execute sub-FFTs                   	[             ]	(1484746800.5624s x0.00 from start)
            (leave) Execute sub-FFTs                   	[1.6419s x3.95]	(1484746802.2043s x0.00 from start)
            (enter) Re-shuffle outputs                 	[             ]	(1484746802.2043s x0.00 from start)
            (leave) Re-shuffle outputs                 	[0.0094s x3.99]	(1484746802.2137s x0.00 from start)
          (leave) Execute FFT                        	[2.2950s x3.88]	(1484746802.2266s x0.00 from start)
        (leave) Execute coset FFT                  	[2.5098s x3.65]	(1484746802.2267s x0.00 from start)
      (leave) Compute evaluation of polynomial B on set T	[2.5099s x3.65]	(1484746802.2268s x0.00 from start)
      (enter) Compute evaluation of polynomial H on set T	[             ]	(1484746802.2269s x0.00 from start)
        (enter) Compute evaluation of polynomial C on set S	[             ]	(1484746802.3047s x0.00 from start)
        (leave) Compute evaluation of polynomial C on set S	[0.6432s x1.02]	(1484746802.9479s x0.00 from start)
        (enter) Compute coefficients of polynomial C	[             ]	(1484746802.9480s x0.00 from start)
          (enter) Execute inverse FFT                	[             ]	(1484746802.9480s x0.00 from start)
            (enter) Shuffle inputs                     	[             ]	(1484746802.9480s x0.00 from start)
            (leave) Shuffle inputs                     	[0.6084s x3.69]	(1484746803.5564s x0.00 from start)
            (enter) Execute sub-FFTs                   	[             ]	(1484746803.5564s x0.00 from start)
            (leave) Execute sub-FFTs                   	[1.8062s x3.49]	(1484746805.3626s x0.00 from start)
            (enter) Re-shuffle outputs                 	[             ]	(1484746805.3626s x0.00 from start)
            (leave) Re-shuffle outputs                 	[0.0289s x2.54]	(1484746805.3915s x0.00 from start)
          (leave) Execute inverse FFT                	[2.5790s x3.41]	(1484746805.5269s x0.00 from start)
        (leave) Compute coefficients of polynomial C	[2.5790s x3.41]	(1484746805.5270s x0.00 from start)
        (enter) Compute evaluation of polynomial C on set T	[             ]	(1484746805.5270s x0.00 from start)
          (enter) Execute coset FFT                  	[             ]	(1484746805.5270s x0.00 from start)
            (enter) Execute FFT                        	[             ]	(1484746805.7702s x0.00 from start)
              (enter) Shuffle inputs                     	[             ]	(1484746805.7703s x0.00 from start)
              (leave) Shuffle inputs                     	[0.6417s x3.73]	(1484746806.4120s x0.00 from start)
              (enter) Execute sub-FFTs                   	[             ]	(1484746806.4122s x0.00 from start)
              (leave) Execute sub-FFTs                   	[1.6966s x3.84]	(1484746808.1088s x0.00 from start)
              (enter) Re-shuffle outputs                 	[             ]	(1484746808.1089s x0.00 from start)
              (leave) Re-shuffle outputs                 	[0.0097s x3.95]	(1484746808.1186s x0.00 from start)
            (leave) Execute FFT                        	[2.3594s x3.81]	(1484746808.1296s x0.00 from start)
          (leave) Execute coset FFT                  	[2.6027s x3.55]	(1484746808.1298s x0.00 from start)
        (leave) Compute evaluation of polynomial C on set T	[2.6029s x3.55]	(1484746808.1299s x0.00 from start)
        (enter) Divide by Z on set T               	[             ]	(1484746808.1541s x0.00 from start)
        (leave) Divide by Z on set T               	[0.1135s x1.37]	(1484746808.2676s x0.00 from start)
      (leave) Compute evaluation of polynomial H on set T	[6.0407s x3.18]	(1484746808.2677s x0.00 from start)
      (enter) Compute coefficients of polynomial H	[             ]	(1484746808.2677s x0.00 from start)
        (enter) Execute inverse coset IFFT         	[             ]	(1484746808.2677s x0.00 from start)
          (enter) Execute inverse FFT                	[             ]	(1484746808.2677s x0.00 from start)
            (enter) Shuffle inputs                     	[             ]	(1484746808.2677s x0.00 from start)
            (leave) Shuffle inputs                     	[0.6496s x3.72]	(1484746808.9173s x0.00 from start)
            (enter) Execute sub-FFTs                   	[             ]	(1484746808.9173s x0.00 from start)
            (leave) Execute sub-FFTs                   	[1.6835s x3.92]	(1484746810.6008s x0.00 from start)
            (enter) Re-shuffle outputs                 	[             ]	(1484746810.6008s x0.00 from start)
            (leave) Re-shuffle outputs                 	[0.0093s x3.99]	(1484746810.6102s x0.00 from start)
          (leave) Execute inverse FFT                	[2.4563s x3.75]	(1484746810.7240s x0.00 from start)
        (leave) Execute inverse coset IFFT         	[2.6691s x3.53]	(1484746810.9367s x0.00 from start)
      (leave) Compute coefficients of polynomial H	[2.6691s x3.53]	(1484746810.9368s x0.00 from start)
      (enter) Compute sum of H and ZK-patch      	[             ]	(1484746810.9368s x0.00 from start)
      (leave) Compute sum of H and ZK-patch      	[0.0209s x3.47]	(1484746810.9576s x0.00 from start)
    (leave) Call to r1cs_to_qap_witness_map    	[21.6444s x3.13]	(1484746810.9577s x0.00 from start)
  (leave) Compute the polynomial H           	[21.7233s x3.13]	(1484746811.0365s x0.00 from start)
  (enter) Compute the proof                  	[             ]	(1484746811.0411s x0.00 from start)
    (enter) Compute answer to A-query          	[             ]	(1484746811.0411s x0.00 from start)
    (enter) Process scalar vector              	[             ]	(1484746811.0411s x0.00 from start)
    (leave) Process scalar vector              	[1.6668s x1.00]	(1484746812.7079s x0.00 from start)
    (leave) Compute answer to A-query          	[1.8412s x1.27]	(1484746812.8823s x0.00 from start)
    (enter) Compute answer to B-query          	[             ]	(1484746812.8823s x0.00 from start)
    (enter) Process scalar vector              	[             ]	(1484746812.8825s x0.00 from start)
    (leave) Process scalar vector              	[4.0740s x1.01]	(1484746816.9564s x0.00 from start)
    (leave) Compute answer to B-query          	[4.0741s x1.01]	(1484746816.9565s x0.00 from start)
    (enter) Compute answer to C-query          	[             ]	(1484746816.9565s x0.00 from start)
    (enter) Process scalar vector              	[             ]	(1484746816.9565s x0.00 from start)
    (leave) Process scalar vector              	[1.9899s x1.00]	(1484746818.9464s x0.00 from start)
    (leave) Compute answer to C-query          	[2.2440s x1.33]	(1484746819.2005s x0.00 from start)
    (enter) Compute answer to H-query          	[             ]	(1484746819.2006s x0.00 from start)
    (leave) Compute answer to H-query          	[27.9494s x3.90]	(1484746847.1500s x0.00 from start)
    (enter) Compute answer to K-query          	[             ]	(1484746847.1500s x0.00 from start)
    (enter) Process scalar vector              	[             ]	(1484746847.1500s x0.00 from start)
    (leave) Process scalar vector              	[1.1408s x1.04]	(1484746848.2909s x0.00 from start)
    (leave) Compute answer to K-query          	[1.2877s x1.35]	(1484746848.4377s x0.00 from start)
  (leave) Compute the proof                  	[37.3966s x3.22]	(1484746848.4377s x0.00 from start)
(leave) Call to r1cs_ppzksnark_prover      	[59.1245s x3.18]	(1484746848.4377s x0.00 from start)
(enter) Call to r1cs_ppzksnark_online_verifier_strong_IC	[             ]	(1484746849.6801s x0.00 from start)
  (enter) Call to alt_bn128_ate_precompute_G1	[             ]	(1484746849.6814s x0.00 from start)
  (leave) Call to alt_bn128_ate_precompute_G1	[0.0000s x3.49]	(1484746849.6814s x0.00 from start)
  (enter) Call to alt_bn128_ate_precompute_G1	[             ]	(1484746849.6814s x0.00 from start)
  (leave) Call to alt_bn128_ate_precompute_G1	[0.0000s x3.29]	(1484746849.6814s x0.00 from start)
  (enter) Call to alt_bn128_ate_miller_loop  	[             ]	(1484746849.6814s x0.00 from start)
  (leave) Call to alt_bn128_ate_miller_loop  	[0.0017s x3.99]	(1484746849.6832s x0.00 from start)
  (enter) Call to alt_bn128_ate_miller_loop  	[             ]	(1484746849.6832s x0.00 from start)
  (leave) Call to alt_bn128_ate_miller_loop  	[0.0017s x3.99]	(1484746849.6848s x0.00 from start)
  (enter) Call to alt_bn128_final_exponentiation	[             ]	(1484746849.6849s x0.00 from start)
    (enter) Call to alt_bn128_final_exponentiation_first_chunk	[             ]	(1484746849.6849s x0.00 from start)
    (leave) Call to alt_bn128_final_exponentiation_first_chunk	[0.0001s x3.90]	(1484746849.6850s x0.00 from start)
    (enter) Call to alt_bn128_final_exponentiation_last_chunk	[             ]	(1484746849.6850s x0.00 from start)
      (enter) Call to alt_bn128_exp_by_neg_z     	[             ]	(1484746849.6850s x0.00 from start)
      (leave) Call to alt_bn128_exp_by_neg_z     	[0.0009s x3.99]	(1484746849.6859s x0.00 from start)
      (enter) Call to alt_bn128_exp_by_neg_z     	[             ]	(1484746849.6859s x0.00 from start)
      (leave) Call to alt_bn128_exp_by_neg_z     	[0.0009s x3.84]	(1484746849.6868s x0.00 from start)
      (enter) Call to alt_bn128_exp_by_neg_z     	[             ]	(1484746849.6868s x0.00 from start)
      (leave) Call to alt_bn128_exp_by_neg_z     	[0.0009s x3.99]	(1484746849.6877s x0.00 from start)
    (leave) Call to alt_bn128_final_exponentiation_last_chunk	[0.0029s x3.93]	(1484746849.6878s x0.00 from start)
  (leave) Call to alt_bn128_final_exponentiation	[0.0030s x3.91]	(1484746849.6879s x0.00 from start)
  (enter) Call to alt_bn128_ate_precompute_G2	[             ]	(1484746849.6879s x0.00 from start)
  (leave) Call to alt_bn128_ate_precompute_G2	[0.0007s x3.99]	(1484746849.6886s x0.00 from start)
  (enter) Call to alt_bn128_ate_precompute_G1	[             ]	(1484746849.6886s x0.00 from start)
  (leave) Call to alt_bn128_ate_precompute_G1	[0.0000s x3.27]	(1484746849.6886s x0.00 from start)
  (enter) Call to alt_bn128_ate_miller_loop  	[             ]	(1484746849.6886s x0.00 from start)
  (leave) Call to alt_bn128_ate_miller_loop  	[0.0017s x4.00]	(1484746849.6902s x0.00 from start)
  (enter) Call to alt_bn128_ate_miller_loop  	[             ]	(1484746849.6903s x0.00 from start)
  (leave) Call to alt_bn128_ate_miller_loop  	[0.0017s x2.92]	(1484746849.6919s x0.00 from start)
  (enter) Call to alt_bn128_final_exponentiation	[             ]	(1484746849.6919s x0.00 from start)
    (enter) Call to alt_bn128_final_exponentiation_first_chunk	[             ]	(1484746849.6920s x0.00 from start)
    (leave) Call to alt_bn128_final_exponentiation_first_chunk	[0.0001s x3.08]	(1484746849.6920s x0.00 from start)
    (enter) Call to alt_bn128_final_exponentiation_last_chunk	[             ]	(1484746849.6920s x0.00 from start)
      (enter) Call to alt_bn128_exp_by_neg_z     	[             ]	(1484746849.6920s x0.00 from start)
      (leave) Call to alt_bn128_exp_by_neg_z     	[0.0009s x3.97]	(1484746849.6929s x0.00 from start)
      (enter) Call to alt_bn128_exp_by_neg_z     	[             ]	(1484746849.6930s x0.00 from start)
      (leave) Call to alt_bn128_exp_by_neg_z     	[0.0009s x3.25]	(1484746849.6939s x0.00 from start)
      (enter) Call to alt_bn128_exp_by_neg_z     	[             ]	(1484746849.6939s x0.00 from start)
      (leave) Call to alt_bn128_exp_by_neg_z     	[0.0010s x4.00]	(1484746849.6949s x0.00 from start)
    (leave) Call to alt_bn128_final_exponentiation_last_chunk	[0.0030s x3.74]	(1484746849.6951s x0.00 from start)
  (leave) Call to alt_bn128_final_exponentiation	[0.0031s x3.71]	(1484746849.6951s x0.00 from start)
  (enter) Call to alt_bn128_ate_precompute_G1	[             ]	(1484746849.6951s x0.00 from start)
  (leave) Call to alt_bn128_ate_precompute_G1	[0.0000s x3.56]	(1484746849.6951s x0.00 from start)
  (enter) Call to alt_bn128_ate_precompute_G1	[             ]	(1484746849.6951s x0.00 from start)
  (leave) Call to alt_bn128_ate_precompute_G1	[0.0000s x3.33]	(1484746849.6951s x0.00 from start)
  (enter) Call to alt_bn128_ate_miller_loop  	[             ]	(1484746849.6952s x0.00 from start)
  (leave) Call to alt_bn128_ate_miller_loop  	[0.0017s x4.00]	(1484746849.6969s x0.00 from start)
  (enter) Call to alt_bn128_ate_miller_loop  	[             ]	(1484746849.6969s x0.00 from start)
  (leave) Call to alt_bn128_ate_miller_loop  	[0.0015s x3.30]	(1484746849.6984s x0.00 from start)
  (enter) Call to alt_bn128_final_exponentiation	[             ]	(1484746849.6984s x0.00 from start)
    (enter) Call to alt_bn128_final_exponentiation_first_chunk	[             ]	(1484746849.6984s x0.00 from start)
    (leave) Call to alt_bn128_final_exponentiation_first_chunk	[0.0001s x2.08]	(1484746849.6985s x0.00 from start)
    (enter) Call to alt_bn128_final_exponentiation_last_chunk	[             ]	(1484746849.6985s x0.00 from start)
      (enter) Call to alt_bn128_exp_by_neg_z     	[             ]	(1484746849.6985s x0.00 from start)
      (leave) Call to alt_bn128_exp_by_neg_z     	[0.0007s x2.00]	(1484746849.6992s x0.00 from start)
      (enter) Call to alt_bn128_exp_by_neg_z     	[             ]	(1484746849.6993s x0.00 from start)
      (leave) Call to alt_bn128_exp_by_neg_z     	[0.0007s x2.00]	(1484746849.7000s x0.00 from start)
      (enter) Call to alt_bn128_exp_by_neg_z     	[             ]	(1484746849.7000s x0.00 from start)
      (leave) Call to alt_bn128_exp_by_neg_z     	[0.0007s x1.75]	(1484746849.7007s x0.00 from start)
    (leave) Call to alt_bn128_final_exponentiation_last_chunk	[0.0023s x1.87]	(1484746849.7008s x0.00 from start)
  (leave) Call to alt_bn128_final_exponentiation	[0.0024s x1.87]	(1484746849.7008s x0.00 from start)
  (enter) Call to alt_bn128_ate_precompute_G1	[             ]	(1484746849.7008s x0.00 from start)
  (leave) Call to alt_bn128_ate_precompute_G1	[0.0000s x1.11]	(1484746849.7008s x0.00 from start)
  (enter) Call to alt_bn128_ate_precompute_G1	[             ]	(1484746849.7009s x0.00 from start)
  (leave) Call to alt_bn128_ate_precompute_G1	[0.0000s x1.11]	(1484746849.7009s x0.00 from start)
  (enter) Call to alt_bn128_ate_miller_loop  	[             ]	(1484746849.7009s x0.00 from start)
  (leave) Call to alt_bn128_ate_miller_loop  	[0.0013s x1.00]	(1484746849.7022s x0.00 from start)
  (enter) Call to alt_bn128_ate_double_miller_loop	[             ]	(1484746849.7022s x0.00 from start)
  (leave) Call to alt_bn128_ate_double_miller_loop	[0.0021s x1.00]	(1484746849.7043s x0.00 from start)
  (enter) Call to alt_bn128_final_exponentiation	[             ]	(1484746849.7043s x0.00 from start)
    (enter) Call to alt_bn128_final_exponentiation_first_chunk	[             ]	(1484746849.7043s x0.00 from start)
    (leave) Call to alt_bn128_final_exponentiation_first_chunk	[0.0001s x1.03]	(1484746849.7044s x0.00 from start)
    (enter) Call to alt_bn128_final_exponentiation_last_chunk	[             ]	(1484746849.7044s x0.00 from start)
      (enter) Call to alt_bn128_exp_by_neg_z     	[             ]	(1484746849.7044s x0.00 from start)
      (leave) Call to alt_bn128_exp_by_neg_z     	[0.0007s x1.00]	(1484746849.7051s x0.00 from start)
      (enter) Call to alt_bn128_exp_by_neg_z     	[             ]	(1484746849.7051s x0.00 from start)
      (leave) Call to alt_bn128_exp_by_neg_z     	[0.0007s x1.00]	(1484746849.7058s x0.00 from start)
      (enter) Call to alt_bn128_exp_by_neg_z     	[             ]	(1484746849.7058s x0.00 from start)
      (leave) Call to alt_bn128_exp_by_neg_z     	[0.0007s x1.00]	(1484746849.7065s x0.00 from start)
    (leave) Call to alt_bn128_final_exponentiation_last_chunk	[0.0023s x1.00]	(1484746849.7067s x0.00 from start)
  (leave) Call to alt_bn128_final_exponentiation	[0.0024s x1.00]	(1484746849.7067s x0.00 from start)
  (enter) Call to alt_bn128_ate_precompute_G1	[             ]	(1484746849.7067s x0.00 from start)
  (leave) Call to alt_bn128_ate_precompute_G1	[0.0000s x1.10]	(1484746849.7067s x0.00 from start)
  (enter) Call to alt_bn128_ate_precompute_G1	[             ]	(1484746849.7067s x0.00 from start)
  (leave) Call to alt_bn128_ate_precompute_G1	[0.0000s x1.08]	(1484746849.7067s x0.00 from start)
  (enter) Call to alt_bn128_ate_miller_loop  	[             ]	(1484746849.7067s x0.00 from start)
  (leave) Call to alt_bn128_ate_miller_loop  	[0.0013s x1.00]	(1484746849.7080s x0.00 from start)
  (enter) Call to alt_bn128_ate_double_miller_loop	[             ]	(1484746849.7081s x0.00 from start)
  (leave) Call to alt_bn128_ate_double_miller_loop	[0.0024s x1.00]	(1484746849.7105s x0.00 from start)
  (enter) Call to alt_bn128_final_exponentiation	[             ]	(1484746849.7105s x0.00 from start)
    (enter) Call to alt_bn128_final_exponentiation_first_chunk	[             ]	(1484746849.7106s x0.00 from start)
    (leave) Call to alt_bn128_final_exponentiation_first_chunk	[0.0001s x1.04]	(1484746849.7106s x0.00 from start)
    (enter) Call to alt_bn128_final_exponentiation_last_chunk	[             ]	(1484746849.7106s x0.00 from start)
      (enter) Call to alt_bn128_exp_by_neg_z     	[             ]	(1484746849.7107s x0.00 from start)
      (leave) Call to alt_bn128_exp_by_neg_z     	[0.0008s x1.01]	(1484746849.7114s x0.00 from start)
      (enter) Call to alt_bn128_exp_by_neg_z     	[             ]	(1484746849.7115s x0.00 from start)
      (leave) Call to alt_bn128_exp_by_neg_z     	[0.0008s x1.01]	(1484746849.7122s x0.00 from start)
      (enter) Call to alt_bn128_exp_by_neg_z     	[             ]	(1484746849.7123s x0.00 from start)
      (leave) Call to alt_bn128_exp_by_neg_z     	[0.0008s x1.01]	(1484746849.7130s x0.00 from start)
    (leave) Call to alt_bn128_final_exponentiation_last_chunk	[0.0025s x1.00]	(1484746849.7132s x0.00 from start)
  (leave) Call to alt_bn128_final_exponentiation	[0.0027s x1.00]	(1484746849.7132s x0.00 from start)
(leave) Call to r1cs_ppzksnark_online_verifier_strong_IC	[0.0331s x2.59]	(1484746849.7132s x0.00 from start)
(enter) Call to r1cs_ppzksnark_online_verifier_strong_IC	[             ]	(1484746849.7153s x0.00 from start)
  (enter) Call to alt_bn128_ate_precompute_G1	[             ]	(1484746849.7166s x0.00 from start)
  (leave) Call to alt_bn128_ate_precompute_G1	[0.0000s x3.33]	(1484746849.7167s x0.00 from start)
  (enter) Call to alt_bn128_ate_precompute_G1	[             ]	(1484746849.7167s x0.00 from start)
  (leave) Call to alt_bn128_ate_precompute_G1	[0.0000s x2.47]	(1484746849.7167s x0.00 from start)
  (enter) Call to alt_bn128_ate_miller_loop  	[             ]	(1484746849.7167s x0.00 from start)
  (leave) Call to alt_bn128_ate_miller_loop  	[0.0020s x3.55]	(1484746849.7187s x0.00 from start)
  (enter) Call to alt_bn128_ate_miller_loop  	[             ]	(1484746849.7188s x0.00 from start)
  (leave) Call to alt_bn128_ate_miller_loop  	[0.0018s x3.79]	(1484746849.7206s x0.00 from start)
  (enter) Call to alt_bn128_final_exponentiation	[             ]	(1484746849.7207s x0.00 from start)
    (enter) Call to alt_bn128_final_exponentiation_first_chunk	[             ]	(1484746849.7207s x0.00 from start)
    (leave) Call to alt_bn128_final_exponentiation_first_chunk	[0.0001s x3.82]	(1484746849.7208s x0.00 from start)
    (enter) Call to alt_bn128_final_exponentiation_last_chunk	[             ]	(1484746849.7208s x0.00 from start)
      (enter) Call to alt_bn128_exp_by_neg_z     	[             ]	(1484746849.7208s x0.00 from start)
      (leave) Call to alt_bn128_exp_by_neg_z     	[0.0009s x3.99]	(1484746849.7217s x0.00 from start)
      (enter) Call to alt_bn128_exp_by_neg_z     	[             ]	(1484746849.7218s x0.00 from start)
      (leave) Call to alt_bn128_exp_by_neg_z     	[0.0009s x3.98]	(1484746849.7227s x0.00 from start)
      (enter) Call to alt_bn128_exp_by_neg_z     	[             ]	(1484746849.7227s x0.00 from start)
      (leave) Call to alt_bn128_exp_by_neg_z     	[0.0009s x3.98]	(1484746849.7236s x0.00 from start)
    (leave) Call to alt_bn128_final_exponentiation_last_chunk	[0.0029s x3.96]	(1484746849.7237s x0.00 from start)
  (leave) Call to alt_bn128_final_exponentiation	[0.0030s x3.94]	(1484746849.7237s x0.00 from start)
  (enter) Call to alt_bn128_ate_precompute_G2	[             ]	(1484746849.7238s x0.00 from start)
  (leave) Call to alt_bn128_ate_precompute_G2	[0.0007s x3.98]	(1484746849.7245s x0.00 from start)
  (enter) Call to alt_bn128_ate_precompute_G1	[             ]	(1484746849.7245s x0.00 from start)
  (leave) Call to alt_bn128_ate_precompute_G1	[0.0000s x3.35]	(1484746849.7245s x0.00 from start)
  (enter) Call to alt_bn128_ate_miller_loop  	[             ]	(1484746849.7245s x0.00 from start)
  (leave) Call to alt_bn128_ate_miller_loop  	[0.0017s x3.79]	(1484746849.7262s x0.00 from start)
  (enter) Call to alt_bn128_ate_miller_loop  	[             ]	(1484746849.7262s x0.00 from start)
  (leave) Call to alt_bn128_ate_miller_loop  	[0.0017s x3.95]	(1484746849.7279s x0.00 from start)
  (enter) Call to alt_bn128_final_exponentiation	[             ]	(1484746849.7279s x0.00 from start)
    (enter) Call to alt_bn128_final_exponentiation_first_chunk	[             ]	(1484746849.7279s x0.00 from start)
    (leave) Call to alt_bn128_final_exponentiation_first_chunk	[0.0001s x3.85]	(1484746849.7280s x0.00 from start)
    (enter) Call to alt_bn128_final_exponentiation_last_chunk	[             ]	(1484746849.7280s x0.00 from start)
      (enter) Call to alt_bn128_exp_by_neg_z     	[             ]	(1484746849.7280s x0.00 from start)
      (leave) Call to alt_bn128_exp_by_neg_z     	[0.0009s x3.98]	(1484746849.7289s x0.00 from start)
      (enter) Call to alt_bn128_exp_by_neg_z     	[             ]	(1484746849.7290s x0.00 from start)
      (leave) Call to alt_bn128_exp_by_neg_z     	[0.0009s x3.98]	(1484746849.7298s x0.00 from start)
      (enter) Call to alt_bn128_exp_by_neg_z     	[             ]	(1484746849.7299s x0.00 from start)
      (leave) Call to alt_bn128_exp_by_neg_z     	[0.0009s x3.98]	(1484746849.7307s x0.00 from start)
    (leave) Call to alt_bn128_final_exponentiation_last_chunk	[0.0029s x3.96]	(1484746849.7309s x0.00 from start)
  (leave) Call to alt_bn128_final_exponentiation	[0.0030s x3.95]	(1484746849.7309s x0.00 from start)
  (enter) Call to alt_bn128_ate_precompute_G1	[             ]	(1484746849.7309s x0.00 from start)
  (leave) Call to alt_bn128_ate_precompute_G1	[0.0000s x3.28]	(1484746849.7310s x0.00 from start)
  (enter) Call to alt_bn128_ate_precompute_G1	[             ]	(1484746849.7310s x0.00 from start)
  (leave) Call to alt_bn128_ate_precompute_G1	[0.0000s x3.32]	(1484746849.7310s x0.00 from start)
  (enter) Call to alt_bn128_ate_miller_loop  	[             ]	(1484746849.7310s x0.00 from start)
  (leave) Call to alt_bn128_ate_miller_loop  	[0.0017s x3.99]	(1484746849.7327s x0.00 from start)
  (enter) Call to alt_bn128_ate_miller_loop  	[             ]	(1484746849.7327s x0.00 from start)
  (leave) Call to alt_bn128_ate_miller_loop  	[0.0017s x2.43]	(1484746849.7343s x0.00 from start)
  (enter) Call to alt_bn128_final_exponentiation	[             ]	(1484746849.7344s x0.00 from start)
    (enter) Call to alt_bn128_final_exponentiation_first_chunk	[             ]	(1484746849.7344s x0.00 from start)
    (leave) Call to alt_bn128_final_exponentiation_first_chunk	[0.0001s x2.05]	(1484746849.7344s x0.00 from start)
    (enter) Call to alt_bn128_final_exponentiation_last_chunk	[             ]	(1484746849.7344s x0.00 from start)
      (enter) Call to alt_bn128_exp_by_neg_z     	[             ]	(1484746849.7344s x0.00 from start)
      (leave) Call to alt_bn128_exp_by_neg_z     	[0.0008s x1.81]	(1484746849.7353s x0.00 from start)
      (enter) Call to alt_bn128_exp_by_neg_z     	[             ]	(1484746849.7353s x0.00 from start)
      (leave) Call to alt_bn128_exp_by_neg_z     	[0.0007s x1.00]	(1484746849.7360s x0.00 from start)
      (enter) Call to alt_bn128_exp_by_neg_z     	[             ]	(1484746849.7360s x0.00 from start)
      (leave) Call to alt_bn128_exp_by_neg_z     	[0.0007s x1.00]	(1484746849.7367s x0.00 from start)
    (leave) Call to alt_bn128_final_exponentiation_last_chunk	[0.0024s x1.29]	(1484746849.7368s x0.00 from start)
  (leave) Call to alt_bn128_final_exponentiation	[0.0025s x1.31]	(1484746849.7369s x0.00 from start)
  (enter) Call to alt_bn128_ate_precompute_G1	[             ]	(1484746849.7369s x0.00 from start)
  (leave) Call to alt_bn128_ate_precompute_G1	[0.0000s x1.13]	(1484746849.7369s x0.00 from start)
  (enter) Call to alt_bn128_ate_precompute_G1	[             ]	(1484746849.7369s x0.00 from start)
  (leave) Call to alt_bn128_ate_precompute_G1	[0.0000s x1.09]	(1484746849.7369s x0.00 from start)
  (enter) Call to alt_bn128_ate_miller_loop  	[             ]	(1484746849.7369s x0.00 from start)
  (leave) Call to alt_bn128_ate_miller_loop  	[0.0013s x1.00]	(1484746849.7382s x0.00 from start)
  (enter) Call to alt_bn128_ate_double_miller_loop	[             ]	(1484746849.7382s x0.00 from start)
  (leave) Call to alt_bn128_ate_double_miller_loop	[0.0021s x1.00]	(1484746849.7403s x0.00 from start)
  (enter) Call to alt_bn128_final_exponentiation	[             ]	(1484746849.7403s x0.00 from start)
    (enter) Call to alt_bn128_final_exponentiation_first_chunk	[             ]	(1484746849.7404s x0.00 from start)
    (leave) Call to alt_bn128_final_exponentiation_first_chunk	[0.0001s x1.02]	(1484746849.7404s x0.00 from start)
    (enter) Call to alt_bn128_final_exponentiation_last_chunk	[             ]	(1484746849.7404s x0.00 from start)
      (enter) Call to alt_bn128_exp_by_neg_z     	[             ]	(1484746849.7404s x0.00 from start)
      (leave) Call to alt_bn128_exp_by_neg_z     	[0.0007s x1.00]	(1484746849.7412s x0.00 from start)
      (enter) Call to alt_bn128_exp_by_neg_z     	[             ]	(1484746849.7412s x0.00 from start)
      (leave) Call to alt_bn128_exp_by_neg_z     	[0.0009s x1.00]	(1484746849.7421s x0.00 from start)
      (enter) Call to alt_bn128_exp_by_neg_z     	[             ]	(1484746849.7421s x0.00 from start)
      (leave) Call to alt_bn128_exp_by_neg_z     	[0.0008s x0.98]	(1484746849.7429s x0.00 from start)
    (leave) Call to alt_bn128_final_exponentiation_last_chunk	[0.0027s x1.00]	(1484746849.7431s x0.00 from start)
  (leave) Call to alt_bn128_final_exponentiation	[0.0027s x1.00]	(1484746849.7431s x0.00 from start)
  (enter) Call to alt_bn128_ate_precompute_G1	[             ]	(1484746849.7431s x0.00 from start)
  (leave) Call to alt_bn128_ate_precompute_G1	[0.0000s x1.10]	(1484746849.7431s x0.00 from start)
  (enter) Call to alt_bn128_ate_precompute_G1	[             ]	(1484746849.7431s x0.00 from start)
  (leave) Call to alt_bn128_ate_precompute_G1	[0.0000s x1.08]	(1484746849.7431s x0.00 from start)
  (enter) Call to alt_bn128_ate_miller_loop  	[             ]	(1484746849.7432s x0.00 from start)
  (leave) Call to alt_bn128_ate_miller_loop  	[0.0016s x1.00]	(1484746849.7447s x0.00 from start)
  (enter) Call to alt_bn128_ate_double_miller_loop	[             ]	(1484746849.7448s x0.00 from start)
  (leave) Call to alt_bn128_ate_double_miller_loop	[0.0023s x1.00]	(1484746849.7471s x0.00 from start)
  (enter) Call to alt_bn128_final_exponentiation	[             ]	(1484746849.7471s x0.00 from start)
    (enter) Call to alt_bn128_final_exponentiation_first_chunk	[             ]	(1484746849.7471s x0.00 from start)
    (leave) Call to alt_bn128_final_exponentiation_first_chunk	[0.0001s x1.03]	(1484746849.7472s x0.00 from start)
    (enter) Call to alt_bn128_final_exponentiation_last_chunk	[             ]	(1484746849.7472s x0.00 from start)
      (enter) Call to alt_bn128_exp_by_neg_z     	[             ]	(1484746849.7472s x0.00 from start)
      (leave) Call to alt_bn128_exp_by_neg_z     	[0.0007s x1.01]	(1484746849.7480s x0.00 from start)
      (enter) Call to alt_bn128_exp_by_neg_z     	[             ]	(1484746849.7480s x0.00 from start)
      (leave) Call to alt_bn128_exp_by_neg_z     	[0.0007s x1.00]	(1484746849.7488s x0.00 from start)
      (enter) Call to alt_bn128_exp_by_neg_z     	[             ]	(1484746849.7488s x0.00 from start)
      (leave) Call to alt_bn128_exp_by_neg_z     	[0.0007s x1.00]	(1484746849.7495s x0.00 from start)
    (leave) Call to alt_bn128_final_exponentiation_last_chunk	[0.0024s x1.00]	(1484746849.7496s x0.00 from start)
  (leave) Call to alt_bn128_final_exponentiation	[0.0025s x1.00]	(1484746849.7496s x0.00 from start)
(leave) Call to r1cs_ppzksnark_online_verifier_strong_IC	[0.0344s x2.53]	(1484746849.7496s x0.00 from start)
(enter) Call to r1cs_constraint_system::swap_AB_if_beneficial	[             ]	(1484746865.5655s x0.00 from start)
  (enter) Estimate densities                 	[             ]	(1484746865.5656s x0.00 from start)
    * Non-zero A-count (estimate): 1141154
    * Non-zero B-count (estimate): 1379738
  (leave) Estimate densities                 	[0.5815s x1.00]	(1484746866.1471s x0.00 from start)
  (enter) Perform the swap                   	[             ]	(1484746866.1471s x0.00 from start)
  (leave) Perform the swap                   	[0.0178s x1.00]	(1484746866.1649s x0.00 from start)
(leave) Call to r1cs_constraint_system::swap_AB_if_beneficial	[0.5994s x1.00]	(1484746866.1650s x0.00 from start)
(enter) Call to r1cs_ppzksnark_prover      	[             ]	(1484746866.1650s x0.00 from start)
  (enter) Compute the polynomial H           	[             ]	(1484746866.1651s x0.00 from start)
    (enter) Call to r1cs_to_qap_witness_map    	[             ]	(1484746866.1651s x0.00 from start)
      * Selected domain: basic_radix2
      (enter) Compute evaluation of polynomials A, B on set S	[             ]	(1484746868.1642s x0.00 from start)
      (leave) Compute evaluation of polynomials A, B on set S	[1.3218s x1.00]	(1484746869.4860s x0.00 from start)
      (enter) Compute coefficients of polynomial A	[             ]	(1484746869.4860s x0.00 from start)
        (enter) Execute inverse FFT                	[             ]	(1484746869.4860s x0.00 from start)
          (enter) Shuffle inputs                     	[             ]	(1484746869.4861s x0.00 from start)
          (leave) Shuffle inputs                     	[0.5846s x3.66]	(1484746870.0706s x0.00 from start)
          (enter) Execute sub-FFTs                   	[             ]	(1484746870.0707s x0.00 from start)
          (leave) Execute sub-FFTs                   	[1.5623s x3.91]	(1484746871.6329s x0.00 from start)
          (enter) Re-shuffle outputs                 	[             ]	(1484746871.6331s x0.00 from start)
          (leave) Re-shuffle outputs                 	[0.0167s x3.66]	(1484746871.6498s x0.00 from start)
        (leave) Execute inverse FFT                	[2.2993s x3.69]	(1484746871.7853s x0.00 from start)
      (leave) Compute coefficients of polynomial A	[2.2993s x3.69]	(1484746871.7854s x0.00 from start)
      (enter) Compute coefficients of polynomial B	[             ]	(1484746871.7854s x0.00 from start)
        (enter) Execute inverse FFT                	[             ]	(1484746871.7854s x0.00 from start)
          (enter) Shuffle inputs                     	[             ]	(1484746871.7854s x0.00 from start)
          (leave) Shuffle inputs                     	[0.5979s x3.68]	(1484746872.3833s x0.00 from start)
          (enter) Execute sub-FFTs                   	[             ]	(1484746872.3834s x0.00 from start)
          (leave) Execute sub-FFTs                   	[1.6037s x3.93]	(1484746873.9871s x0.00 from start)
          (enter) Re-shuffle outputs                 	[             ]	(1484746873.9871s x0.00 from start)
          (leave) Re-shuffle outputs                 	[0.0126s x3.70]	(1484746873.9997s x0.00 from start)
        (leave) Execute inverse FFT                	[2.3206s x3.75]	(1484746874.1060s x0.00 from start)
      (leave) Compute coefficients of polynomial B	[2.3207s x3.75]	(1484746874.1061s x0.00 from start)
      (enter) Compute ZK-patch                   	[             ]	(1484746874.1061s x0.00 from start)
      (leave) Compute ZK-patch                   	[0.2252s x2.86]	(1484746874.3313s x0.00 from start)
      (enter) Compute evaluation of polynomial A on set T	[             ]	(1484746874.3314s x0.00 from start)
        (enter) Execute coset FFT                  	[             ]	(1484746874.3314s x0.00 from start)
          (enter) Execute FFT                        	[             ]	(1484746874.5621s x0.00 from start)
            (enter) Shuffle inputs                     	[             ]	(1484746874.5621s x0.00 from start)
            (leave) Shuffle inputs                     	[0.6820s x3.37]	(1484746875.2442s x0.00 from start)
            (enter) Execute sub-FFTs                   	[             ]	(1484746875.2443s x0.00 from start)
            (leave) Execute sub-FFTs                   	[2.0957s x2.90]	(1484746877.3400s x0.00 from start)
            (enter) Re-shuffle outputs                 	[             ]	(1484746877.3400s x0.00 from start)
            (leave) Re-shuffle outputs                 	[0.0158s x3.79]	(1484746877.3559s x0.00 from start)
          (leave) Execute FFT                        	[2.8009s x3.03]	(1484746877.3630s x0.00 from start)
        (leave) Execute coset FFT                  	[3.0317s x2.88]	(1484746877.3631s x0.00 from start)
      (leave) Compute evaluation of polynomial A on set T	[3.0317s x2.88]	(1484746877.3631s x0.00 from start)
      (enter) Compute evaluation of polynomial B on set T	[             ]	(1484746877.3631s x0.00 from start)
        (enter) Execute coset FFT                  	[             ]	(1484746877.3631s x0.00 from start)
          (enter) Execute FFT                        	[             ]	(1484746877.5833s x0.00 from start)
            (enter) Shuffle inputs                     	[             ]	(1484746877.5833s x0.00 from start)
            (leave) Shuffle inputs                     	[0.6486s x3.68]	(1484746878.2319s x0.00 from start)
            (enter) Execute sub-FFTs                   	[             ]	(1484746878.2319s x0.00 from start)
            (leave) Execute sub-FFTs                   	[1.6682s x3.90]	(1484746879.9001s x0.00 from start)
            (enter) Re-shuffle outputs                 	[             ]	(1484746879.9002s x0.00 from start)
            (leave) Re-shuffle outputs                 	[0.0360s x2.74]	(1484746879.9363s x0.00 from start)
          (leave) Execute FFT                        	[2.3673s x3.81]	(1484746879.9506s x0.00 from start)
        (leave) Execute coset FFT                  	[2.5876s x3.58]	(1484746879.9507s x0.00 from start)
      (leave) Compute evaluation of polynomial B on set T	[2.5876s x3.58]	(1484746879.9507s x0.00 from start)
      (enter) Compute evaluation of polynomial H on set T	[             ]	(1484746879.9507s x0.00 from start)
        (enter) Compute evaluation of polynomial C on set S	[             ]	(1484746880.0445s x0.00 from start)
        (leave) Compute evaluation of polynomial C on set S	[0.7083s x1.02]	(1484746880.7528s x0.00 from start)
        (enter) Compute coefficients of polynomial C	[             ]	(1484746880.7528s x0.00 from start)
          (enter) Execute inverse FFT                	[             ]	(1484746880.7528s x0.00 from start)
            (enter) Shuffle inputs                     	[             ]	(1484746880.7528s x0.00 from start)
            (leave) Shuffle inputs                     	[0.6362s x3.52]	(1484746881.3890s x0.00 from start)
            (enter) Execute sub-FFTs                   	[             ]	(1484746881.3891s x0.00 from start)
            (leave) Execute sub-FFTs                   	[1.8210s x3.46]	(1484746883.2101s x0.00 from start)
            (enter) Re-shuffle outputs                 	[             ]	(1484746883.2102s x0.00 from start)
            (leave) Re-shuffle outputs                 	[0.0218s x3.43]	(1484746883.2319s x0.00 from start)
          (leave) Execute inverse FFT                	[2.5939s x3.38]	(1484746883.3467s x0.00 from start)
        (leave) Compute coefficients of polynomial C	[2.5940s x3.38]	(1484746883.3468s x0.00 from start)
        (enter) Compute evaluation of polynomial C on set T	[             ]	(1484746883.3468s x0.00 from start)
          (enter) Execute coset FFT                  	[             ]	(1484746883.3468s x0.00 from start)
            (enter) Execute FFT                        	[             ]	(1484746883.5678s x0.00 from start)
              (enter) Shuffle inputs                     	[             ]	(1484746883.5678s x0.00 from start)
              (leave) Shuffle inputs                     	[0.6987s x3.37]	(1484746884.2664s x0.00 from start)
              (enter) Execute sub-FFTs                   	[             ]	(1484746884.2707s x0.00 from start)
              (leave) Execute sub-FFTs                   	[2.0173s x3.14]	(1484746886.2880s x0.00 from start)
              (enter) Re-shuffle outputs                 	[             ]	(1484746886.2882s x0.00 from start)
              (leave) Re-shuffle outputs                 	[0.0184s x3.51]	(1484746886.3066s x0.00 from start)
            (leave) Execute FFT                        	[2.7501s x3.20]	(1484746886.3178s x0.00 from start)
          (leave) Execute coset FFT                  	[2.9712s x3.04]	(1484746886.3180s x0.00 from start)
        (leave) Compute evaluation of polynomial C on set T	[2.9713s x3.04]	(1484746886.3181s x0.00 from start)
        (enter) Divide by Z on set T               	[             ]	(1484746886.3463s x0.00 from start)
        (leave) Divide by Z on set T               	[0.1203s x1.37]	(1484746886.4666s x0.00 from start)
      (leave) Compute evaluation of polynomial H on set T	[6.5159s x2.93]	(1484746886.4667s x0.00 from start)
      (enter) Compute coefficients of polynomial H	[             ]	(1484746886.4667s x0.00 from start)
        (enter) Execute inverse coset IFFT         	[             ]	(1484746886.4667s x0.00 from start)
          (enter) Execute inverse FFT                	[             ]	(1484746886.4667s x0.00 from start)
            (enter) Shuffle inputs                     	[             ]	(1484746886.4667s x0.00 from start)
            (leave) Shuffle inputs                     	[0.9484s x2.48]	(1484746887.4151s x0.00 from start)
            (enter) Execute sub-FFTs                   	[             ]	(1484746887.4151s x0.00 from start)
            (leave) Execute sub-FFTs                   	[2.2314s x2.83]	(1484746889.6465s x0.00 from start)
            (enter) Re-shuffle outputs                 	[             ]	(1484746889.6466s x0.00 from start)
            (leave) Re-shuffle outputs                 	[0.0243s x2.46]	(1484746889.6709s x0.00 from start)
          (leave) Execute inverse FFT                	[3.3443s x2.67]	(1484746889.8109s x0.00 from start)
        (leave) Execute inverse coset IFFT         	[3.6021s x2.55]	(1484746890.0687s x0.00 from start)
      (leave) Compute coefficients of polynomial H	[3.6021s x2.55]	(1484746890.0688s x0.00 from start)
      (enter) Compute sum of H and ZK-patch      	[             ]	(1484746890.0688s x0.00 from start)
      (leave) Compute sum of H and ZK-patch      	[0.0258s x3.38]	(1484746890.0946s x0.00 from start)
    (leave) Call to r1cs_to_qap_witness_map    	[23.9296s x2.82]	(1484746890.0947s x0.00 from start)
  (leave) Compute the polynomial H           	[24.0241s x2.82]	(1484746890.1892s x0.00 from start)
  (enter) Compute the proof                  	[             ]	(1484746890.1937s x0.00 from start)
    (enter) Compute answer to A-query          	[             ]	(1484746890.1938s x0.00 from start)
    (enter) Process scalar vector              	[             ]	(1484746890.1938s x0.00 from start)
    (leave) Process scalar vector              	[1.9429s x1.00]	(1484746892.1367s x0.00 from start)
    (leave) Compute answer to A-query          	[2.2334s x1.19]	(1484746892.4271s x0.00 from start)
    (enter) Compute answer to B-query          	[             ]	(1484746892.4272s x0.00 from start)
    (enter) Process scalar vector              	[             ]	(1484746892.4272s x0.00 from start)
    (leave) Process scalar vector              	[4.4736s x1.00]	(1484746896.9008s x0.00 from start)
    (leave) Compute answer to B-query          	[4.4736s x1.00]	(1484746896.9008s x0.00 from start)
    (enter) Compute answer to C-query          	[             ]	(1484746896.9008s x0.00 from start)
    (enter) Process scalar vector              	[             ]	(1484746896.9008s x0.00 from start)
    (leave) Process scalar vector              	[2.2602s x1.00]	(1484746899.1611s x0.00 from start)
    (leave) Compute answer to C-query          	[2.5599s x1.28]	(1484746899.4607s x0.00 from start)
    (enter) Compute answer to H-query          	[             ]	(1484746899.4609s x0.00 from start)
    (leave) Compute answer to H-query          	[30.5179s x3.68]	(1484746929.9788s x0.00 from start)
    (enter) Compute answer to K-query          	[             ]	(1484746929.9788s x0.00 from start)
    (enter) Process scalar vector              	[             ]	(1484746929.9788s x0.00 from start)
    (leave) Process scalar vector              	[1.1431s x1.04]	(1484746931.1219s x0.00 from start)
    (leave) Compute answer to K-query          	[1.2872s x1.35]	(1484746931.2660s x0.00 from start)
  (leave) Compute the proof                  	[41.0723s x3.03]	(1484746931.2660s x0.00 from start)
(leave) Call to r1cs_ppzksnark_prover      	[65.1010s x2.95]	(1484746931.2660s x0.00 from start)
(enter) Call to r1cs_ppzksnark_online_verifier_strong_IC	[             ]	(1484746932.6883s x0.00 from start)
  (enter) Call to alt_bn128_ate_precompute_G1	[             ]	(1484746932.6985s x0.00 from start)
  (leave) Call to alt_bn128_ate_precompute_G1	[0.0000s x3.07]	(1484746932.6986s x0.00 from start)
  (enter) Call to alt_bn128_ate_precompute_G1	[             ]	(1484746932.6986s x0.00 from start)
  (leave) Call to alt_bn128_ate_precompute_G1	[0.0000s x3.03]	(1484746932.6986s x0.00 from start)
  (enter) Call to alt_bn128_ate_miller_loop  	[             ]	(1484746932.6986s x0.00 from start)
  (leave) Call to alt_bn128_ate_miller_loop  	[0.0017s x3.55]	(1484746932.7003s x0.00 from start)
  (enter) Call to alt_bn128_ate_miller_loop  	[             ]	(1484746932.7003s x0.00 from start)
  (leave) Call to alt_bn128_ate_miller_loop  	[0.0022s x3.49]	(1484746932.7026s x0.00 from start)
  (enter) Call to alt_bn128_final_exponentiation	[             ]	(1484746932.7026s x0.00 from start)
    (enter) Call to alt_bn128_final_exponentiation_first_chunk	[             ]	(1484746932.7026s x0.00 from start)
    (leave) Call to alt_bn128_final_exponentiation_first_chunk	[0.0001s x3.94]	(1484746932.7027s x0.00 from start)
    (enter) Call to alt_bn128_final_exponentiation_last_chunk	[             ]	(1484746932.7027s x0.00 from start)
      (enter) Call to alt_bn128_exp_by_neg_z     	[             ]	(1484746932.7027s x0.00 from start)
      (leave) Call to alt_bn128_exp_by_neg_z     	[0.0009s x3.99]	(1484746932.7036s x0.00 from start)
      (enter) Call to alt_bn128_exp_by_neg_z     	[             ]	(1484746932.7037s x0.00 from start)
      (leave) Call to alt_bn128_exp_by_neg_z     	[0.0009s x3.90]	(1484746932.7046s x0.00 from start)
      (enter) Call to alt_bn128_exp_by_neg_z     	[             ]	(1484746932.7046s x0.00 from start)
      (leave) Call to alt_bn128_exp_by_neg_z     	[0.0009s x3.21]	(1484746932.7055s x0.00 from start)
    (leave) Call to alt_bn128_final_exponentiation_last_chunk	[0.0030s x3.65]	(1484746932.7057s x0.00 from start)
  (leave) Call to alt_bn128_final_exponentiation	[0.0031s x3.64]	(1484746932.7058s x0.00 from start)
  (enter) Call to alt_bn128_ate_precompute_G2	[             ]	(1484746932.7058s x0.00 from start)
  (leave) Call to alt_bn128_ate_precompute_G2	[0.0010s x3.83]	(1484746932.7068s x0.00 from start)
  (enter) Call to alt_bn128_ate_precompute_G1	[             ]	(1484746932.7068s x0.00 from start)
  (leave) Call to alt_bn128_ate_precompute_G1	[0.0000s x3.33]	(1484746932.7069s x0.00 from start)
  (enter) Call to alt_bn128_ate_miller_loop  	[             ]	(1484746932.7069s x0.00 from start)
  (leave) Call to alt_bn128_ate_miller_loop  	[0.0017s x3.98]	(1484746932.7086s x0.00 from start)
  (enter) Call to alt_bn128_ate_miller_loop  	[             ]	(1484746932.7086s x0.00 from start)
  (leave) Call to alt_bn128_ate_miller_loop  	[0.0017s x3.28]	(1484746932.7104s x0.00 from start)
  (enter) Call to alt_bn128_final_exponentiation	[             ]	(1484746932.7104s x0.00 from start)
    (enter) Call to alt_bn128_final_exponentiation_first_chunk	[             ]	(1484746932.7104s x0.00 from start)
    (leave) Call to alt_bn128_final_exponentiation_first_chunk	[0.0001s x3.91]	(1484746932.7105s x0.00 from start)
    (enter) Call to alt_bn128_final_exponentiation_last_chunk	[             ]	(1484746932.7105s x0.00 from start)
      (enter) Call to alt_bn128_exp_by_neg_z     	[             ]	(1484746932.7105s x0.00 from start)
      (leave) Call to alt_bn128_exp_by_neg_z     	[0.0009s x3.98]	(1484746932.7114s x0.00 from start)
      (enter) Call to alt_bn128_exp_by_neg_z     	[             ]	(1484746932.7115s x0.00 from start)
      (leave) Call to alt_bn128_exp_by_neg_z     	[0.0009s x3.99]	(1484746932.7124s x0.00 from start)
      (enter) Call to alt_bn128_exp_by_neg_z     	[             ]	(1484746932.7124s x0.00 from start)
      (leave) Call to alt_bn128_exp_by_neg_z     	[0.0009s x3.98]	(1484746932.7133s x0.00 from start)
    (leave) Call to alt_bn128_final_exponentiation_last_chunk	[0.0029s x3.97]	(1484746932.7134s x0.00 from start)
  (leave) Call to alt_bn128_final_exponentiation	[0.0030s x3.95]	(1484746932.7134s x0.00 from start)
  (enter) Call to alt_bn128_ate_precompute_G1	[             ]	(1484746932.7135s x0.00 from start)
  (leave) Call to alt_bn128_ate_precompute_G1	[0.0000s x3.25]	(1484746932.7135s x0.00 from start)
  (enter) Call to alt_bn128_ate_precompute_G1	[             ]	(1484746932.7135s x0.00 from start)
  (leave) Call to alt_bn128_ate_precompute_G1	[0.0000s x3.28]	(1484746932.7135s x0.00 from start)
  (enter) Call to alt_bn128_ate_miller_loop  	[             ]	(1484746932.7135s x0.00 from start)
  (leave) Call to alt_bn128_ate_miller_loop  	[0.0017s x2.53]	(1484746932.7152s x0.00 from start)
  (enter) Call to alt_bn128_ate_miller_loop  	[             ]	(1484746932.7152s x0.00 from start)
  (leave) Call to alt_bn128_ate_miller_loop  	[0.0018s x2.30]	(1484746932.7170s x0.00 from start)
  (enter) Call to alt_bn128_final_exponentiation	[             ]	(1484746932.7170s x0.00 from start)
    (enter) Call to alt_bn128_final_exponentiation_first_chunk	[             ]	(1484746932.7170s x0.00 from start)
    (leave) Call to alt_bn128_final_exponentiation_first_chunk	[0.0001s x3.10]	(1484746932.7171s x0.00 from start)
    (enter) Call to alt_bn128_final_exponentiation_last_chunk	[             ]	(1484746932.7171s x0.00 from start)
      (enter) Call to alt_bn128_exp_by_neg_z     	[             ]	(1484746932.7171s x0.00 from start)
      (leave) Call to alt_bn128_exp_by_neg_z     	[0.0012s x2.67]	(1484746932.7184s x0.00 from start)
      (enter) Call to alt_bn128_exp_by_neg_z     	[             ]	(1484746932.7186s x0.00 from start)
      (leave) Call to alt_bn128_exp_by_neg_z     	[0.0013s x2.01]	(1484746932.7199s x0.00 from start)
      (enter) Call to alt_bn128_exp_by_neg_z     	[             ]	(1484746932.7199s x0.00 from start)
      (leave) Call to alt_bn128_exp_by_neg_z     	[0.0013s x2.02]	(1484746932.7212s x0.00 from start)
    (leave) Call to alt_bn128_final_exponentiation_last_chunk	[0.0044s x2.18]	(1484746932.7215s x0.00 from start)
  (leave) Call to alt_bn128_final_exponentiation	[0.0045s x2.18]	(1484746932.7216s x0.00 from start)
  (enter) Call to alt_bn128_ate_precompute_G1	[             ]	(1484746932.7216s x0.00 from start)
  (leave) Call to alt_bn128_ate_precompute_G1	[0.0000s x1.05]	(1484746932.7216s x0.00 from start)
  (enter) Call to alt_bn128_ate_precompute_G1	[             ]	(1484746932.7216s x0.00 from start)
  (leave) Call to alt_bn128_ate_precompute_G1	[0.0000s x1.10]	(1484746932.7216s x0.00 from start)
  (enter) Call to alt_bn128_ate_miller_loop  	[             ]	(1484746932.7216s x0.00 from start)
  (leave) Call to alt_bn128_ate_miller_loop  	[0.0015s x1.01]	(1484746932.7231s x0.00 from start)
  (enter) Call to alt_bn128_ate_double_miller_loop	[             ]	(1484746932.7232s x0.00 from start)
  (leave) Call to alt_bn128_ate_double_miller_loop	[0.0029s x1.00]	(1484746932.7261s x0.00 from start)
  (enter) Call to alt_bn128_final_exponentiation	[             ]	(1484746932.7261s x0.00 from start)
    (enter) Call to alt_bn128_final_exponentiation_first_chunk	[             ]	(1484746932.7262s x0.00 from start)
    (leave) Call to alt_bn128_final_exponentiation_first_chunk	[0.0001s x1.07]	(1484746932.7262s x0.00 from start)
    (enter) Call to alt_bn128_final_exponentiation_last_chunk	[             ]	(1484746932.7263s x0.00 from start)
      (enter) Call to alt_bn128_exp_by_neg_z     	[             ]	(1484746932.7263s x0.00 from start)
      (leave) Call to alt_bn128_exp_by_neg_z     	[0.0008s x1.00]	(1484746932.7271s x0.00 from start)
      (enter) Call to alt_bn128_exp_by_neg_z     	[             ]	(1484746932.7271s x0.00 from start)
      (leave) Call to alt_bn128_exp_by_neg_z     	[0.0007s x1.00]	(1484746932.7278s x0.00 from start)
      (enter) Call to alt_bn128_exp_by_neg_z     	[             ]	(1484746932.7278s x0.00 from start)
      (leave) Call to alt_bn128_exp_by_neg_z     	[0.0007s x1.00]	(1484746932.7285s x0.00 from start)
    (leave) Call to alt_bn128_final_exponentiation_last_chunk	[0.0024s x1.00]	(1484746932.7286s x0.00 from start)
  (leave) Call to alt_bn128_final_exponentiation	[0.0025s x1.00]	(1484746932.7286s x0.00 from start)
(leave) Call to r1cs_ppzksnark_online_verifier_strong_IC	[0.0404s x2.75]	(1484746932.7287s x0.00 from start)
=================================================================
==32531==ERROR: AddressSanitizer: heap-use-after-free on address 0x61c000dc20b0 at pc 0x56340a1d8894 bp 0x7ffdd74c1f10 sp 0x7ffdd74c1f00
READ of size 32 at 0x61c000dc20b0 thread T0
    #0 0x56340a1d8893 in transaction_tests::test_simple_joinsplit_invalidity::test_method() test/transaction_tests.cpp:481
    #1 0x56340a1d9c9c in test_simple_joinsplit_invalidity_invoker test/transaction_tests.cpp:378
    #2 0x563409fa2eb4 in boost::detail::function::void_function_invoker0<void (*)(), void>::invoke(boost::detail::function::function_buffer&) /home/str4d/dev/zcash/zcash/depends/x86_64-unknown-linux-gnu/share/../include/boost/function/function_template.hpp:118
    #3 0x56340a5b84fb in boost::detail::function::function_obj_invoker0<boost::detail::forward, int>::invoke(boost::detail::function::function_buffer&) (/home/str4d/dev/zcash/zcash/src/test/test_bitcoin+0x8044fb)
    #4 0x56340a5b78ec in boost::execution_monitor::catch_signals(boost::function<int ()> const&) (/home/str4d/dev/zcash/zcash/src/test/test_bitcoin+0x8038ec)
    #5 0x56340a5b79f7 in boost::execution_monitor::execute(boost::function<int ()> const&) (/home/str4d/dev/zcash/zcash/src/test/test_bitcoin+0x8039f7)
    #6 0x56340a5b81a5 in boost::execution_monitor::vexecute(boost::function<void ()> const&) (/home/str4d/dev/zcash/zcash/src/test/test_bitcoin+0x8041a5)
    #7 0x56340a57e030 in boost::unit_test::unit_test_monitor_t::execute_and_translate(boost::function<void ()> const&, unsigned int) (/home/str4d/dev/zcash/zcash/src/test/test_bitcoin+0x7ca030)
    #8 0x56340a55c185 in boost::unit_test::framework::state::execute_test_tree(unsigned long, unsigned int, boost::unit_test::framework::state::random_generator_helper const*) (/home/str4d/dev/zcash/zcash/src/test/test_bitcoin+0x7a8185)
    #9 0x56340a55c419 in boost::unit_test::framework::state::execute_test_tree(unsigned long, unsigned int, boost::unit_test::framework::state::random_generator_helper const*) (/home/str4d/dev/zcash/zcash/src/test/test_bitcoin+0x7a8419)
    #10 0x56340a554f51 in boost::unit_test::framework::run(unsigned long, bool) (/home/str4d/dev/zcash/zcash/src/test/test_bitcoin+0x7a0f51)
    #11 0x56340a57c36e in boost::unit_test::unit_test_main(boost::unit_test::test_suite* (*)(int, char**), int, char**) (/home/str4d/dev/zcash/zcash/src/test/test_bitcoin+0x7c836e)
    #12 0x7ffae8a8982f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #13 0x563409ebc188 in _start (/home/str4d/dev/zcash/zcash/src/test/test_bitcoin+0x108188)

0x61c000dc20b0 is located 48 bytes inside of 1832-byte region [0x61c000dc2080,0x61c000dc27a8)
freed by thread T0 here:
    #0 0x563409f3888a in operator delete(void*) (/home/str4d/dev/zcash/zcash/src/test/test_bitcoin+0x18488a)
    #1 0x56340a1ee468 in __gnu_cxx::new_allocator<JSDescription>::deallocate(JSDescription*, unsigned long) /usr/include/c++/5/ext/new_allocator.h:110
    #2 0x56340a1ee468 in std::allocator_traits<std::allocator<JSDescription> >::deallocate(std::allocator<JSDescription>&, JSDescription*, unsigned long) /usr/include/c++/5/bits/alloc_traits.h:517
    #3 0x56340a1ee468 in std::_Vector_base<JSDescription, std::allocator<JSDescription> >::_M_deallocate(JSDescription*, unsigned long) /usr/include/c++/5/bits/stl_vector.h:178
    #4 0x56340a1ee468 in void std::vector<JSDescription, std::allocator<JSDescription> >::_M_emplace_back_aux<JSDescription>(JSDescription&&) /usr/include/c++/5/bits/vector.tcc:438

previously allocated by thread T0 here:
    #0 0x563409f38292 in operator new(unsigned long) (/home/str4d/dev/zcash/zcash/src/test/test_bitcoin+0x184292)
    #1 0x56340a1ee259 in __gnu_cxx::new_allocator<JSDescription>::allocate(unsigned long, void const*) /usr/include/c++/5/ext/new_allocator.h:104
    #2 0x56340a1ee259 in std::allocator_traits<std::allocator<JSDescription> >::allocate(std::allocator<JSDescription>&, unsigned long) /usr/include/c++/5/bits/alloc_traits.h:491
    #3 0x56340a1ee259 in std::_Vector_base<JSDescription, std::allocator<JSDescription> >::_M_allocate(unsigned long) /usr/include/c++/5/bits/stl_vector.h:170
    #4 0x56340a1ee259 in void std::vector<JSDescription, std::allocator<JSDescription> >::_M_emplace_back_aux<JSDescription>(JSDescription&&) /usr/include/c++/5/bits/vector.tcc:412

SUMMARY: AddressSanitizer: heap-use-after-free test/transaction_tests.cpp:481 transaction_tests::test_simple_joinsplit_invalidity::test_method()
Shadow bytes around the buggy address:
  0x0c38801b03c0: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c38801b03d0: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c38801b03e0: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c38801b03f0: fd fd fd fd fd fa fa fa fa fa fa fa fa fa fa fa
  0x0c38801b0400: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x0c38801b0410: fd fd fd fd fd fd[fd]fd fd fd fd fd fd fd fd fd
  0x0c38801b0420: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c38801b0430: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c38801b0440: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c38801b0450: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c38801b0460: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
==32531==ABORTING
```

### PR DESCRIPTION
**Pull request by ebfull**
Fixes #2026

### CODE REVIEW

**Comment by bitcartel** [comment]
@ebfull How does this fix the issue?  Is the problem that the push_back() is causing the vector to reallocate memory since > capacity, so the existing reference to JSDesc at position 0 is now invalid, which is why you get it again?

**Comment by ebfull** [comment]
@bitcartel yep

**Comment by bitcartel** [comment]
utACK

File: src/test/transaction_tests.cpp [hunk 1]
```diff
@@ -475,6 +475,7 @@ BOOST_AUTO_TEST_CASE(test_simple_joinsplit_invalidity)
         jsdesc->nullifiers[1] = GetRandHash();
 
         newTx.vjoinsplit.push_back(JSDescription());
+        jsdesc = &newTx.vjoinsplit[0];
```
Comment (str4d) [inline src/test/transaction_tests.cpp]: Non-blocking: Could maybe use a comment pointing out why this is necessary, although someone can always look at `git blame` to figure it out if they can't see it immediately.

Comment (bitcartel) [inline src/test/transaction_tests.cpp]: Done

**Comment by bitcartel** [comment]
@zkbot r+
