### PR TITLE
Ensure that the "future timestamp" rule is correctly applied by block template construction

### LINKED ISSUE #6960: Block template construction fails to properly clamp the block time to satisfy the "future timestamp" rule
From protocol spec [§ 7.6 Block Header Encoding and Consensus](https://zips.z.cash/protocol/protocol.pdf#blockheader):

> For each block at block height 2 or greater on Mainnet, or block height 653606 or greater on Testnet, `nTime`
**MUST** be less than or equal to the median-time-past of that block plus 90 · 60 seconds.

This rule is not correctly applied by zcashd's block template construction.

If the median-time-past is more than 90 minutes ago, then a new block with `nTime` set to the current time would violate the rule. At `miner.cpp` lines 74-76 in `UpdateTime`: https://github.com/zcash/zcash/blob/1c0c425fdea00d5c6382a11245cfc4ee7bd492cd/src/miner.cpp#L68-L79
there is code that is intended to allow recovering from that situation by clamping `nTime` to the range allowed by this consensus rule (and also by the "nTime must be greater than median-time-past" rule).

However, that code does not work as intended, because `nOldTime` is set to `pblock->nTime` which is initially set to the current time at https://github.com/zcash/zcash/blob/1c0c425fdea00d5c6382a11245cfc4ee7bd492cd/src/miner.cpp#L369

`UpdateTime` is only called to update `nTime` for an existing block template, not to set it initially. So, if `nTime` starts at a value that violates the rule, the condition `nOldTime < nNewTime` does not hold when `UpdateTime` is called, and so `nTime` remains at the invalid value rather than being set to the clamped value.

(The intent of the `if (nOldTime < nNewTime)` is to not allow `nTime` to go backwards for a given template. This would be fine by itself absent the initialization problem.)

Note that if a block has not been mined on testnet for more than 24 hours, an additional problem is that (with default options) zcashd nodes will never exit Initial Block Download, and so will not start mining. However, that can be worked around by setting the `maxtipage` config option. Once it is set, the above bug will be exposed (and it is also exposed if the median-time-past is between 90 minutes and 24 hours ago).

This is in practice a testnet-only bug, because it is vanishingly unlikely that a block would fail to be mined on mainnet for 24h.

The fix is to initialize `nTime` to 0 and then immediately call `UpdateTime`, rather than initializing it to `GetTime()`.

### PR DESCRIPTION
**Pull request by daira**
fixes #6960

### CODE REVIEW

File: src/test/miner_tests.cpp [hunk 1]
```diff
@@ -372,18 +372,44 @@ BOOST_AUTO_TEST_CASE(CreateNewBlock_validity)
     // Stop here if we needed to mine more blocks.
     assert(nblocks == sizeof(blockinfo)/sizeof(*blockinfo));
 
+    auto nTime = pblocktemplate->block.nTime;
+    delete pblocktemplate;
+
     // Set the clock to be just ahead of the last "mined" block, to ensure we satisfy the
     // future timestamp soft fork rule.
```
Comment (str4d) [inline src/test/miner_tests.cpp:379]: This comment is now incorrect for the code it is associated with. Move this comment down to where the `-curTime + ...` logic now lives, and replace it here with an accurate comment for this part of the test.

**Review by str4d — APPROVED** [review]
utACK 9831458a4af73f781194f6634720e89ade4da7f4 with comment fix

File: src/test/miner_tests.cpp (hunk 1 above)
Comment (str4d) [reply src/test/miner_tests.cpp:379]: The comment is incorrect here because it says:
> Set the clock to be just ahead of the last "mined" block
but actually sets the clock to be _equal_ to the last "mined" block.

Comment (str4d) [reply src/test/miner_tests.cpp:379]: > is almost a no-op by itself, apart from leaving the clock in fixed mode rather than offset mode.

AFAICT it is not a no-op. The call to `GetTime()` necessarily introduces some delay between itself and `nTime`, because the clock hasn't been overridden yet and is using the normal system clock. The new code has zero delay, per above.

Comment (daira) [reply src/test/miner_tests.cpp:379]: Yes. That was also incorrect prior to this change. I will open another PR to be applied after v6.0.0.

Comment (daira) [reply src/test/miner_tests.cpp:379]: Fixed by #6964.
