### PR TITLE
Fix z_mergetoaddress sending from ANY_SPROUT/ANY_SAPLING when the wallet contains both note types

### LINKED ISSUE #3909: Unable to use z_mergetoaddress with 'ANY_SPROUT' or 'ANY_SAPLING' when wallet contains both Sprout and Sapling notes
Using a wallet that contains both Sprout and Sapling notes:

./zcash-cli z_mergetoaddress '["ANY_SAPLING"]' taddr
error code: -8
error message:
Cannot send from both Sprout and Sapling addresses using z_mergetoaddress

./zcash-cli z_mergetoaddress '["ANY_SPROUT"]' taddr
error code: -8
error message:
Cannot send from both Sprout and Sapling addresses using z_mergetoaddress

### PR DESCRIPTION
**Pull request by Eirik0**
Closes #3909

### CODE REVIEW

**Comment by Eirik0** [comment]
The issue was that when using ANY_SPROUT/ANY_SAPLING we were just checking if `pwalletMain->GetFilteredNotes(sproutEntries, saplingEntries, zaddrs)` returned both sprout and sapling notes and throwing an error if it did (not taking in to account which parameter was passed in).

File: src/wallet/rpcwallet.cpp [hunk 1]
```diff
@@ -4406,8 +4406,15 @@ UniValue z_mergetoaddress(const UniValue& params, bool fHelp)
         if (!saplingActive && saplingEntries.size() > 0) {
             throw JSONRPCError(RPC_INVALID_PARAMETER, "Invalid parameter, Sapling has not activated");
         }
+        // Do not include Sprout/Sapling notes if using "ANY_SAPLING"/"ANY_SPROUT" respectively
```
Comment (bitcartel) [inline src/wallet/rpcwallet.cpp]: If the user includes both keywords, all entries will be cleared.  Or is the existence of both keywords caught/handled elsewhere?

Comment (Eirik0) [reply src/wallet/rpcwallet.cpp]: I changed the logic just below to include `|| (useAnySprout && useAnySapling)`. If the user passes in both values, they will get an error saying that you can't send from both sprout and sapling (I added a test for this too). I would be happy to change this so that we check sooner and the user gets a more specific error message if they pass in both values if we prefer that.

**Comment by ioptio** [comment]
We should specify in the payment API the combination of address types that can work with this call. https://zcash.readthedocs.io/en/latest/rtd_pages/payment_api.html#z-mergetoaddress

**Comment by Eirik0** [comment]
@ioptio I updated the documentation in the RPC help. If that looks good, I will submit something similar to the documentation repo.

File: qa/rpc-tests/mergetoaddress_helper.py [hunk 2]
```diff
@@ -15,14 +15,18 @@
...
         merge_to_address_lambda()
-        fail("Expected exception: %s" % expected_error_msg)
+        caught_exception = False
     except JSONRPCException as e:
         assert_equal(expected_error_msg, e.error['message'])
     except Exception as e:
         fail("Expected JSONRPCException. Found %s" % repr(e))
 
+    if not caught_exception:
+        fail("Expected exception: %s" % expected_error_msg)
```
Comment (daira) [inline qa/rpc-tests/mergetoaddress_helper.py]: This can be written more simply as:
```
    try:
        merge_to_address_lambda()
    except JSONRPCException as e:
        assert_equal(expected_error_msg, e.error['message'])
    except Exception as e:
        fail("Expected JSONRPCException. Found %s" % repr(e))
    else:
        fail("Expected exception: %s" % expected_error_msg)
```

(The `else:` clause executes if the `try:` clause completes normally, but is not itself within the scope of the `try`.)

File: qa/rpc-tests/mergetoaddress_mixednotes.py [hunk 3]
```diff
@@ -0,0 +1,70 @@
...
+            '-nuparams=5ba81b19:100',  # Overwinter
+            '-nuparams=76b809bb:100',  # Sapling
+            '-experimentalfeatures', '-zmergetoaddress'
+        ]] * 4)
+
+    def setup_chain(self):
+        print("Initializing test directory " + self.options.tmpdir)
+        initialize_chain_clean(self.options.tmpdir, 4)
+
+    def run_test(self):
```
Comment (daira) [inline qa/rpc-tests/mergetoaddress_mixednotes.py]: Please add a test case for the error when `ANY_SPROUT` and `ANY_SAPLING` are both given, but there are not notes of both types.

Comment (Eirik0) [reply qa/rpc-tests/mergetoaddress_mixednotes.py]: As it stands now, _I think_ this will end up covering the same code as the test added in the `mergetoaddress_helper.py`, but I will go ahead an add an assertion for when we have only Sprout notes and try to use `ANY_SPROUT` and `ANY_SAPLING`, and a similar one for a wallet with only Sapling notes.

**Comment by Eirik0** [comment]
I copied and pasted a comment and forgot to update Sprout to Sapling. Force pushed to fix this.

File: qa/rpc-tests/mergetoaddress_mixednotes.py [hunk 4]
```diff
@@ -45,7 +46,11 @@ def run_test(self):
 
         assert_equal(Decimal(self.nodes[1].z_gettotalbalance()["transparent"]), Decimal('0'))
 
-        # Send to t_addr from sprout
+        # Make sure we cannot use "ANY_SPROUT" and "ANY_SAPLING" even if we only have Sprout Notes
```
Comment (daira) [inline qa/rpc-tests/mergetoaddress_mixednotes.py]: At this point in the test we have both Sprout and Sapling notes (10 ZEC each), I think.

Comment (Eirik0) [reply qa/rpc-tests/mergetoaddress_mixednotes.py]: You are correct. Fixing now.

**Comment by Eirik0** [comment]
I will squash these commits together after rereview.

**Comment by Eirik0** [comment]
@zkbot r+

File: qa/rpc-tests/mergetoaddress_helper.py [hunk 5]
```diff
@@ -152,6 +153,11 @@ def run_test(self, test):
             "Destination address is also the only source address, and all its funds are already merged.",
             lambda: test.nodes[0].z_mergetoaddress([mytaddr], mytaddr))
 
+        # Merging will fail for this specific case where it would spend a fee and do nothing
```
Comment (daira) [inline qa/rpc-tests/mergetoaddress_helper.py]: This is the wrong comment. (Sorry for not catching this earlier.)

Comment (Eirik0) [reply qa/rpc-tests/mergetoaddress_helper.py]: I missed this when working on this again too. It's poorly worded which makes it harder to catch.

Comment (Eirik0) [reply qa/rpc-tests/mergetoaddress_helper.py]: https://github.com/zcash/zcash/pull/4044
