### PR TITLE
Get rid of underscore prefixes for include guards.

### LINKED ISSUE #1272: Use of reserved identifiers in inclusion guards
A common, but incorrect, practice is to choose a reserved name for a macro used in a preprocessor conditional guarding against multiple inclusions of a header file. (See also PRE06-C. Enclose header files in an inclusion guard.) The name may clash with reserved names defined by the implementation of the C standard library in its headers or with reserved names implicitly predefined by the compiler even when no C standard library header is included

See CERT C Rule "DCL37-C. Do not declare or define a reserved identifier" for more details.

Here are a hand full of locations in zcash that do this:

```
User name starts with underscore. : __ZCASH_UTIL_H
User name starts with underscore. : _PRF_H_
User name starts with underscore. : _ZCNOTE_H_
User name starts with underscore. : _ZCJOINSPLIT_H_
User name starts with underscore. : _ZCADDRESS_H_
```

There are likely more.

One solution is to just remove the "__" from the beginning of the name.

Another solution is to use:
# pragma once

I think this is already used fairly extensively in this code base so it should be supported by all the compilers you use.

There are a variety of arguments for and against, but you may want to pick one solution (that doesn't involved reserved identifiers) and use it consistently.

### PR DESCRIPTION
**Pull request by syd0**
This is because they may conflict with reserved names. Also took
this opportunity to make the guards in the zcash subdir a bit
more uniform by having them all conform to ZC_<...>_H_

This closes #1272

### CODE REVIEW

File: src/zcash/Zcash.h [hunk 1]
```diff
@@ -1,5 +1,5 @@
-#ifndef _ZCCONSTANTS_H_
-#define _ZCCONSTANTS_H_
+#ifndef ZC_CONSTANTS_H_
```
Comment (daira) [inline src/zcash/Zcash.h]: Change to ``ZC_ZCASH_H_``.

**Comment by daira** [comment]
Results of ``grep -Rn '#define _' src`` with some false positives filtered out:

```
src/snark/src/algebra/evaluation_domain/domains/basic_radix2_domain_aux.tcc:28:#define _basic_radix2_FFT _basic_parallel_radix2_FFT
src/snark/src/algebra/evaluation_domain/domains/basic_radix2_domain_aux.tcc:30:#define _basic_radix2_FFT _basic_serial_radix2_FFT
src/snark/build/include/libsnark/algebra/evaluation_domain/domains/basic_radix2_domain_aux.tcc:28:#define _basic_radix2_FFT _basic_parallel_radix2_FFT
src/snark/build/include/libsnark/algebra/evaluation_domain/domains/basic_radix2_domain_aux.tcc:30:#define _basic_radix2_FFT _basic_serial_radix2_FFT
src/secp256k1/src/modules/ecdh/main_impl.h:8:#define _SECP256K1_MODULE_ECDH_MAIN_
src/secp256k1/src/modules/ecdh/tests_impl.h:8:#define _SECP256K1_MODULE_ECDH_TESTS_
src/secp256k1/src/modules/recovery/main_impl.h:8:#define _SECP256K1_MODULE_RECOVERY_MAIN_
src/secp256k1/src/modules/recovery/tests_impl.h:8:#define _SECP256K1_MODULE_RECOVERY_TESTS_
src/secp256k1/src/eckey_impl.h:8:#define _SECP256K1_ECKEY_IMPL_H_
src/secp256k1/src/scalar_8x32.h:8:#define _SECP256K1_SCALAR_REPR_
src/secp256k1/src/ecmult_gen_impl.h:8:#define _SECP256K1_ECMULT_GEN_IMPL_H_
src/secp256k1/src/num_impl.h:8:#define _SECP256K1_NUM_IMPL_H_
src/secp256k1/src/scalar_low.h:8:#define _SECP256K1_SCALAR_REPR_
src/secp256k1/src/hash.h:8:#define _SECP256K1_HASH_
src/secp256k1/src/field_5x52_int128_impl.h:8:#define _SECP256K1_FIELD_INNER5X52_IMPL_H_
src/secp256k1/src/testrand.h:8:#define _SECP256K1_TESTRAND_H_
src/secp256k1/src/gen_context.c:43:    fprintf(fp, "#define _SECP256K1_ECMULT_STATIC_CONTEXT_\n");
src/secp256k1/src/field_10x26.h:8:#define _SECP256K1_FIELD_REPR_
src/secp256k1/src/scalar.h:8:#define _SECP256K1_SCALAR_
src/secp256k1/src/testrand_impl.h:8:#define _SECP256K1_TESTRAND_IMPL_H_
src/secp256k1/src/bench.h:8:#define _SECP256K1_BENCH_H_
src/secp256k1/src/ecdsa.h:8:#define _SECP256K1_ECDSA_
src/secp256k1/src/scalar_low_impl.h:8:#define _SECP256K1_SCALAR_REPR_IMPL_H_
src/secp256k1/src/eckey.h:8:#define _SECP256K1_ECKEY_
src/secp256k1/src/scalar_4x64.h:8:#define _SECP256K1_SCALAR_REPR_
src/secp256k1/src/scalar_impl.h:8:#define _SECP256K1_SCALAR_IMPL_H_
src/secp256k1/src/field_5x52_impl.h:8:#define _SECP256K1_FIELD_REPR_IMPL_H_
src/secp256k1/src/group_impl.h:8:#define _SECP256K1_GROUP_IMPL_H_
src/secp256k1/src/field_5x52.h:8:#define _SECP256K1_FIELD_REPR_
src/secp256k1/src/util.h:8:#define _SECP256K1_UTIL_H_
src/secp256k1/src/field_impl.h:8:#define _SECP256K1_FIELD_IMPL_H_
src/secp256k1/src/ecmult_static_context.h:2:#define _SECP256K1_ECMULT_STATIC_CONTEXT_
src/secp256k1/src/ecmult_gen.h:8:#define _SECP256K1_ECMULT_GEN_
src/secp256k1/src/ecmult.h:8:#define _SECP256K1_ECMULT_
src/secp256k1/src/ecdsa_impl.h:9:#define _SECP256K1_ECDSA_IMPL_H_
src/secp256k1/src/num_gmp.h:8:#define _SECP256K1_NUM_REPR_
src/secp256k1/src/num.h:8:#define _SECP256K1_NUM_
src/secp256k1/src/ecmult_const_impl.h:8:#define _SECP256K1_ECMULT_CONST_IMPL_
src/secp256k1/src/num_gmp_impl.h:8:#define _SECP256K1_NUM_REPR_IMPL_H_
src/secp256k1/src/ecmult_impl.h:8:#define _SECP256K1_ECMULT_IMPL_H_
src/secp256k1/src/basic-config.h:8:#define _SECP256K1_BASIC_CONFIG_
src/secp256k1/src/field_5x52_asm_impl.h:15:#define _SECP256K1_FIELD_INNER5X52_IMPL_H_
src/secp256k1/src/hash_impl.h:8:#define _SECP256K1_HASH_IMPL_H_
src/secp256k1/src/scalar_8x32_impl.h:8:#define _SECP256K1_SCALAR_REPR_IMPL_H_
src/secp256k1/src/ecmult_const.h:8:#define _SECP256K1_ECMULT_CONST_
src/secp256k1/src/scalar_4x64_impl.h:8:#define _SECP256K1_SCALAR_REPR_IMPL_H_
src/secp256k1/src/field.h:8:#define _SECP256K1_FIELD_
src/secp256k1/src/group.h:8:#define _SECP256K1_GROUP_
src/secp256k1/src/field_10x26_impl.h:8:#define _SECP256K1_FIELD_REPR_IMPL_H_
src/secp256k1/contrib/lax_der_privatekey_parsing.h:29:#define _SECP256K1_CONTRIB_BER_PRIVATEKEY_H_
src/secp256k1/contrib/lax_der_parsing.h:52:#define _SECP256K1_CONTRIB_LAX_DER_PARSING_H_
```

**Comment by daira** [comment]
I think it's worth cleaning up the libsecp256k1 cases; we might as well fix the problem completely.

**Comment by daira** [comment]
Note that libsecp256k1 has some duplicated guard names, e.g. between ``src/secp256k1/src/scalar_8x32_impl.h:8`` and ``src/secp256k1/src/scalar_4x64_impl.h``. I don't know whether this was intentional to prevent both implementations from being #included, but if so, it would actually just cause the second ``#include`` to silently do nothing, which seems like a bad idea.

**Comment by syd0** [comment]
re: duplicate guard names, that's a good catch @daira. I had initially ignored secp256 because I wasn't sure if it was part of zcash proper (it looked like an external library). I've fixed the duplicate guard names, luckily it doesn't seem like they were being depended on.

IMO we should probably switch things to #pragma once, but I'm just not sure if zcash targets compilers that don't support it.

**Comment by str4d** [comment]
Since it isn't possible to cherry-pick subtree merges, please just drop the last commit from this PR (while rebasing to squash the first two together), and I'll open a separate PR to update the library.

**Comment by str4d** [comment]
Opened #2780 for the secp256k1 bump.

**Comment by syd0** [comment]
@str4d - cool this was done - removed the secp256k commit.

**Comment by str4d** [comment]
Thanks @syd0!

@zkbot r+
