### PR TITLE
Fix assertion in wallet initialization when wallet best block is ahead of the main chain.

### LINKED ISSUE #5846: Bug: Assertion `orchardWallet.CheckpointNoteCommitmentTree(pindex->nHeight)' failed.
I was running the latest `nu5_private_testnet` and left it mining for a while. When I came back, I had a `Segmentation fault (core dumped)` message.  I did not have coredumps enabled and assumed I had an issue with mining. I restarted the node and received this message on the metrics screen which I now get every time I try start the node:

```
zcashd: wallet/wallet.cpp:2636: void CWallet::IncrementNoteWitnesses(const Consensus::Params &, const CBlockIndex *, const CBlock *, MerkleFrontiers &, bool): Assertion `orchardWallet.CheckpointNoteCommitmentTree(pindex->nHeight)' failed.
Aborted (core dumped)
```

I do have this core dump available.

### PR DESCRIPTION
**Pull request by nuttycom**
In #5809, we attempted to fix the assumption that on startup, the
wallet's best chain was at the same position as the node's chain tip.
This did not account for a condition where the node's block index
might not contain the block corresponding to the wallet's best chain,
because the node had crashed before the block index containing that
block could be written to disk.

This commit adds handling so that the `ThreadNotifyWallets` thread
will not start until the wallet's best block has been restored
to the node's block index and we're able to obtain a pointer to
that state.

Fixes #5846

### CODE REVIEW

File: src/init.cpp [hunk 1]
```diff
@@ -599,6 +602,108 @@ void CleanupBlockRevFiles()
     }
 }
 
+void ThreadStartWalletNotifier()
+{
+    CBlockIndex *pindexLastTip;
+
+    // However, if a wallet is enabled, we actually want to start notifying
```
Comment (str4d) [inline src/init.cpp:609]:
```suggestion
    // If the wallet is compiled in and enabled, we want to start notifying
```

File: src/init.cpp [hunk 2]
```diff
@@ -599,6 +602,108 @@ void CleanupBlockRevFiles()
...
+                if (timedOut()) {
+                    return;
+                }
+            }
+
+            // We cannot progress with wallet notification until the chain tip is no
+            // more than 100 blocks behind pindexLastTip. This can occur if the node
+            // shuts down abruptly without being able to write out chainActive; the
+            // node writes chain data out roughly hourly, while the wallet writes it
+            // every 10 minutes. We need to wait for ThreadImport to catch up.
```
Comment (str4d) [inline src/init.cpp:671]:
```suggestion
            // every 10 minutes. We need to wait for ThreadImport to catch up, or any
            // missing blocks to be fetched from peers.
```

**Review by str4d — APPROVED** [review]
utACK, but I was in the pairing where this PR was written, so this needs another review.

File: src/init.cpp [hunk 3]
```diff
@@ -599,6 +602,108 @@ void CleanupBlockRevFiles()
...
+            while (true) {
+                boost::this_thread::interruption_point();
+
+                const CBlockIndex *pindexFork = chainActive.FindFork(pindexLastTip);
```
Comment (therealyingtong) [inline src/init.cpp:676]: Do we nedd `LOCK(cs_main)` here?

**Review by therealyingtong — APPROVED** [review]
utACK with a question.

File: src/init.cpp (hunk 3 above)
Comment (nuttycom) [reply src/init.cpp]: Yup, great catch! Fixed.
