### PR TITLE
Don't rename main thread

### LINKED ISSUE #6066: Don't rename main thread it should be zcashd
### Describe the issue
main thread is showing as zc-wait-to-stop  instead of zcashd

#### If so, please list the steps to reproduce below:
1.  run zcashd
2. check name process 

### Expected behaviour
I'm expecting original name zcashd  instead of zc-wait-to-stop

### Actual behaviour + errors
ps ax | grep zcashd
  37137 ?        SLsl   3:56 zcashd
cat /proc/37137/task/37137/comm 
zc-wait-to-stop

### The version of Zcash you were using:
Zcash Daemon version v5.1.0

### Machine specs:
- Ubuntu 20.04.4 LTSca
- CPU: Intel(R) Xeon(R) Silver 4210R CPU @ 2.40GHz
- RAM: 128GB
- Disk size: 1 TG
- Disk Type (HD/SDD): SSD
- Linux kernel version (uname -a): Linux mn-template 5.4.0-121-generic #137-Ubuntu SMP Wed Jun 15 13:33:07 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- Compiler version (gcc --version): gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
- Linker version (ld -v): GNU ld (GNU Binutils for Ubuntu) 2.34
- Assembler version (as --version): GNU assembler (GNU Binutils for Ubuntu) 2.34

### PR DESCRIPTION
**Pull request by daira**
This reverts part of 1f1810c37d00cb46d00d8553e6de3c6fdb991010 in #5959.
Leaving the main thread unnamed causes it to be displayed as the executable name (i.e. `zcashd`)
or command line in process monitoring tools. fixes #6066

### CODE REVIEW

File: src/bitcoind.cpp [hunk 1]
```diff
@@ -43,10 +43,6 @@ static bool fDaemon;
 
 void WaitForShutdown(boost::thread_group* threadGroup)
 {
-    // This is the main process thread, but after this point, all we do here is wait for
-    // shutdown, and then shut down the node.
```
Comment (daira) [inline src/bitcoind.cpp:47]: I guess the comment is still correct. Let me know if you want to retain it (but I think it's fairly obvious from the name of the function).

**Comment by gades** [comment]
I did small improvement for it https://github.com/zcash/zcash/pull/6068

**Review by nuttycom — APPROVED** [review]
utACK

**Review by ebfull — APPROVED** [review]
