### PR TITLE
Do not return Orchard components from z_gettreestate before NU5 activation.

### LINKED ISSUE #5957: Severe Performance Regression in zcashd v5.0.0 on z_gettreestate RPC
### Describe the issue
One of the RPC methods in zcashd has a severe performance regression over v4.6.0-2. This issue is most likely also present in v4.7.0, but I haven't tested it yet. 

### Can you reliably reproduce the issue?
LightwalletD is currently unable to run against v5.0.0 when running in production, because one of the RPC methods is taking too long to return. It is almost certainly one of these RPC methods:
- `getaddresstxids`
- `getrawtransaction`
- `getaddressbalance`
- `getaddressutxos`

What is happening is that one of these RPCs is grabbing some sort of lock inside zcashd and taking a long time to return. This causes CPU usage on one core to become 100%, and subsequent RPC calls to queue up, eventually failing with a timeout. Note that my machine has multiple cores, but zcashd consumes 100% of one core and locks up the RPCs, eventually causing timeouts. 

This is also happening only in production, which makes me think that the large number of calls coming in from Zecwallet users is causing this problem.

### The version of Zcash you were using:
v5.0.0, (but almost certainly also happens with v4.7.0)

### Machine specs:
4 core AWS t2.xlarge instance with 8GB of ram.

### PR DESCRIPTION
**Pull request by nuttycom**
Fixes #5957

### CODE REVIEW

**Comment by nuttycom** [comment]
@LarryRuane You should include similar guards in your work on https://github.com/zcash/zcash/issues/5527

**Review by steven-ecc — DISMISSED** [review]
utACK

File: src/rpc/blockchain.cpp [hunk 1]
```diff
@@ -1337,7 +1337,7 @@ UniValue z_gettreestate(const UniValue& params, bool fHelp)
     }
 
     // orchard
-    {
+    if (Params().GetConsensus().NetworkUpgradeActive(chainActive.Height(), Consensus::UPGRADE_NU5)) {
```
Comment (steven-ecc) [inline src/rpc/blockchain.cpp:1340]: Did you close this bracket somewhere?

Comment (steven-ecc) [reply src/rpc/blockchain.cpp:1340]: NM, all good.

Comment (adityapk00) [reply src/rpc/blockchain.cpp:1340]: Can you do the same thing for Sapling above? If the `z_gettreestate` requests a block pre-sapling, the same bug is present.

File: src/rpc/blockchain.cpp [hunk 2]
```diff
@@ -1337,7 +1337,7 @@ UniValue z_gettreestate(const UniValue& params, bool fHelp)
     }
 
     // orchard
-    {
+    if (Params().GetConsensus().NetworkUpgradeActive(pindex->nHeight, Consensus::UPGRADE_NU5)) {
```
Comment (daira) [inline src/rpc/blockchain.cpp:1340]: Comment on line 1351 and the subsequent loop: why would a post-NU5 block not have an Orchard final state?

Comment (nuttycom) [reply src/rpc/blockchain.cpp:1340]: That's a good question; the same applies to line 1325. I'm not sure why blocks might not have a final state after activation.

Comment (nuttycom) [reply src/rpc/blockchain.cpp:1340]: Oh! It might be defensive against the eventual deactivation of these protocols; that's the only situation under which I'd expect there to be a series of blocks *after* a non-null root. But in that circumstance, I don't think we'd want to scan. I'd like to get @str4d's comments here to decide what to do about this.

The tests for this code explicitly check for a null `finalRoot` value, so rather than omitting the section entirely I'll just skip the expensive scan.

**Review by therealyingtong — APPROVED** [review]
utACK

**Comment by pacu** [comment]
Sorry for being late to the party. 
The z_gettreestate now serves SaplingTree and OrchardTree states but the JSON field changed for the sapling tree. Does ZecWallet support that? Protobuf in lightwalletd save us from that with parameter ordinals, but that's not the case for "unstructured" json.

**Comment by adityapk00** [comment]
What do you mean the JSON field has changed? Which field has changed?

**Comment by steven-ecc** [comment]
The format of the JSON returned by z_gettreestate didn't change for Sapling AFAIK. @pacu what are you referring to specifically?

**Comment by pacu** [comment]
Yesterday I was working on fixing a missing checkpoint for darksidewalletd, and when I called 
`grpcurl -d '{ "height" : 663150 }' lightwalletd.electriccoin.co:9067 cash.z.wallet.sdk.rpc.CompactTxStreamer/GetTreeState`

I got a response with the keys saplingTree and orchardTree, instead of just a single tree. 

Now that doesn't seem to be the case. 

Anyhow, clients using GRPC were not affected by this because the ordinal aspect of the JSON is respected.

**Comment by nuttycom** [comment]
I'm going to revert this entirely; I think the problem is actually that the empty root that we're checking against in GetOrchardAnchorAt may be the zero value rather than the actually empty root.

**Comment by pacu** [comment]
I think there's a positive mixup from my comment which is related to the lightwalletd counter part of this RPC 😅
