### PR TITLE
Fix "--disable-mining" build regression 

### LINKED ISSUE #4634: zcashd doesn't compile with --disable-mining
### Describe the issue
` CONFIGURE_FLAGS="--disable-tests --disable-mining --disable-bench" ./zcutil/build.sh` fails with 
```
main.h:118:35: error: ‘equihash_solution_size’ was not declared in this scope
  118 |     ((CBlockHeader::HEADER_SIZE + equihash_solution_size(N, K))*MAX_HEADERS_RESULTS < \
      |                                   ^~~~~~~~~~~~~~~~~~~~~~
/home/adityapk/github/zcash/depends/x86_64-unknown-linux-gnu/share/../include/boost/static_assert.hpp:70:55: note: in definition of macro ‘BOOST_STATIC_ASSERT’
   70 | #     define BOOST_STATIC_ASSERT( ... ) static_assert(__VA_ARGS__, #__VA_ARGS__)
      |                                                       ^~~~~~~~~~~
chainparams.cpp:509:29: note: in expansion of macro ‘equihash_parameters_acceptable’
  509 |         BOOST_STATIC_ASSERT(equihash_parameters_acceptable(N, K));
```

### Can you reliably reproduce the issue?
Yes

### Expected behaviour
Compile succeeds with disabled mining

### The version of Zcash you were using:
master branch

### Any extra information that might be useful in the debugging process.
The problem is the method `equihash_solution_size` here (https://github.com/zcash/zcash/blob/b4ec903ac4e27943b667291c34271b2275653bb1/src/crypto/equihash.h#L160) is behind a `#ifdef ENABLE_MINING`, but is being used in a `static_assert` here (https://github.com/zcash/zcash/blob/959f5b09d0b5110499ce6a9675f0d3ea55792185/src/chainparams.cpp#L96) that is outside a `#ifdef ENABLE_MINING`

### PR DESCRIPTION
**Pull request by daira**
closes #4634

Test by building with:
* `CONFIGURE_FLAGS="--disable-tests --disable-mining --disable-bench" zcutil/build.sh`
* `zcutil/distclean.sh`
* `CONFIGURE_FLAGS="--disable-mining" zcutil/build.sh`

After the second build, run `qa/zcash/full-test-suite.py`. Stop when it gets to the RPC tests, which will hang. The preceding parts of the test suite are all expected to pass.

Signed-off-by: Daira Hopwood <daira@jacaranda.org>

### CODE REVIEW

**Comment by daira** [comment]
The diff is a little bit less confusing if you review with the "Split diff" setting.

**Comment by daira** [comment]
Note that this doesn't allow RPC tests to pass, because those depend on mining. It does allow the rest of the test suite to pass.

File: src/gtest/test_equihash.cpp [hunk 1]
```diff
@@ -7,6 +7,7 @@
 
 #include "crypto/equihash.h"
 #include "uint256.h"
+#include "utilstrencodings.h"
```
Comment (therealyingtong) [inline src/gtest/test_equihash.cpp:10]: why do we need `utilstrencodings.h` here?

**Comment by adityapk00** [comment]
Looks good. I can confirm it works. Thanks for quickly fixing this!

File: src/gtest/test_equihash.cpp (hunk 1 above)
Comment (daira) [reply src/gtest/test_equihash.cpp:10]: It's needed for `ParseHex`.

**Comment by daira** [comment]
@zkbot r+
