### PR TITLE
Enforce first four bits are zero for all spending keys and phi.

### LINKED ISSUE #899: Enforce 4 leading bits are zero on 252-bit values
After #888 is merged, those values are represented by `uint256` and when they're given to the PRF the leading bits are masked off. I'd prefer to throw an exception when those leading bits are nonzero, and to have a separate method for generating those 252-bit values (instead of just generating a random `uint256`. Sean also suggest having a `uint252` type, which I would also like.

### PR DESCRIPTION
**Pull request by ebfull**
This introduces a `uint252` to ensure these fields are 252-bits for the PRFs.

Closes #899

### CODE REVIEW

File: src/gtest/test_noteencryption.cpp [hunk 1]
```diff
@@ -100,9 +100,10 @@ TEST(noteencryption, api)
 
 uint256 test_prf(
     unsigned char distinguisher,
-    uint256 x,
+    uint252 seed_x,
     uint256 y
 ) {
+    uint256 x = seed_x.inner();
     *x.begin() &= 0x0f;
```
Comment (defuse) [inline src/gtest/test_noteencryption.cpp]: This should no longer be necessary if `uint252` does what I expect. Perhaps change it to:

```c
assert((*x.begin() & 0x0f) == *x.begin());
```

Comment (defuse) [inline src/gtest/test_noteencryption.cpp]: Oh this is just the test PRF.

File: src/uint252.h [hunk 2]
```diff
@@ -0,0 +1,46 @@
...
+    }
+
+    const unsigned char* end() const
+    {
+        return contents.end();
+    }
+
+    uint252() : contents() {};
+    explicit uint252(const uint256& in) : contents(in) {
+        (*contents.begin()) &= 0x0F;
```
Comment (defuse) [inline src/uint252.h]: It's safer in my opinion if this checks that the leading bits are 0 instead of silently zeroing them if they aren't. In order to do that we'd just have to add an `libzcash::random_uint252()` since random generating is the only case we currently use this behavior.

File: src/gtest/test_joinsplit.cpp [hunk 3]
```diff
@@ -257,7 +257,7 @@ TEST(joinsplit, full_api_test)
 
 TEST(joinsplit, note_plaintexts)
 {
-    uint256 a_sk = uint256S("f6da8716682d600f74fc16bd0187faad6a26b4aa4c24d5c055b216d94516847e");
+    uint252 a_sk = uint252(uint256S("f6da8716682d600f74fc16bd0187faad6a26b4aa4c24d5c055b216d94516847e"));
```
Comment (defuse) [inline src/gtest/test_joinsplit.cpp]: I'd expect this to throw an exception because the leading byte is 0x7e. See my comment below about whether or not the constructor should silently mask those bits or throw an exception if they're nonzero.

File: src/zcash/prf.cpp [hunk 4]
```diff
@@ -2,7 +2,7 @@
 #include "crypto/sha256.h"
 
 uint256 PRF(bool a, bool b, bool c, bool d,
-            const uint256& x,
+            const uint252& x,
             const uint256& y)
 {
```
Comment (defuse) [inline src/zcash/prf.cpp]: The line `blob[0] &= 0x0F` below can be removed, I suggest replacing it with an assertion that the leading bits are zero.

File: src/zcash/circuit/utils.tcc [hunk 5]
```diff
@@ -28,6 +31,14 @@ std::vector<bool> uint256_to_bool_vector(uint256 input) {
     return output_bv;
 }
 
+std::vector<bool> uint256_to_bool_vector(uint256 input) {
+    return to_bool_vector(input);
+}
+
+std::vector<bool> uint252_to_bool_vector(uint252 input) {
+    return trailing252(to_bool_vector(input));
```
Comment (defuse) [inline src/zcash/circuit/utils.tcc]: Instead of using templates we could do `return trailing252(to_bool_vector(input.inner()));` but the way it is now is fine.

**Comment by defuse** [comment]
ACK. https://github.com/zcash/zcash/pull/956/files#r64312443 and https://github.com/zcash/zcash/pull/956/files#r64311907 are nice to have but don't block this PR in my opinion.

File: src/gtest/test_joinsplit.cpp (hunk 3 above)
Comment (daira) [inline src/gtest/test_joinsplit.cpp]: Also, perhaps add a ``uint252S`` function?

File: src/gtest/test_noteencryption.cpp [hunk 6]
```diff
@@ -117,15 +118,15 @@ uint256 test_prf(
 TEST(noteencryption, prf_addr)
 {
     for (size_t i = 0; i < 100; i++) {
-        uint256 a_sk = libzcash::random_uint256();
+        uint252 a_sk = uint252(libzcash::random_uint256());
```
Comment (daira) [inline src/gtest/test_noteencryption.cpp]: If this were a separate ``random_uint252`` function, it would allow the constructor to throw when given an invalid input (not zeroes in the first four bits).

File: src/uint252.h (hunk 2 above)
Comment (daira) [inline src/uint252.h]: Ah, I see we came to the same conclusion :-)

**Comment by ebfull** [comment]
Added `random_uint252` and made the `uint252` constructor throw if given an input with any of the first four bits set. Rebased.

File: src/gtest/test_noteencryption.cpp (hunk 1 above)
Comment (daira) [inline src/gtest/test_noteencryption.cpp]: Even though this is the test PRF, that would probably be a good change to make because failure of that assertion would indicate a bug in the test.

**Comment by daira** [comment]
ACK. I think it would be good to address https://github.com/zcash/zcash/pull/956/files#r64311523 and https://github.com/zcash/zcash/pull/956/files#r64312443 , but that dies not block the PR.

**Comment by ebfull** [comment]
@zkbot r+
