### PR TITLE
WriteWitnessCache: Catch errors and abort transaction

### LINKED ISSUE #1452: Exception safety of WriteWitnessCache
What happens if an exception is thrown after ``TxnBegin()`` in ``WriteWitnessCache``? It should call ``TxnAbort`` and rethrow, I think.

### PR DESCRIPTION
**Pull request by str4d**
Closes #1452

### CODE REVIEW

**Comment by bitcartel** [comment]
Looks good.  Is it possible to mock walletdb to return false and throw an exception to test the error handling?

**Comment by daira** [comment]
utACK. I considered whether we should be catching ``...`` rather than ``std::exception``, but I guess there is nothing that would be throwing a bare exception that is called from within the ``try``, so it doesn't matter.

**Comment by str4d** [comment]
@bitcartel tests added (which required moving the implementation into the header).

File: src/wallet/gtest/test_wallet.cpp [hunk 1]
```diff
@@ -679,6 +697,50 @@ TEST(wallet_tests, ClearNoteWitnessCache) {
...
+        .Times(4);
+
+    EXPECT_CALL(walletdb, WriteTx(wtx.GetHash(), wtx))
+        .WillOnce(Return(false))
+        .WillOnce(ThrowLogicError())
+        .WillRepeatedly(Return(true));
+    EXPECT_CALL(walletdb, WriteWitnessCacheSize(0))
+        .WillOnce(Return(false))
+        .WillOnce(ThrowLogicError())
+        .WillRepeatedly(Return(true));
```
Comment (daira) [inline src/wallet/gtest/test_wallet.cpp]: I find this style of test very difficult to follow; split it up so that the EXPECT_CALLs are associated with a given call to ``WriteWitnessCache``. Otherwise it's not possible to tell, for instance, *which* calls to ``WriteWitnessCache`` called ``TxnAbort``.

**Comment by bitcartel** [comment]
@str4d ACK once test above is split up.

**Comment by str4d** [comment]
@daira @bitcartel Test split up.

**Comment by bitcartel** [comment]
Is WriteWitnessCache a template because of the test?

Also I think the tests before they were split up were easier to read, I can understand why that style is used in the GoogleMock docs.

ACK+cov

**Comment by str4d** [comment]
@bitcartel
> Is WriteWitnessCache a template because of the test?

[Yes](https://github.com/google/googletest/blob/master/googlemock/docs/CookBook.md#mocking-nonvirtual-methods).

> Also I think the tests before they were split up were easier to read, I can understand why that style is used in the GoogleMock docs.

Up to you and @daira to fight it out; I can remove the last commit if desired.

**Comment by bitcartel** [comment]
I'm fine with the change to the test, it was just a comment about the style.  We have ACK+cov and utACK so we are good to merge.
@zkbot r+

**Comment by daira** [comment]
I do definitely prefer this style. Post-hoc ACK.
