### PR TITLE
Reduce memory usage of CBlockIndex

### LINKED ISSUE #5936: stop storing all the Equihash solutions in memory
### Describe the issue
`zcashd` reliably gets OOM-killed on a 4GB machine during initial block download -- on both testnet and mainnet.

### Can you reliably reproduce the issue?
Yes.

#### If so, please list the steps to reproduce below:
1. start up a 4GB `e2-medium` GCP instance, with Debian 11, 512 GB disk
2. `sudo apt-get install  build-essential pkg-config libc6-dev m4 g++-multilib autoconf libtool ncurses-dev unzip git python3 python3-zmq  zlib1g-dev curl bsdmainutils automake libtinfo5 gdb tmux wormhole`
3. `git clone https://github.com/zcash/zcash && cd zcash`
4. `git checkout f285a39063d71c4c7da6a4c8188be66b97bd1be8`
5. `./zcutil/build.sh -j4`
6. `mkdir ~/.zcash && echo 'testnet=1' > ~/.zcash/zcash.conf`
7. `./src/zcashd`

## Expected behaviour
`zcashd` should sync to the tip of testnet, or if it fails, should fail cleanly (giving an error).

### Actual behaviour + errors
```
Thank you for running a testnet zcashd v4.7.0 node!
You're helping to strengthen the network and contributing to a social good :)

In order to ensure you are adequately protecting your privacy when using Zcash,
please see <https://z.cash/support/security/>.

     Downloading blocks | 282753 (980960 headers) / ~1755310 (16%)
                        | [                                                  ]
           Next upgrade | Blossom at block height 584000, in around 522 days
            Connections | 5
  Network solution rate | 19.000 Sol/s

You are currently not mining.
To enable mining, add 'gen=1' to your zcash.conf and restart.

Since starting this node 1 hours, 0 minutes, 20 seconds ago:
- You have validated 220258 transactions!

[Press Ctrl+C to exit] [Set 'showmetrics=0' to hide]
Killed
```
along with this in the dmesg:
```
[ 3729.759783] zcash-msghand invoked oom-killer: gfp_mask=0x100dca(GFP_HIGHUSER_MOVABLE|__GFP_ZERO), order=0, oom_score_adj=0
[ 3729.771065] CPU: 1 PID: 685 Comm: zcash-msghand Not tainted 5.10.0-13-cloud-amd64 #1 Debian 5.10.106-1
[ 3729.780569] Hardware name: Google Google Compute Engine/Google Compute Engine, BIOS Google 01/01/2011
[ 3729.789988] Call Trace:
[ 3729.792551]  dump_stack+0x6b/0x83
[ 3729.795996]  dump_header+0x4a/0x1f0
[ 3729.799724]  oom_kill_process.cold+0xb/0x10
[ 3729.804031]  out_of_memory+0x1bd/0x500
[ 3729.807978]  __alloc_pages_slowpath.constprop.0+0xb8c/0xc60
[ 3729.938487]  __alloc_pages_nodemask+0x2da/0x310
[ 3729.943150]  alloc_pages_vma+0x80/0x260
[ 3729.947094]  handle_mm_fault+0xe69/0x1bf0
[ 3729.951226]  do_user_addr_fault+0x1b8/0x3f0
[ 3729.955604]  exc_page_fault+0x78/0x160
[ 3729.959474]  ? asm_exc_page_fault+0x8/0x30
[ 3729.963690]  asm_exc_page_fault+0x1e/0x30
[ 3729.967823] RIP: 0033:0x7f6bb5da5e73
[ 3729.971598] Code: Unable to access opcode bytes at RIP 0x7f6bb5da5e49.
[ 3729.978233] RSP: 002b:00007f6b90ff7ad8 EFLAGS: 00010206
[ 3729.983569] RAX: 00007f69ffdb9010 RBX: 000000003b7ffcb6 RCX: 00007f6a3b5b8ca6
[ 3729.990816] RDX: 0000000015a06ca6 RSI: 00007f6a9cbb3020 RDI: 00007f6a25bb1fa0
[ 3729.998072] RBP: 0000000077000000 R08: fffffffffffffff0 R09: 0000000000000000
[ 3730.005316] R10: 00007f6a3b5b8cc6 R11: 00007f69ffdb9010 R12: 0000000000000001
[ 3730.012567] R13: 00007f69ffdb9010 R14: 0000000000000689 R15: 00007f6b90ff7c50
[ 3730.019853] Mem-Info:
[ 3730.022234] active_anon:422 inactive_anon:960854 isolated_anon:0
                active_file:59 inactive_file:32 isolated_file:0
                unevictable:64 dirty:2 writeback:6
                slab_reclaimable:3285 slab_unreclaimable:4019
                mapped:11 shmem:91 pagetables:2201 bounce:0
                free:21664 free_pcp:67 free_cma:0
[ 3730.053926] Node 0 active_anon:1688kB inactive_anon:3843416kB active_file:236kB inactive_file:28kB unevictable:256kB isolated(anon):0kB isolated(file):128kB mapped:44kB dirty:8kB writeback:24kB shmem:364kB shmem_thp: 0kB shmem_pmdmapped: 0kB anon_thp: 1767424kB writeback_tmp:0kB kernel_stack:1936kB all_unreclaimable? yes
[ 3730.206803] Node 0 DMA free:15828kB min:264kB low:328kB high:392kB reserved_highatomic:0KB active_anon:0kB inactive_anon:0kB active_file:0kB inactive_file:0kB unevictable:0kB writepending:0kB present:15920kB managed:15828kB mlocked:0kB pagetables:0kB bounce:0kB free_pcp:0kB local_pcp:0kB free_cma:0kB
[ 3730.233529] lowmem_reserve[]: 0 2962 3915 3915 3915
[ 3730.238538] Node 0 DMA32 free:54516kB min:50852kB low:63564kB high:76276kB reserved_highatomic:0KB active_anon:0kB inactive_anon:2951080kB active_file:0kB inactive_file:0kB unevictable:0kB writepending:4kB present:3126080kB managed:3033260kB mlocked:0kB pagetables:1712kB bounce:0kB free_pcp:20kB local_pcp:0kB free_cma:0kB
[ 3730.267253] lowmem_reserve[]: 0 0 952 952 952
[ 3730.271744] Node 0 Normal free:16312kB min:16460kB low:20572kB high:24684kB reserved_highatomic:0KB active_anon:1688kB inactive_anon:891704kB active_file:296kB inactive_file:452kB unevictable:256kB writepending:28kB present:1048576kB managed:975812kB mlocked:256kB pagetables:7092kB bounce:0kB free_pcp:248kB local_pcp:0kB free_cma:0kB
[ 3730.301500] lowmem_reserve[]: 0 0 0 0 0
[ 3730.305461] Node 0 DMA: 1*4kB (U) 0*8kB 1*16kB (U) 2*32kB (U) 2*64kB (U) 2*128kB (U) 0*256kB 0*512kB 1*1024kB (U) 1*2048kB (M) 3*4096kB (M) = 15828kB
[ 3730.444277] Node 0 DMA32: 36*4kB (UME) 84*8kB (UME) 62*16kB (UME) 82*32kB (UME) 36*64kB (UME) 24*128kB (UE) 12*256kB (UE) 8*512kB (UME) 37*1024kB (UME) 0*2048kB 0*4096kB = 54864kB
[ 3730.460410] Node 0 Normal: 259*4kB (UME) 182*8kB (UE) 206*16kB (UME) 86*32kB (UE) 55*64kB (UE) 31*128kB (UME) 3*256kB (UM) 0*512kB 0*1024kB 0*2048kB 0*4096kB = 16796kB
[ 3730.475505] Node 0 hugepages_total=0 hugepages_free=0 hugepages_surp=0 hugepages_size=1048576kB
[ 3730.484332] Node 0 hugepages_total=0 hugepages_free=0 hugepages_surp=0 hugepages_size=2048kB
[ 3730.492902] 196 total pagecache pages
[ 3730.496702] 0 pages in swap cache
[ 3730.500139] Swap cache stats: add 0, delete 0, find 0/0
[ 3730.505487] Free swap  = 0kB
[ 3730.508490] Total swap = 0kB
[ 3730.511489] 1047644 pages RAM
[ 3730.514782] 0 pages HighMem/MovableOnly
[ 3730.518742] 41419 pages reserved
[ 3730.522101] Tasks state (memory values in pages):
[ 3730.526930] [  pid  ]   uid  tgid total_vm      rss pgtables_bytes swapents oom_score_adj name
[ 3730.535676] [    198]     0   198    12574      734    98304        0          -250 systemd-journal
[ 3730.544856] [    216]     0   216     4834      259    65536        0         -1000 systemd-udevd
[ 3730.553861] [    324]     0   324     2030      847    53248        0             0 haveged
[ 3730.687586] [    343]     0   343    24956      347    73728        0             0 dhclient
[ 3730.696154] [    347]   103   347     1952      133    53248        0          -900 dbus-daemon
[ 3730.704975] [    356]     0   356    55219      248    73728        0             0 rsyslogd
[ 3730.713621] [    406]   105   406     4747      168    57344        0             0 chronyd
[ 3730.722091] [    407]   105   407     2666      138    57344        0             0 chronyd
[ 3730.730572] [    409]     0   409    28577     3230    98304        0          -999 google_guest_ag
[ 3730.740358] [    421]     0   421    30245     3159   110592        0             0 google_osconfig
[ 3730.749530] [    486]     0   486     6728     1870    94208        0             0 unattended-upgr
[ 3730.758701] [    490]     0   490      703       29    45056        0             0 agetty
[ 3730.767092] [    491]     0   491     1084       30    45056        0             0 agetty
[ 3730.775480] [    514]     0   514     3379      198    69632        0             0 systemd-logind
[ 3730.784569] [    515]     0   515     3323      244    61440        0         -1000 sshd
[ 3730.792976] [    521]     0   521     1394       52    45056        0             0 cron
[ 3730.801197] [    532]  1000   532     3780      293    69632        0             0 systemd
[ 3730.934628] [    533]  1000   533    41658      667    94208        0             0 (sd-pam)
[ 3730.943256] [    569]  1000   569     1324      302    53248        0             0 tmux: server
[ 3730.952270] [    570]  1000   570     1498      148    53248        0             0 bash
[ 3730.960483] [    660]  1000   660  1564965   947446  7876608        0             0 zcashd
[ 3730.968878] [    664]  1000   664     1498      138    49152        0             0 bash
[ 3730.977090] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/user.slice/user-1000.slice/session-1.scope,task=zcashd,pid=660,uid=1000
[ 3730.993790] Out of memory: Killed process 660 (zcashd) total-vm:6259860kB, anon-rss:3789784kB, file-rss:0kB, shmem-rss:0kB, UID:1000 pgtables:7692kB oom_score_adj:0
[ 3731.254906] oom_reaper: reaped process 660 (zcashd), now anon-rss:256kB, file-rss:0kB, shmem-rss:0kB
```

### The version of Zcash you were using:
Run `zcashd --version` to find out
Compiled off git commit hash `f285a39063d71c4c7da6a4c8188be66b97bd1be8`.

### Machine specs:
- OS name + version: Debian 11
- CPU: Intel Broadwell (`e2-medium`)
- RAM: 4GB
- Disk size: 512 GB
- Disk Type (HD/SDD): GCP Balanced persistent disk
- Linux kernel version (uname -a): 5.10.0-13-cloud-amd64
- Compiler version (gcc --version): gcc (Debian 10.2.1-6) 10.2.1 20210110 (though presumably it was compiled with the version of clang specified by `depends/packages/native_clang.mk`
- Linker version (ld -v): GNU ld (GNU Binutils for Debian) 2.35.2
- Assembler version (as --version): GNU assembler (GNU Binutils for Debian) 2.35.2

### Any extra information that might be useful in the debugging process.
1. I will upload an example `~/.zcash/debug.log` once i'm on an internet connection that's not on an airplane (the logfiles are ~60MB each).

2. There are a bunch of `POTENTIAL DEADLOCK DETECTED` error messages, I posted an excerpt of them in the corresponding issue: https://github.com/zcash/zcash/issues/5776#issuecomment-1120501677.

3. The block height at OOM varies, values i've encountered are: 282753, 252245, 255127, 282729.

4. I believe this is a bona fide bug because memory usage suddenly exploding at a very old block is suspicious; if it was inherent to the protocol or the size of the full chain we'd see it at a network upgrade height or when the chain is fully synced -- here the `.zcash` directory is only 700MB large after the OOM-kill and it always happens at very old blocks.

5. @mdr0id pointed me at https://github.com/bitcoin-sv/bitcoin-sv/issues/112 which got me looking at https://github.com/bitcoin/bitcoin/issues/11822 and https://github.com/bitcoin/bitcoin/pull/11824; which might be somewhat related.

6. I ran an IBD with `valgrind --tool=massif ./repos/zcash/src/zcashd` with `while true; do vgdb --pid=17075 xtmemory; sleep 60;done` and `while true; do vgdb --pid=17075 detailed_snapshot snapshots/egg_$i;((i=i+1)); sleep 10;done` running in parallel to take periodic snapshots (because once the OOM-killer gets involved, the SIGKILL doesn't leave time for `valgrind` to write out the final output).

7. I popped the xtmemory files into callgrind; the massive memory increase seems to be from `AcceptBlockHeader` and `CBlockIndex`; i wonder if there's something that's causing those to be called more often than they should be (or if there's something that's causing those to not be deallocated):

Screen Shot 2022-05-08 at 15 51 16
Screen Shot 2022-05-08 at 15 50 42

8. i ran `free -m` (headers are `total    used    free   shared buff/cache  available`) in a loop every two seconds and this is what it looks like: the used memory is stable around 2 gigabytes and then immediately before the OOM-kill it balloons up:
Screen Shot 2022-05-05 at 17 32 27

 
### Do you have a backup of `~/.zcash` directory and/or take a VM snapshot?
Yes, though the OOM issue that is triggered when loading the `.zcash` directory is caused by leveldb and is *not* related to this.

### PR DESCRIPTION
**Pull request by daira**
The `nSolution` field of `CBlockIndex` holds a `std::vector<unsigned char>` containing a 1344-byte Equihash solution. In normal operation the node holds a linked tree of `CBlockIndex` nodes for the whole chain. Therefore, the total memory required for these `nSolution` fields for the current mainnet height 1834642, is at least $1834642 \cdot 1344$ bytes $\approx 2.3$ GiB.

It has to be possible to retrieve the `nSolution` field for any stored block in order to answer peer `getheaders` queries, for example. But once a block index entry has been flushed to leveldb (which happens asynchronously), it is no longer necessary to keep this field in memory, because it can be read back if needed. The cost of this should be small because of the caching done by leveldb.

This PR also adds the following Prometheus metrics:
* (counter) `zcashd.debug.memory.allocated_equihash_solutions` - the number of Equihash solutions that have ever been allocated;
* (counter) `zcashd.debug.memory.trimmed_equihash_solutions` - the number of Equihash solutions that were trimmed;
* (counter) `zcashd.debug.blocktree.trimmed_equihash_read_dbindex` - the number of times a block index entry needed to be reread to construct a block header because a solution had been trimmed;
* (counter) `zcashd.debug.blocktree.write_batch` - the number of block tree batch write operations (calls to `CBlockTreeDB::WriteBatchSync`);
* (counter) `zcashd.debug.blocktree.write_batch_read_dbindex` - the number of times a block index entry needed to be reread before being written during a block tree batch write operation.

These metrics are specific to zcashd; they are primarily intended for performance debugging of this feature and should not be considered stable. Note that in #6259 these metrics will be put behind the `-debugmetrics` flag.

fixes #5936

### CODE REVIEW

File: src/chain.h [hunk 1]
```diff
@@ -191,10 +191,10 @@ static const BlockStatus BLOCK_VALID_CONSENSUS = BLOCK_VALID_SCRIPTS;
  */
 class CBlockIndex
 {
-public:
-    //! pointer to the hash of the block, if any. Memory is owned by this CBlockIndex
-    const uint256* phashBlock;
+    //! The hash of the block, if it has been calculated
+    std::optional<uint256> optHashBlock;
```
Comment (str4d) [inline src/chain.h:195]: This is going to increase memory usage, because the block hash will be duplicated in memory and every `CBlockIndex` will now store 33 bytes instead of 8. For now this is only around 44 MiB so it's probably fine.

Separately, this is a deviation from upstream that we should think through.

Comment (daira) [reply src/chain.h:195]: I don't necessarily think we should do this change; it was just the simplest way to avoid memory handling issues when setting the hash from the block header.

**Comment by superbaud** [comment]
```
2022-10-05T00:15:00.068831Z  INFO Init: main: Opened LevelDB successfully
2022-10-05T00:15:00.068946Z  INFO Init: main: Opening LevelDB in /home/sasha_work/.zcash-testnet/testnet3/chainstate
2022-10-05T00:15:16.601905Z  INFO Init: main: Opened LevelDB successfully
2022-10-05T00:15:16.611602Z ERROR Init: main: LoadBlockIndex(): CheckProofOfWork failed: CBlockIndex(pprev=0x55f8ef571c10, nHeight=865648, merkle=b8e036628ba0f39fb2b44ef0cf784af72a5039d1b00cecd7656c48455ffe5e44, hashBlock=29875a309dd42baf44a78f5b71226417a7cb2f7d882421ec3e4b8491a053f086)
2022-10-05T00:15:16.811959Z  INFO Init: main: Aborted block database rebuild. Exiting.
2022-10-05T00:15:16.812572Z  INFO main: scheduler thread interrupt
2022-10-05T00:15:16.812696Z  INFO Shutdown: main: StopRPC: waiting for async rpc workers to stop
2022-10-05T00:15:16.812708Z  INFO main: metrics-ui thread interrupt
2022-10-05T00:15:16.813055Z  INFO Shutdown: main: StopNode()
2022-10-05T00:15:16.819153Z  INFO Shutdown: main: done
```
it immediately gives an error

File: src/chain.h (hunk 1 above)
Comment (daira) [reply src/chain.h:195]: This has been undone.

File: src/chain.cpp [hunk 2]
```diff
@@ -108,3 +108,23 @@ void CBlockIndex::BuildSkip()
     if (pprev)
         pskip = pprev->GetAncestor(GetSkipHeight(nHeight));
 }
+
+CBlockHeader CBlockIndex::GetBlockHeader() const
+{
+    CBlockHeader header;
+    if (nSolution.empty()) {
+        assert(ReadBlockHeaderFromDisk(header, GetBlockPos()));
```
Comment (daira) [inline src/chain.cpp:116]: TODO: better error handling.

File: src/txdb.cpp [hunk 3]
```diff
@@ -382,13 +382,13 @@ bool CCoinsViewDB::GetStats(CCoinsStats &stats) const {
     return true;
 }
 
-bool CBlockTreeDB::WriteBatchSync(const std::vector<std::pair<int, const CBlockFileInfo*> >& fileInfo, int nLastFile, const std::vector<const CBlockIndex*>& blockinfo) {
+bool CBlockTreeDB::WriteBatchSync(const std::vector<std::pair<int, const CBlockFileInfo*> >& fileInfo, int nLastFile, const std::vector<CBlockIndex*>& blockinfo) {
```
Comment (daira) [inline src/txdb.cpp:385]: There's probably a better way to do this.

**Comment by daira** [comment]
TODO:
* Check whether the thread safety fix using `cs_solutions` is correct, and whether it is needed.
* Try to avoid changing the type signature of `CBlockTreeDB::WriteBatchSync` (in principle it should be able to take `const std::vector<const CBlockIndex*>& blockinfo` since it doesn't change those `CBlockIndex`s).
* Fix the handling of errors in/from `ReadBlockHeaderFromDisk`.
* Are we clearing solutions from the right `CBlockIndex`s in the right place?
* Analyse whether the cost of reading headers back from disk is reasonable, and whether it could be a significant DoS vector.
* Do we need to cache solutions after they are cleared?

File: src/rpc/blockchain.cpp [hunk 4]
```diff
@@ -118,11 +118,13 @@ UniValue blockheaderToJSON(const CBlockIndex* blockindex)
     result.pushKV("finalsaplingroot", blockindex->hashFinalSaplingRoot.GetHex());
     result.pushKV("time", (int64_t)blockindex->nTime);
     result.pushKV("nonce", blockindex->nNonce.GetHex());
-    result.pushKV("solution", HexStr(blockindex->nSolution));
     result.pushKV("bits", strprintf("%08x", blockindex->nBits));
     result.pushKV("difficulty", GetDifficulty(blockindex));
     result.pushKV("chainwork", blockindex->nChainWork.GetHex());
 
+    CBlockHeader header = blockindex->GetBlockHeader();
+    result.pushKV("solution", HexStr(header.nSolution));
```
Comment (str4d) [inline src/rpc/blockchain.cpp:126]: Nit: this changes the order of the fields in the returned JSON, which is unnecessary.

File: src/chain.h [hunk 5]
```diff
@@ -564,20 +567,27 @@ class CDiskBlockIndex : public CBlockIndex
...
+        header.hashPrevBlock        = hashPrev;
+        header.hashMerkleRoot       = hashMerkleRoot;
+        header.hashBlockCommitments = hashBlockCommitments;
+        header.nTime                = nTime;
+        header.nBits                = nBits;
+        header.nNonce               = nNonce;
+        header.nSolution            = nSolution;
+        return header;
+    }
+
```
Comment (daira) [inline src/chain.h:584]: Override SetSolutionFrom to abort.

File: src/chain.cpp [hunk 6]
```diff
@@ -108,3 +110,31 @@ void CBlockIndex::BuildSkip()
     if (pprev)
         pskip = pprev->GetAncestor(GetSkipHeight(nHeight));
 }
+
+void CBlockIndex::ClearSolution()
```
Comment (daira) [inline src/chain.cpp:114]: Put these in the same order as in the header.

File: src/chain.cpp [hunk 7]
```diff
@@ -108,3 +110,31 @@ void CBlockIndex::BuildSkip()
...
+{
+    AssertLockHeld(cs_main);
+    nSolution.clear();
+    nSolution.shrink_to_fit();
+}
+
+CBlockHeader CBlockIndex::GetBlockHeader() const
```
Comment (str4d) [inline src/chain.cpp:121]: Move these above `InvertLowestOne` so the order of functions in this file roughly matches the order in the header.

File: src/chain.cpp [hunk 8]
```diff
@@ -108,3 +110,31 @@ void CBlockIndex::BuildSkip()
     if (pprev)
         pskip = pprev->GetAncestor(GetSkipHeight(nHeight));
 }
+
+void CBlockIndex::ClearSolution()
+{
+    AssertLockHeld(cs_main);
+    nSolution.clear();
+    nSolution.shrink_to_fit();
```
Comment (daira) [inline src/chain.cpp:118]:
```suggestion
    std::vector<unsigned char> empty;
    nSolution.swap(empty);
```

File: src/txdb.cpp (hunk 3 above)
Comment (daira) [reply src/txdb.cpp:385]: There isn't, unfortunately: https://stackoverflow.com/questions/19122858/why-is-a-vector-of-pointers-not-castable-to-a-const-vector-of-const-pointers

File: src/chain.h [hunk 9]
```diff
@@ -429,10 +430,12 @@ class CBlockIndex
 
     std::string ToString() const
     {
-        return strprintf("CBlockIndex(pprev=%p, nHeight=%d, merkle=%s, hashBlock=%s)",
+        return strprintf("CBlockIndex(pprev=%p, nHeight=%d, merkle=%s, hashBlock=%s, nSolution (%d bytes)=%s)",
```
Comment (str4d) [inline src/chain.h:433]:
```suggestion
        return strprintf("CBlockIndex(pprev=%p, nHeight=%d, merkle=%s, hashBlock=%s, nSolution=%s)",
```

File: src/chain.h [hunk 10]
```diff
@@ -429,10 +430,12 @@ class CBlockIndex
...
             pprev, nHeight,
             hashMerkleRoot.ToString(),
-            GetBlockHash().ToString());
+            phashBlock ? GetBlockHash().ToString() : "(nil)",
+            nSolution.size(),
+            HexStr(nSolution.begin(), nSolution.end()));
```
Comment (str4d) [inline src/chain.h:438]:
```suggestion
            HasSolution() ? HexStr(nSolution.begin(), nSolution.end())) : "(pruned)";
```

**Review by str4d — APPROVED** [review]
utACK 229746f01d1ded09109146c468d7cfc1fdc37ef3 modulo cleaning up the commits and addressing some minor comments.

**Comment by daira** [comment]
We want to change `IsWorthTrimming` to allow solutions to be trimmed earlier, to avoid the situation where there are lots of headers for blocks that haven't yet been validated. This will become especially important if #6231 (or a backport of bitcoin/bitcoin#10345) is merged.

File: src/chain.cpp [hunk 11]
```diff
@@ -58,6 +63,50 @@ const CBlockIndex *CChain::FindFork(const CBlockIndex *pindex) const {
     return pindex;
 }
 
+void CBlockIndex::ConsiderTrimming()
```
Comment (sellout) [inline src/chain.cpp:66]:
```suggestion
void CBlockIndex::TrimSolution()
```

File: src/txdb.cpp [hunk 12]
```diff
@@ -382,14 +384,31 @@ bool CCoinsViewDB::GetStats(CCoinsStats &stats) const {
...
     for (std::vector<std::pair<int, const CBlockFileInfo*> >::const_iterator it=fileInfo.begin(); it != fileInfo.end(); it++) {
         batch.Write(make_pair(DB_BLOCK_FILES, it->first), *it->second);
     }
     batch.Write(DB_LAST_BLOCK, nLastFile);
     for (std::vector<const CBlockIndex*>::const_iterator it=blockinfo.begin(); it != blockinfo.end(); it++) {
-        batch.Write(make_pair(DB_BLOCK_INDEX, (*it)->GetBlockHash()), CDiskBlockIndex(*it));
+        std::pair<char, uint256> key = make_pair(DB_BLOCK_INDEX, (*it)->GetBlockHash());
+        try {
+            CDiskBlockIndex dbindex {*it, [this, &key]() {
+                MetricsIncrementCounter("zcashd.blocktree_write_batch_read_dbindex");
```
Comment (str4d) [inline src/txdb.cpp:398]: Given that these are debug metrics that we don't want to support as part of the public interface, let's subgroup them so that we can (in a separate PR) add default-on filtering:
```suggestion
                MetricsIncrementCounter("zcashd.debug.blocktree.write_batch_read_dbindex");
```

File: src/txdb.h [hunk 13]
```diff
@@ -117,12 +117,13 @@ class CBlockTreeDB : public CDBWrapper
...
     void operator=(const CBlockTreeDB&);
 public:
-    bool WriteBatchSync(const std::vector<std::pair<int, const CBlockFileInfo*> >& fileInfo, int nLastFile, const std::vector<const CBlockIndex*>& blockinfo);
+    bool WriteBatchSync(const std::vector<std::pair<int, const CBlockFileInfo*> >& fileInfo, int nLastFile, const std::vector<CBlockIndex*>& blockinfo);
     bool EraseBatchSync(const std::vector<const CBlockIndex*>& blockinfo);
     bool ReadBlockFileInfo(int nFile, CBlockFileInfo &info);
     bool ReadLastBlockFile(int &nFile);
     bool WriteReindexing(bool fReindexing);
     bool ReadReindexing(bool &fReindexing);
+    bool ReadDiskBlockIndex(const uint256 &blockhash, CDiskBlockIndex &dbindex);
```
Comment (sellout) [inline src/txdb.h:126]: Check whether this member should be `const`.

**Review by sellout — CHANGES_REQUESTED** [review]
Reviewed with @str4d.

File: src/chain.h [hunk 14]
```diff
@@ -386,23 +395,15 @@ class CBlockIndex
...
-        block.nTime          = nTime;
-        block.nBits          = nBits;
-        block.nNonce         = nNonce;
-        block.nSolution      = nSolution;
-        return block;
-    }
+    //! Get the block header for this block index. Requires cs_main.
+    CBlockHeader GetBlockHeader() const;
+
+    //! Clear the Equihash solution to save memory, if it is beneficial. Requires cs_main.
```
Comment (sellout) [inline src/chain.h:401]:
```suggestion
    //! Clear the Equihash solution to save memory. Requires cs_main.
```

**Review by sellout — APPROVED** [review]
Just one comment suggestion.

File: src/chain.h [hunk 15]
```diff
@@ -429,10 +430,11 @@ class CBlockIndex
 
     std::string ToString() const
     {
-        return strprintf("CBlockIndex(pprev=%p, nHeight=%d, merkle=%s, hashBlock=%s)",
+        return strprintf("CBlockIndex(pprev=%p, nHeight=%d, merkle=%s, hashBlock=%s, nSolution=%s)",
```
Comment (str4d) [inline src/chain.h:433]: Nit: we weren't printing the solution previously here because it is very large, and not actually useful outside the header (vs the other values that are useful in the context of other block-related debug output).

File: src/txdb.cpp [hunk 16]
```diff
@@ -599,7 +622,8 @@ bool CBlockTreeDB::LoadBlockIndexGuts(
                 pindexNew->nTime          = diskindex.nTime;
                 pindexNew->nBits          = diskindex.nBits;
                 pindexNew->nNonce         = diskindex.nNonce;
-                pindexNew->nSolution      = diskindex.nSolution;
+                // the Equihash solution will be loaded lazily from the dbindex entry
+                MetricsIncrementCounter("zcashd.debug.memory.trimmed_equihash_solutions");
```
Comment (str4d) [inline src/txdb.cpp:626]: Hmm, isn't this going to count a "trim" without a corresponding "allocate" (the latter only occuring when a `CBlockIndex` is created from a `CBlockHeader`)? That makes `allocate - trim` incorrect as a measure of in-memory Equihash solutions. I think this should be removed:
```suggestion
```

**Review by str4d — APPROVED** [review]
utACK 82dd2495248a7fb51da08a8a80bf03855aae6c0d with question about metrics (which is non-blocking as they are for debugging purposes).

File: src/chain.h (hunk 15 above)
Comment (daira) [reply src/chain.h:433]: What do you think about changing this to just print the result of `HasSolution()`?

File: src/txdb.cpp (hunk 16 above)
Comment (daira) [reply src/txdb.cpp:626]: Oh I think you're right. I will check and remove this if you are.

File: src/chain.h (hunk 15 above)
Comment (str4d) [reply src/chain.h:433]: Yeah, that works fine.

File: src/chain.h [hunk 17]
```diff
@@ -429,10 +430,11 @@ class CBlockIndex
 
     std::string ToString() const
     {
-        return strprintf("CBlockIndex(pprev=%p, nHeight=%d, merkle=%s, hashBlock=%s)",
+        return strprintf("CBlockIndex(pprev=%p, nHeight=%d, merkle=%s, hashBlock=%s, HasSolution=%s)",
             pprev, nHeight,
             hashMerkleRoot.ToString(),
-            GetBlockHash().ToString());
+            phashBlock ? GetBlockHash().ToString() : "(nil)",
+            HasSolution());
```
Comment (daira) [inline src/chain.h:437]: Note that tinyformat correctly prints "true" or "false" for `%s` when passed a boolean: https://github.com/zcash/zcash/blob/27ffefed1291f1474e15149e6992653d1c3669ee/src/tinyformat.h#L737-L742

**Comment by daira** [comment]
Ready for re-review; changes in https://github.com/zcash/zcash/compare/82dd2495248a7fb51da08a8a80bf03855aae6c0d..fb66589022df4a0eff6ff244aa6b713c3a2bb2dd

**Review by sellout — APPROVED** [review]
utACK

**Review by str4d — APPROVED** [review]
re-utACK fb66589022df4a0eff6ff244aa6b713c3a2bb2dd.
