### PR TITLE
libzcash and new zkSNARK circuit implementation

### LINKED ISSUE #128: Redesign a cleaner separation between ``zcash`` and ``libzerocash``.
We've seen a few cases which feel like abstraction-boundary-crossing between ``zerocashd`` and ``libzerocash``, including:

* ``libzerocash`` types implement bitcoin serialization. This is a circular dependency. (A hacky work-around to implement this includes that the upstream ``serialize.h`` is [copied into ``libzerocash``](https://github.com/Electric-Coin-Company/libzerocash/blob/master/libzerocash/serialize.h).)
* [``CWallet::MakePour``](https://github.com/Electric-Coin-Company/zerocashd/blob/zc.v0.10.0.ticket123.rebase.0/src/wallet.cpp#L1133) *seems to me* to require too much knowledge of Pour construction. Can we push more of that logic into ``libzerocash`` and have ``CWallet::MakePour`` more about serialization and fetching appropriate bits for merkle tree reads/updates?

Let's collect more examples in this ticket for a refactor of the boundary.

(Note: I'm not yet certain the second bullet is a sensible proposal, it's just a hunch for now.)

### LINKED ISSUE #247: Make the Pour creation implementation map more directly to the Zerocash paper.
This may interact with #68 as well as altering the interface to libzerocash.

Currently, for #227, @daira and I are diagnosing a malformed signature for Pours in [``MakePourTx``](https://github.com/Electric-Coin-Company/zerocashd/blob/zc.v0.10.0.latest/src/wallet.cpp#L1171). While trying to understand the purpose of this signature, we cracked open the Zerocash extended paper and reviewed the Pour algorithm specified in Fig 2.

We wished that there were a single function that implements each of the steps in the Fig 2. algorithm, with little extraneous code, so that we could verify the implementation is following the paper.  Currently, the signature linked to above is using Bitcoin's convoluted signature hashing system, and so we're not certain it corresponds to the steps in the Figure.

A low hanging fruit here is to avoid Bitcoin's convoluted signature scheme altogether and to use libsecp256k1 directly for the Pour signature.

### LINKED ISSUE #315: libzerocash<->libsnark interface cleanup: the input coin parameters to a pour proof should be expressed as structs
Currently, the interface uses separate 2-element vectors for each parameter, rather than a vector of all the parameters needed for an input coin.

### LINKED ISSUE #500: Implement new PRF layouts that don't truncate hash outputs
All PRFs are constructed from the SHA256 compression function by, in some cases, truncating one of the input arguments, and using those bits to differentiate the PRFs. This might create a vulnerability (or proof failure), where for example when 3 bits are used to differentiate the PRFs, there will always be 8 input values that will produce the same result. If the security proof ever relies on a variable being the *unique* known input that would satisfy the PRF, then the security proof fails for the implementation.

One possible solution is make sure that all PRF input variables are truncated the same way every time they are used (or, better, never generate/keep those truncated bits in the first place).

### LINKED ISSUE #512: Convert all libzerocash boolean return values into exceptions
For example, there's a few boolean-returning functions in IncrementalMerkleTree.

From #493.

### LINKED ISSUE #514: Fix zerocashTest to meaningfully check the work it's doing
zerocashTest does a lot of stuff, but most of it is just printing things to stdout and can't make the test actually fail. Add `BOOST_REQUIRE`s to make it actually check things.

From #493.

### LINKED ISSUE #707: Clean up PourTransaction.cpp by having a function called "PRF"
This would make the code infinitely more understandable.

### LINKED ISSUE #798: Remove redundancy in PourTransaction
PourTransaction has a completely terrible API and implementation that duplicates all the code just because there happen to be two inputs and two outputs. Please fix it, it is hurting my eyes (and is really error-prone, unnecessarily difficult to review, and bad for maintenance).

### LINKED ISSUE #809: Implement Faerie Gold Fix.
Implement (or ensure our code addresses) the fix specified in #98.

### LINKED ISSUE #822: No bitness constraints on merkle authentication path
Boolean (or "bitness") constraints are used to enforce that variables in the arithmetic circuit are either zero or one. Some gadgets operate over variables assuming they have bitness, because if they didn't have bitness it would be very dangerous. (You could essentially short-circuit hash evaluations, though I'm not sure how difficult it would be to accomplish.)

In our circuit, `old_coin_authentication_path_variables` is used to store the digests on the left or the right of the tree as you ascend the authentication path to the root. It is used by the `merkle_tree_check_read_gadget`. It's important that it is boolean constrained as this [note suggests explicitly](https://github.com/scipr-lab/libsnark/blob/master/src/gadgetlib1/gadgets/merkle_tree/merkle_tree_check_read_gadget.tcc#L85).

However, we're not constraining it, just witnessing it. (Try looking for `old_coin_authentication_path_variables` in our [circuit code](https://github.com/zcash/zcash/blob/zc.v0.11.2.latest/src/zerocash/zerocash_pour_gadget.tcc) and finding a `generate_r1cs_constraints` method call.)

### LINKED ISSUE #824: Reduce redundancy in JoinSplit gadget implementation
https://github.com/zcash/zcash/blob/zc.v0.11.2.latest/src/zerocash/zerocash_pour_gadget.tcc

A substantial proportion of the code in this file seems like it should not need to exist. For example: the code in ``zerocash_pour_input_map`` has to match that after ``/* do the multipacking */`` on line 61. Why is this done in two places? If they didn't match then there might be a security bug.

### LINKED ISSUE #854: JoinSplit sum of values should be enforced to be in [0, 2^64-1]
Nothing in [zerocash_pour_gadget.tcc](https://github.com/zcash/zcash/blob/zc.v0.11.2.z1/src/zerocash/zerocash_pour_gadget.tcc) checks that the values of the input and output notes are in [0, ``MAX_MONEY``]. This has to be checked in the circuit, because the values are private. (``vpub_old`` and ``vpub_new`` are checked outside the circuit, in the ``CheckTransaction`` function of ``main.cpp``.)

See #853 for a related issue in the Zerocash paper, and https://github.com/zcash/zips/issues/41 for one in the Zcash protocol spec.

### LINKED ISSUE #877: Delete MintTransaction and related tests
https://github.com/zcash/zcash/blob/zc.v0.11.2.z2/src/zerocash/MintTransaction.cpp

### PR DESCRIPTION
**Pull request by ebfull**
This PR completes [`libzcash`](https://github.com/zcash/zcash/tree/zc.v0.11.2.latest/src/zcash), the implementation of the [Zcash protocol specification](https://github.com/zcash/zips/blob/9bb4410e45394c8b7e43e35622f54dd4041a4ddd/protocol/protocol.pdf) and replacement of [`libzerocash`](https://github.com/Zerocash/libzerocash), our old Zerocash protocol implementation. The new spec comes with some improvements to security and terminology, with minimal differences from the original academic design.

This implementation includes:

* A rewrite of the zkSNARK circuit for `JoinSplit` operations. This rewrite is cleaner, broken up into separate gadgets, easier to audit and review, and fixes some security bugs. (Closes #822, Closes #809, Closes #500, Closes #854)
* A minimal API for interacting with `JoinSplit`s and surrounding primitives. This PR removes almost twice as much code as it introduces. (Closes #877, Closes #315, Closes #824, Closes #798, Closes #707, Closes #512, Closes #247, Closes #128, Closes #514)

### CODE REVIEW

**Comment by ebfull** [comment]
I had to rebase this PR because github showed the commits in chronological order, which is incredibly misleading in PRs like this one where the ordering has extremely important semantic value. Should be fixed now though.

**Comment by ebfull** [comment]
@defuse Can you upload `https://z.cash/downloads/z3-proving.key` to S3? (I've already uploaded the verification key.) I'll redirect it to `https://s3.amazonaws.com/zcashalpha/zc3-proving.key` when you've finished.

**Comment by ebfull** [comment]
@defuse Never mind! They're uploaded now.

**Comment by ebfull** [comment]
@zkbot try

File: src/gtest/test_merkletree.cpp [hunk 1]
```diff
@@ -40,11 +40,15 @@ read_json(const std::string& jsondata)
 }
 
 #include "zcash/IncrementalMerkleTree.hpp"
-#include "zerocash/IncrementalMerkleTree.h"
 #include "zerocash/utils/util.h"
 
 //#define PRINT_JSON 1
 
+#include "libsnark/common/default_types/r1cs_ppzksnark_pp.hpp"
```
Comment (ebfull) [inline src/gtest/test_merkletree.cpp]: These includes are redundant in the file.

File: src/primitives/transaction.cpp [hunk 2]
```diff
@@ -9,84 +9,56 @@
...
-
-    boost::array<std::vector<unsigned char>, NUM_POUR_INPUTS> serials_bv;
-    boost::array<std::vector<unsigned char>, NUM_POUR_OUTPUTS> commitments_bv;
-    boost::array<std::vector<unsigned char>, NUM_POUR_INPUTS> macs_bv;
-
-    proof = pourtx.unpack(serials_bv, commitments_bv, macs_bv, ciphertexts, ephemeralKey);
-    serials = unsigned_char_vector_array_to_uint256_array(serials_bv);
-    commitments = unsigned_char_vector_array_to_uint256_array(commitments_bv);
-    macs = unsigned_char_vector_array_to_uint256_array(macs_bv);
+    boost::array<libzcash::Note, ZC_NUM_JS_OUTPUTS> notes;
```
Comment (ebfull) [inline src/primitives/transaction.cpp]: This isn't used currently, but in the future this will be used to give the notes to the caller of the constructor. This is especially necessary because the ordering of the outputs will change if we enforce #778.

File: src/test/coins_tests.cpp [hunk 3]
```diff
@@ -166,10 +166,12 @@ BOOST_AUTO_TEST_CASE(serials_test)
...
 {
-    Address addr = Address::CreateNewRandomAddress();
-    Coin coin(addr.getPublicAddress(), 100);
+    libzcash::SpendingKey k = libzcash::SpendingKey::random();
+    libzcash::PaymentAddress addr = k.address();
 
-    tree.append(uint256(coin.getCoinCommitment().getCommitmentValue()));
+    libzcash::Note note(addr.a_pk, 0, uint256(), uint256());
+
+    tree.append(note.cm());
```
Comment (ebfull) [inline src/test/coins_tests.cpp]: It isn't really necessary, at least the way the tests are currently written, for this to be a valid note commitment at all, and it might be better to just append a random 256-bit digest to the tree here instead.

File: src/zcash/JoinSplit.cpp [hunk 4]
```diff
@@ -0,0 +1,345 @@
...
+                );
+            }
+
+            if (!pb.is_satisfied()) {
+                throw std::invalid_argument("Constraint system not satisfied by inputs");
+            }
+
+            primary_input = pb.primary_input();
+            aux_input = pb.auxiliary_input();
+        }
```
Comment (ebfull) [inline src/zcash/JoinSplit.cpp]: These above lines are in structured blocks because the gadget isn't needed after the constraint system is realized, at least with the current design of the libsnark API, and the protoboard isn't needed once the input witnesses are realized. This should save us some memory; not sure how much.

Ultimately, I want to reuse the constraint system and input witnesses for the prover, because currently the proving key contains a copy of the constraint system. This is a limitation of the libsnark API that we should focus on closer to launch.

**Comment by ebfull** [comment]
@zkbot force

**Comment by ebfull** [comment]
@zkbot try

**Comment by ebfull** [comment]
Comparison between the old and the new circuit:

old:
```
  * QAP number of variables: 1477804
  * QAP pre degree: 1594979
  * QAP degree: 2097152
  * QAP number of input variables: 9
```

new:
```
  * QAP number of variables: 1426992
  * QAP pre degree: 1566328
  * QAP degree: 1572864
  * QAP number of input variables: 9
```

The old circuit had 3 hashes per note. The new circuit has two, but the output notes have additional hashes to fix faerie gold. This means the circuit should be approximately "two hashes" smaller. However, we also add bitness constraints that were previously unenforced, in addition to some "precautionary" bitness constraints which may not be necessary.

Notice that the resulting QAP degree is much smaller because less "dummy constraints" need to be added to satisfy the linear independence property at this particular depth. We may not be so lucky at higher depths.

**Comment by ebfull** [comment]
[The performance results are in.](http://ci.leastauthority.com:8010/builders/zcashperformance/builds/22)

**Comment by ebfull** [comment]
I'm splitting out internal mock circuit tests into #920 because we need to be confident in the approach and implementation, and know for certain that it does not interfere with the constraint system, which may require extra auditing.

**Comment by ebfull** [comment]
Hopefully, accidentally closing the PR didn't disturb zkbot.

@zkbot try

**Comment by ebfull** [comment]
@zkbot try

File: src/zcash/Address.hpp [hunk 5]
```diff
@@ -0,0 +1,46 @@
...
+    uint256 pk_enc;
+
+    PaymentAddress() : a_pk(), pk_enc() { }
+    PaymentAddress(uint256 a_pk, uint256 pk_enc) : a_pk(a_pk), pk_enc(pk_enc) { }
+
+    ADD_SERIALIZE_METHODS;
+
+    template <typename Stream, typename Operation>
+    inline void SerializationOp(Stream& s, Operation ser_action, int nType, int nVersion) {
+        READWRITE(a_pk);
```
Comment (ebfull) [inline src/zcash/Address.hpp]: I'll add the leading byte (0x92) here even though this PR isn't really addressing #572 yet.

File: src/zcash/JoinSplit.cpp [hunk 6]
```diff
@@ -0,0 +1,340 @@
...
+uint256 JoinSplit<NumInputs, NumOutputs>::h_sig(
+    const uint256& randomSeed,
+    const boost::array<uint256, NumInputs>& nullifiers,
+    const uint256& pubKeyHash
+) {
+    unsigned char personalization[crypto_generichash_blake2b_PERSONALBYTES]
+        = {'Z','c','a','s','h','C','o','m','p','u','t','e','h','S','i','g'};
+
+    std::vector<unsigned char> block;
+    block.insert(block.end(), randomSeed.begin(), randomSeed.end());
```
Comment (ebfull) [inline src/zcash/JoinSplit.cpp]: I'll combine these two lines.

File: src/zcash/Note.cpp [hunk 7]
```diff
@@ -0,0 +1,90 @@
...
+                                     const uint256& ephemeralKey,
+                                     const uint256& h_sig,
+                                     unsigned char nonce
+                                    )
+{
+    auto plaintext = decryptor.decrypt(ciphertext, ephemeralKey, h_sig, nonce);
+
+    CDataStream ss(SER_NETWORK, PROTOCOL_VERSION);
+    ss << plaintext;
+
```
Comment (ebfull) [inline src/zcash/Note.cpp]: I'll add an additional assertion here that `ss.size() == sizeof(NotePlaintext)`; this is locally guaranteed (not input dependent) already, but we should guard ourselves against serialization bugs.

File: src/zcash/Note.hpp [hunk 8]
```diff
@@ -0,0 +1,83 @@
...
+    Note(uint256 a_pk, uint64_t value, uint256 rho, uint256 r)
+        : a_pk(a_pk), value(value), rho(rho), r(r) {}
+
+    Note();
+
+    ADD_SERIALIZE_METHODS;
+
+    template <typename Stream, typename Operation>
+    inline void SerializationOp(Stream& s, Operation ser_action, int nType, int nVersion) {
+        READWRITE(a_pk);
```
Comment (ebfull) [inline src/zcash/Note.hpp]: I don't think `Note` ever really needs to be serialized, just `NotePlaintext`, so I will remove this.

File: src/zcash/Note.cpp (hunk 7 above)
Comment (ebfull) [inline src/zcash/Note.cpp]: Actually, oops! I didn't put an assertion here because it's not necessary. We'll trigger an exception.

File: src/gtest/test_joinsplit.cpp [hunk 9]
```diff
@@ -0,0 +1,213 @@
...
+            ciphertexts,
+            ephemeralKey,
+            pubKeyHash,
+            randomSeed,
+            hmacs,
+            nullifiers,
+            commitments,
+            vpub_old,
+            vpub_new,
+            rt
```
Comment (daira) [inline src/gtest/test_joinsplit.cpp]: I think I've mentioned this before, but it would be much clearer if the output parameters were prefixed with ``out_``.

File: src/gtest/test_joinsplit.cpp [hunk 10]
```diff
@@ -0,0 +1,213 @@
...
+
+    // Insert the commitments from the last tx into the tree
+    tree.append(commitments[0]);
+    auto witness_recipient = tree.witness();
+    tree.append(commitments[1]);
+    witness_recipient.append(commitments[1]);
+    vpub_old = 0;
+    vpub_new = 1;
+    rt = tree.root();
+    pubKeyHash = random_uint256();
```
Comment (daira) [inline src/gtest/test_joinsplit.cpp]: Because the variables are being reused from above, it's a little tricky to see that all and only the right ones are reinitialized here.

File: src/gtest/test_joinsplit.cpp [hunk 11]
```diff
@@ -0,0 +1,213 @@
...
+    js->preloadProvingKey("./zcashTest.pk");
+    js->loadProvingKey();
+    js->loadVerifyingKey("./zcashTest.vk");
+
+    test_full_api(js);
+
+    delete js;
+}
+
+TEST(joinsplit, note_plaintexts)
```
Comment (daira) [inline src/gtest/test_joinsplit.cpp]: At first I thought this was redundant with ``TEST(noteencryption, api)`` in ``test_noteencryption.cpp``, but it isn't because it's testing ``Note``'s API as well. Maybe add cross-referencing comments so that people looking at one of these tests can find the other.

File: src/gtest/test_noteencryption.cpp [hunk 12]
```diff
@@ -3,8 +3,11 @@
 
 #include <stdexcept>
 
+#include "crypto/sha256.h"
+
 #include "zcash/NoteEncryption.hpp"
 #include "zcash/prf.h"
+#include "crypto/sha256.h"
```
Comment (daira) [inline src/gtest/test_noteencryption.cpp]: Why is this included twice?

Comment (ebfull) [inline src/gtest/test_noteencryption.cpp]: Nice catch.

File: src/gtest/test_noteencryption.cpp [hunk 13]
```diff
@@ -28,8 +31,8 @@ TEST(noteencryption, api)
         ASSERT_TRUE(b.get_epk() != c.get_epk());
     }
 
-    boost::array<unsigned char, 216> message;
-    for (unsigned char i = 0; i < 216; i++) {
+    boost::array<unsigned char, 201> message;
+    for (unsigned char i = 0; i < 201; i++) {
```
Comment (daira) [inline src/gtest/test_noteencryption.cpp]: ``i < boost::size(message)``, to avoid the redundancy?

File: src/main.cpp [hunk 14]
```diff
@@ -960,7 +960,10 @@ bool CheckTransaction(const CTransaction& tx, CValidationState &state)
 
         if (state.PerformPourVerification()) {
             BOOST_FOREACH(const CPourTx &pour, tx.vpour) {
```
Comment (daira) [inline src/main.cpp]: I assume renaming this will be a separate pull request. ref #602

File: src/primitives/transaction.cpp [hunk 15]
```diff
@@ -9,84 +9,56 @@
...
-        scriptPubKeyHash = ss.GetHash();
-    }
-
-    return PourProver::VerifyProof(
-        params,
-        std::vector<unsigned char>(scriptPubKeyHash.begin(), scriptPubKeyHash.end()),
-        std::vector<unsigned char>(anchor.begin(), anchor.end()),
+bool CPourTx::Verify(
+    ZCJoinSplit& params,
+    const uint256& pubKeyHash
```
Comment (daira) [inline src/primitives/transaction.cpp]: I was initially confused as to why the ``pubKeyHash`` is passed in here, but it's because we changed the design so that ``pubKeyHash`` is associated with the transaction, not the JoinSplit. Maybe add a comment.

File: src/primitives/transaction.cpp [hunk 16]
```diff
@@ -9,84 +9,56 @@
...
+        ciphertexts,
+        ephemeralKey,
+        pubKeyHash,
+        randomSeed,
+        macs,
+        serials,
+        commitments,
+        vpub_old,
+        vpub_new,
+        anchor
```
Comment (daira) [inline src/primitives/transaction.cpp]: It might be nicer for these to be in the same order they're encoded in a JoinSplit description, i.e.
(inputs, outputs, vpub_old, vpub_new, anchor, serials/nullifiers, commitments, ephemeralKey, ciphertexts, randomSeed, macs).

File: src/primitives/transaction.h [hunk 17]
```diff
@@ -50,60 +35,65 @@ class CPourTx
...
     template <typename Stream, typename Operation>
     inline void SerializationOp(Stream& s, Operation ser_action, int nType, int nVersion) {
         READWRITE(vpub_old);
         READWRITE(vpub_new);
-        READWRITE(scriptPubKey);
-        READWRITE(scriptSig);
         READWRITE(anchor);
         READWRITE(serials);
         READWRITE(commitments);
         READWRITE(ciphertexts);
```
Comment (daira) [inline src/primitives/transaction.h]: The spec has commitments and ciphertexts the other way around. (It also calls ciphertexts ``encCiphertexts``, since we might add more kinds of ciphertext in future.)

File: src/primitives/transaction.h [hunk 18]
```diff
@@ -113,13 +103,12 @@ class CPourTx
         return (
             a.vpub_old == b.vpub_old &&
             a.vpub_new == b.vpub_new &&
-            a.scriptPubKey == b.scriptPubKey &&
-            a.scriptSig == b.scriptSig &&
             a.anchor == b.anchor &&
             a.serials == b.serials &&
             a.commitments == b.commitments &&
             a.ciphertexts == b.ciphertexts &&
```
Comment (daira) [inline src/primitives/transaction.h]: Also swap commitments and ciphertexts here for consistency, even though it doesn't matter logically.

File: src/wallet/rpcwallet.cpp [hunk 19]
```diff
@@ -2454,67 +2456,72 @@ Value zc_raw_receive(const json_spirit::Array& params, bool fHelp)
 
     LOCK(cs_main);
```
Comment (daira) [inline src/wallet/rpcwallet.cpp]: (Independent of this PR.) We can reduce the scope of the lock, I think.

File: src/wallet/rpcwallet.cpp [hunk 20]
```diff
@@ -2563,99 +2570,97 @@ Value zc_raw_pour(const json_spirit::Array& params, bool fHelp)
     if (params[4].get_real() != 0.0)
         vpub_new = AmountFromValue(params[4]);
```
Comment (daira) [inline src/wallet/rpcwallet.cpp]: When we redesign the RPC interface, let's make sure that amounts are in zatoshi, not ZEC. (The protocol should not even really know about ZEC at all.)

File: src/wallet/rpcwallet.cpp [hunk 21]
```diff
@@ -2454,67 +2456,72 @@ Value zc_raw_receive(const json_spirit::Array& params, bool fHelp)
...
+        anchor
+    );
 
     CDataStream ss(SER_NETWORK, PROTOCOL_VERSION);
-    {
-        ss << decrypted_bucket.getValue();
-        ss << decrypted_bucket.getRho();
-        ss << decrypted_bucket.getR();
-    }
+    ss << npt;
```
Comment (daira) [inline src/wallet/rpcwallet.cpp]: I am liking how the NotePlaintext abstraction simplifies things (not just here).

File: src/wallet/rpcwallet.cpp [hunk 22]
```diff
@@ -2681,6 +2687,7 @@ Value zc_raw_pour(const json_spirit::Array& params, bool fHelp)
         ss2 << ((unsigned char) 0x01);
         ss2 << pourtx.ephemeralKey;
         ss2 << pourtx.ciphertexts[1];
+        ss2 << pourtx.h_sig(*pzcashParams, pubKeyHash);
 
         encryptedBucket2 = HexStr(ss2.begin(), ss2.end());
     }
```
Comment (daira) [inline src/wallet/rpcwallet.cpp]: This code should be deduplicated.

File: src/wallet/rpcwallet.cpp [hunk 23]
```diff
@@ -2711,22 +2718,25 @@ Value zc_raw_keygen(const json_spirit::Array& params, bool fHelp)
...
     std::string pub_hex = HexStr(pub.begin(), pub.end());
     std::string priv_hex = HexStr(priv.begin(), priv.end());
+    std::string viewing_hex = HexStr(viewing.begin(), viewing.end());
 
     Object result;
     result.push_back(Pair("zcaddress", pub_hex));
     result.push_back(Pair("zcsecretkey", priv_hex));
+    result.push_back(Pair("zcviewingkey", viewing_hex));
     return result;
 }
```
Comment (daira) [inline src/wallet/rpcwallet.cpp]: Wow this PR is huge. Up to here so far.

File: src/zcash/Address.hpp [hunk 24]
```diff
@@ -0,0 +1,53 @@
...
+
+    ADD_SERIALIZE_METHODS;
+
+    template <typename Stream, typename Operation>
+    inline void SerializationOp(Stream& s, Operation ser_action, int nType, int nVersion) {
+        unsigned char leadingByte = 0x92;
+        READWRITE(leadingByte);
+
+        if (leadingByte != 0x92) {
+            throw std::ios_base::failure("unrecognized payment address version");
```
Comment (daira) [inline src/zcash/Address.hpp]: "unrecognized payment address lead byte" (it may not be a version as such; there may be different kinds of key with different features).

File: src/zcash/Address.cpp [hunk 25]
```diff
@@ -0,0 +1,23 @@
...
+
+SpendingKey SpendingKey::random() {
+    return SpendingKey(random_uint256());
+}
+
+PaymentAddress SpendingKey::address() {
+    return PaymentAddress(PRF_addr_a_pk(*this), viewing_key().pk_enc());
+}
+
+}
```
Comment (daira) [inline src/zcash/Address.cpp]: Do we prefer files to end with a newline?

File: src/zcash/GenerateParams.cpp [hunk 26]
```diff
@@ -0,0 +1,21 @@
+#include "zcash/JoinSplit.hpp"
+
+#include <iostream>
+
+int main(int argc, char **argv)
+{
+    if(argc != 3) {
```
Comment (daira) [inline src/zcash/GenerateParams.cpp]: Nitpick: ``if (``

File: src/zcash/GenerateParams.cpp [hunk 27]
```diff
@@ -0,0 +1,21 @@
+#include "zcash/JoinSplit.hpp"
+
+#include <iostream>
+
+int main(int argc, char **argv)
+{
```
Comment (daira) [inline src/zcash/GenerateParams.cpp]: Maybe print a warning that this is not secure for generating production parameters. (There's no way to prove that you didn't keep a backdoor.)

File: src/zcash/JoinSplit.cpp [hunk 28]
```diff
@@ -0,0 +1,344 @@
...
+    boost::optional<r1cs_ppzksnark_verification_key<ppzksnark_ppT>> vk;
+    boost::optional<std::string> pkPath;
+
+    static void initialize() {
+        LOCK(cs_InitializeParams);
+
+        ppzksnark_ppT::init_public_params();
+    }
+
+    void preloadProvingKey(std::string path) {
```
Comment (daira) [inline src/zcash/JoinSplit.cpp]: Should this instead be called something like ``setProvingKeyPath``?

File: src/zcash/JoinSplit.cpp [hunk 29]
```diff
@@ -0,0 +1,344 @@
...
+        // Compute nullifiers of inputs
+        for (size_t i = 0; i < NumInputs; i++) {
+            nullifiers[i] = inputs[i].nullifier();
+        }
+
+        // Sample randomSeed
+        randomSeed = random_uint256();
+
+        // Compute h_sig
+        uint256 h_sig = this->h_sig(randomSeed, nullifiers, pubKeyHash);
```
Comment (daira) [inline src/zcash/JoinSplit.cpp]: Where is ``pubKeyHash`` computed? I don't see the string "ZcashECDSAPubKey" (or equivalent character array) anywhere.

File: src/zcash/JoinSplit.cpp [hunk 30]
```diff
@@ -0,0 +1,344 @@
...
+        uint64_t vpub_old,
+        uint64_t vpub_new,
+        const uint256& rt
+    ) {
+        if (!pk) {
+            throw std::runtime_error("JoinSplit proving key not loaded");
+        }
+
+        // Compute nullifiers of inputs
+        for (size_t i = 0; i < NumInputs; i++) {
```
Comment (daira) [inline src/zcash/JoinSplit.cpp]: Should we use ``i0`` consistently for zero-based input/output indices?

File: src/zcash/JoinSplit.cpp [hunk 31]
```diff
@@ -0,0 +1,344 @@
...
+        auto proof = r1cs_ppzksnark_prover<ppzksnark_ppT>(
+            *pk,
+            primary_input,
+            aux_input
+        );
+
+        std::stringstream ss;
+        ss << proof;
+
+        return ss.str();
```
Comment (daira) [inline src/zcash/JoinSplit.cpp]: Maybe assert that the proof is the expected length?

Also, ``std::stringstream`` and ``std::string`` apparently do allow embedded zero bytes, but that isn't obvious so maybe these are not the ideal types to use.

File: src/zcash/JoinSplit.cpp [hunk 32]
```diff
@@ -0,0 +1,344 @@
...
+    addr = a_sk.address();
+}
+
+JSInput::JSInput() : witness(ZCIncrementalMerkleTree().witness()),
+                     key(random_uint256()) {
+    note = Note(key.address().a_pk, 0, random_uint256(), random_uint256());
+    ZCIncrementalMerkleTree dummy_tree;
+    dummy_tree.append(note.cm());
+    witness = dummy_tree.witness();
+}
```
Comment (daira) [inline src/zcash/JoinSplit.cpp]: Hmm, where are the constructors that take arguments defined?

Comment (daira) [inline src/zcash/JoinSplit.cpp]: Oh, in the header. (For some reason my search wasn't finding them there.) Never mind.

File: src/zcash/Note.cpp (hunk 7 above)
Comment (daira) [inline src/zcash/Note.cpp]: Does this still trigger an exception if the contents of ``ss`` is longer than expected?

File: src/zcash/Note.cpp [hunk 33]
```diff
@@ -0,0 +1,90 @@
...
+                                                   ) const
+{
+    CDataStream ss(SER_NETWORK, PROTOCOL_VERSION);
+    ss << (*this);
+
+    ZCNoteEncryption::Plaintext pt;
+
+    assert(pt.size() == ss.size());
+
+    memcpy(&pt[0], &ss[0], pt.size());
```
Comment (daira) [inline src/zcash/Note.cpp]: This seems surprisingly low-level, is there not a method or constructor for this?

File: src/zcash/Note.hpp [hunk 34]
```diff
@@ -0,0 +1,73 @@
...
+
+    ADD_SERIALIZE_METHODS;
+
+    template <typename Stream, typename Operation>
+    inline void SerializationOp(Stream& s, Operation ser_action, int nType, int nVersion) {
+        unsigned char leadingByte = 0x00;
+        READWRITE(leadingByte);
+
+        if (leadingByte != 0x00) {
+            throw std::ios_base::failure("version of NotePlaintext is invalid");
```
Comment (daira) [inline src/zcash/Note.hpp]: "lead byte of NotePlaintext is not recognized"

File: src/zcash/Zcash.h [hunk 35]
```diff
@@ -0,0 +1,18 @@
...
+#define _ZCCONSTANTS_H_
+
+#define ZC_NUM_JS_INPUTS 2
+#define ZC_NUM_JS_OUTPUTS 2
+#define INCREMENTAL_MERKLE_TREE_DEPTH 20
+#define INCREMENTAL_MERKLE_TREE_DEPTH_TESTING 4
+
+// TODO: these constants should be 'ZC'
+// for consistency, but I didn't want to
+// interfere with the old constants
```
Comment (daira) [inline src/zcash/Zcash.h]: Do we intend to rename them later?

File: src/zcash/Zcash.h [hunk 36]
```diff
@@ -0,0 +1,18 @@
...
+#define ZCASH_NOTEPLAINTEXT_LEADING 1
+#define ZCASH_V_SIZE 8
+#define ZCASH_RHO_SIZE 32
+#define ZCASH_R_SIZE 32
+#define ZCASH_MEMO_SIZE 128
+
+#endif // _ZCCONSTANTS_H_
```
Comment (daira) [inline src/zcash/Zcash.h]: I got up to here, packing in for the night.

File: src/zcash/JoinSplit.cpp (hunk 29 above)
Comment (ebfull) [inline src/zcash/JoinSplit.cpp]: This PR doesn't address that portion of the spec. I have placed `TODO: #808` everywhere that it is relevant.

File: src/zcash/JoinSplit.cpp (hunk 31 above)
Comment (ebfull) [inline src/zcash/JoinSplit.cpp]: There's no expected length of the proof because it's encoded in ascii decimal.

However, [in my future PR](https://github.com/ebfull/zcash/commit/8ff0dd4c2d3ebe25d3ddf2ebfa21b07454b44462), I have implemented fixed-sized proofs and wrote such assertions, because I enabled binary serialization.

File: src/zcash/Zcash.h (hunk 35 above)
Comment (ebfull) [inline src/zcash/Zcash.h]: Later in this PR the other constants are removed; I will add another commit that fixes these names.

File: src/zcash/JoinSplit.cpp [hunk 37]
```diff
@@ -0,0 +1,344 @@
...
+        protoboard<FieldT> pb;
+
+        joinsplit_gadget<FieldT, NumInputs, NumOutputs> g(pb);
+        g.generate_r1cs_constraints();
+
+        const r1cs_constraint_system<FieldT> constraint_system = pb.get_constraint_system();
+        r1cs_ppzksnark_keypair<ppzksnark_ppT> keypair = r1cs_ppzksnark_generator<ppzksnark_ppT>(constraint_system);
+
+        pk = keypair.pk;
+        vk = keypair.vk;
```
Comment (str4d) [inline src/zcash/JoinSplit.cpp]: Should these use move assignment?

File: src/zcbenchmarks.cpp [hunk 38]
```diff
@@ -42,64 +44,52 @@ double benchmark_sleep()
...
     timer_start();
-    CPourTx pourtx(*pzerocashParams,
-                   scriptPubKey,
+    CPourTx pourtx(*pzcashParams,
+                   pubKeyHash,
                    anchor,
-                   {vpourin[0], vpourin[1]},
-                   {vpourout[0], vpourout[1]},
+                   {JSInput(), JSInput()},
+                   {JSOutput(), JSOutput()},
```
Comment (str4d) [inline src/zcbenchmarks.cpp]: Technically, rewriting the test in this fashion will add the time it takes to generate the four random inputs to the benchmark time. But maybe it is insignificant.

**Comment by str4d** [comment]
ACK! With a few caveats:

- I went through all the gadgets, but do not claim to understand libsnark and therefore was not checking that e.g. the correct functions were called in the correct places.
- I did not compare the code against the protocol spec PDF (but everything I saw was consistent with my understanding of the spec as gained from meeting discussions).
- I did not review any of the fully-removed files, and am therefore assuming that the new code is a complete replacement.

File: src/zcash/JoinSplit.cpp (hunk 37 above)
Comment (ebfull) [inline src/zcash/JoinSplit.cpp]: This isn't a critical codepath for performance (used in tests and utilities only) but yes you're right.

**Comment by ebfull** [comment]
fyi: I am still adding `h_sig` test vectors to ensure it matches the spec.

File: src/zcash/circuit/commitment.tcc [hunk 39]
```diff
@@ -0,0 +1,104 @@
...
+                // length of message
+                0,0,0,0,0,0,0,0,
+                0,0,0,0,0,0,0,0,
+                0,0,0,0,0,0,0,0,
+                0,0,0,0,0,0,0,0,
+                0,0,0,0,0,0,0,0,
+                0,0,0,0,0,0,0,0,
+                0,0,0,0,0,0,1,1,
+                0,1,0,0,1,0,0,0
+            }, ZERO);
```
Comment (daira) [inline src/zcash/circuit/commitment.tcc]: Either add a comment saying what length this represents (840 bits), or compute it from the length.

File: src/zcash/circuit/commitment.tcc [hunk 40]
```diff
@@ -0,0 +1,104 @@
...
+            pb,
+            IV2,
+            block2->bits,
+            *result,
+        ""));
+    }
+
+    void generate_r1cs_constraints() {
+        // TODO: This may not be necessary if SHA256 constrains
+        // its output digests to be boolean anyway.
```
Comment (daira) [inline src/zcash/circuit/commitment.tcc]: We should follow and document a consistent convention for whether gadgets boolean-constrain their outputs.

File: src/zcash/circuit/gadget.tcc [hunk 41]
```diff
@@ -0,0 +1,345 @@
...
+private:
+    // Verifier inputs
+    pb_variable_array<FieldT> zk_packed_inputs;
+    pb_variable_array<FieldT> zk_unpacked_inputs;
+    std::shared_ptr<multipacking_gadget<FieldT>> unpacker;
+
+    std::shared_ptr<digest_variable<FieldT>> zk_merkle_root;
+    std::shared_ptr<digest_variable<FieldT>> zk_h_sig;
+    boost::array<std::shared_ptr<digest_variable<FieldT>>, NumInputs> zk_input_nullifiers;
+    boost::array<std::shared_ptr<digest_variable<FieldT>>, NumInputs> zk_input_hmacs;
```
Comment (daira) [inline src/zcash/circuit/gadget.tcc]: This is just called "macs" elsewhere. It isn't HMAC.

File: src/zcash/circuit/gadget.tcc [hunk 42]
```diff
@@ -0,0 +1,345 @@
...
+    boost::array<std::shared_ptr<input_note_gadget<FieldT>>, NumInputs> zk_input_notes;
+    boost::array<std::shared_ptr<PRF_pk_gadget<FieldT>>, NumInputs> zk_hmac_authentication;
+
+    // Output note gadgets
+    boost::array<std::shared_ptr<output_note_gadget<FieldT>>, NumOutputs> zk_output_notes;
+
+public:
+    // PRF_pk and PRF_rho each only have a 1-bit
+    // domain separation "nonce" for different hmacs.
+    BOOST_STATIC_ASSERT(NumInputs <= 2);
```
Comment (daira) [inline src/zcash/circuit/gadget.tcc]: ``PRF_rho`` takes an output index, not an input index.

File: src/zcash/circuit/gadget.tcc [hunk 43]
```diff
@@ -0,0 +1,345 @@
...
+            uint64_t left_side_acc = vpub_old;
+            for (size_t i = 0; i < NumInputs; i++) {
+                left_side_acc += inputs[i].note.value;
+            }
+
+            zk_total_uint64.fill_with_bits(
+                this->pb,
+                uint64_to_bool_vector(left_side_acc)
+            );
+        }
```
Comment (daira) [inline src/zcash/circuit/gadget.tcc]: Up to here in my review.

File: src/zcash/circuit/gadget.tcc (hunk 41 above)
Comment (ebfull) [inline src/zcash/circuit/gadget.tcc]: That's right, I'll take this opportunity to fix that.

File: src/zcash/circuit/commitment.tcc (hunk 40 above)
Comment (ebfull) [inline src/zcash/circuit/commitment.tcc]: Unfortunately, if it were *just* up to the gadget we could end up boolean constraining things that don't need to be.

File: src/zcash/circuit/prfs.tcc [hunk 44]
```diff
@@ -0,0 +1,139 @@
...
+            y = pb_variable_array<FieldT>();
+            while (y->size() < 256) {
+                y->emplace_back(ZERO);
+            }
+        }
+
+        block.reset(new block_variable<FieldT>(pb, {
+            discriminants,
+            x,
+            *y
```
Comment (daira) [inline src/zcash/circuit/prfs.tcc]: I can't tell whether this is using the right bit order.

File: src/zcash/circuit/prfs.tcc [hunk 45]
```diff
@@ -0,0 +1,139 @@
...
+        std::shared_ptr<digest_variable<FieldT>> result
+    ) : PRF_gadget<FieldT>(pb, ZERO, 1, 1, 0, 0, a_sk, boost::none, result) {}
+
+    void generate_r1cs_constraints() {
+        PRF_gadget<FieldT>::generate_r1cs_constraints();
+    }
+
+    void generate_r1cs_witness() {
+        PRF_gadget<FieldT>::generate_r1cs_witness();
+    }
```
Comment (daira) [inline src/zcash/circuit/prfs.tcc]: Why do ``generate_r1cs_constraints`` and ``generate_r1cs_witness`` need to be overridden; can't they just be inherited?

Comment (ebfull) [inline src/zcash/circuit/prfs.tcc]: I'm confused as to why I did that, yes I believe they can inherit instead.

File: src/gtest/test_noteencryption.cpp (hunk 13 above)
Comment (ebfull) [inline src/gtest/test_noteencryption.cpp]: Eh, to avoid silent integer overflow (which might not matter in this test anyway) I'd rather this be explicit for now so we can catch it later.

File: src/wallet/rpcwallet.cpp (hunk 19 above)
Comment (ebfull) [inline src/wallet/rpcwallet.cpp]: I agree. This lock is really only needed inside of `WitnessBucketCommitment` as far as I can tell.

File: src/zcash/circuit/gadget.tcc (hunk 42 above)
Comment (ebfull) [inline src/zcash/circuit/gadget.tcc]: Thanks for catching this.

File: src/zcash/Note.cpp (hunk 7 above)
Comment (ebfull) [inline src/zcash/Note.cpp]: That would be helpful. I was only concerned about memory safety here.

File: src/zcash/circuit/prfs.tcc (hunk 44 above)
Comment (ebfull) [inline src/zcash/circuit/prfs.tcc]: It is, it's just a flat map.

File: src/gtest/test_joinsplit.cpp [hunk 46]
```diff
@@ -0,0 +1,213 @@
...
+    // Create the commitment tree
+    ZCIncrementalMerkleTree tree;
+
+    // Set up a JoinSplit description
+    uint256 ephemeralKey;
+    uint256 randomSeed;
+    uint64_t vpub_old = 10;
+    uint64_t vpub_new = 0;
+    uint256 pubKeyHash = random_uint256();
+    boost::array<uint256, 2> hmacs;
```
Comment (defuse) [inline src/gtest/test_joinsplit.cpp]: Rename `hmacs` to something else since we aren't using HMAC (do this everywhere).

File: src/primitives/transaction.cpp [hunk 47]
```diff
@@ -9,84 +9,56 @@
...
-        uint256_to_array<NUM_POUR_OUTPUTS>(commitments),
-        uint256_to_array<NUM_POUR_INPUTS>(macs),
-        proof
+        anchor
     );
 }
 
+uint256 CPourTx::h_sig(ZCJoinSplit& params, const uint256& pubKeyHash) const
+{
+    return params.h_sig(randomSeed, serials, pubKeyHash);
```
Comment (defuse) [inline src/primitives/transaction.cpp]: Taylor should double-check that the order of arguments is the right order.

File: src/test/sighash_tests.cpp [hunk 48]
```diff
@@ -124,12 +124,12 @@ void static RandomTransaction(CMutableTransaction &tx, bool fSingle) {
             } else {
                 pourtx.vpub_new = insecure_rand() % 100000000;
             }
-            RandomScript(pourtx.scriptPubKey);
-            RandomScript(pourtx.scriptSig);
+
             pourtx.anchor = GetRandHash();
             pourtx.serials[0] = GetRandHash();
             pourtx.serials[1] = GetRandHash();
             pourtx.ephemeralKey = GetRandHash();
```
Comment (defuse) [inline src/test/sighash_tests.cpp]: This should technically be a Curve25519 public key.

File: src/primitives/transaction.h [hunk 49]
```diff
@@ -50,60 +35,65 @@ class CPourTx
...
     // that the recipient needs, including a memo field. It
     // is encrypted using the scheme implemented in crypto/NoteEncryption.cpp
-    boost::array<ZCNoteEncryption::Ciphertext, NUM_POUR_OUTPUTS> ciphertexts;
+    boost::array<ZCNoteEncryption::Ciphertext, ZC_NUM_JS_OUTPUTS> ciphertexts;
 
     // Ephemeral key
     uint256 ephemeralKey;
 
+    // Random seed
+    uint256 randomSeed;
```
Comment (defuse) [inline src/primitives/transaction.h]: Where does this get set to a random value? I just searched this diff for `randomSeed` and couldn't see where that happens. Should it happen in the constructor?

File: src/primitives/transaction.cpp [hunk 50]
```diff
@@ -9,84 +9,56 @@
...
+
+    params.loadProvingKey();
+    proof = params.prove(
+        inputs,
+        outputs,
+        notes,
+        ciphertexts,
+        ephemeralKey,
+        pubKeyHash,
+        randomSeed,
```
Comment (defuse) [inline src/primitives/transaction.cpp]: Oh, this is an output parameter, I think. (Re: my question of where randomSeed gets set to a random value).

File: src/test/sighash_tests.cpp [hunk 51]
```diff
@@ -124,12 +124,12 @@ void static RandomTransaction(CMutableTransaction &tx, bool fSingle) {
...
+            pourtx.randomSeed = GetRandHash();
             pourtx.ciphertexts[0] = {insecure_rand() % 100, insecure_rand() % 100};
             pourtx.ciphertexts[1] = {insecure_rand() % 100, insecure_rand() % 100};
```
Comment (defuse) [inline src/test/sighash_tests.cpp]: Is there a reason this is only setting the first two bytes (or whatever they are) of `ciphertexts[0]` and `ciphertexts[1]`?

File: src/test/test_bitcoin.cpp [hunk 52]
```diff
@@ -25,7 +25,7 @@
 
 CClientUIInterface uiInterface; // Declared but not defined in ui_interface.h
 CWallet* pwalletMain;
-libzerocash::ZerocashParams *pzerocashParams;
+ZCJoinSplit *pzcashParams;
```
Comment (defuse) [inline src/test/test_bitcoin.cpp]: Are there two global variables with this name?

File: src/primitives/transaction.h (hunk 49 above)
Comment (ebfull) [inline src/primitives/transaction.h]: The randomSeed is sampled by JoinSplit::prove.

File: src/test/sighash_tests.cpp (hunk 51 above)
Comment (ebfull) [inline src/test/sighash_tests.cpp]: Nope, also that code produces a warning which you've probably seen before, we should fix it.

File: src/test/test_bitcoin.cpp (hunk 52 above)
Comment (defuse) [inline src/test/test_bitcoin.cpp]: Yes, the other one is in `init.cpp`. What does C++ do in this case?

Comment (ebfull) [inline src/test/test_bitcoin.cpp]: Nah, it's just exported from `libbitcoinserver` (or whatever it is) just as `pwalletMain` is.

Comment (defuse) [inline src/test/test_bitcoin.cpp]: Does this even get linked with `init.cpp`?

Comment (ebfull) [inline src/test/test_bitcoin.cpp]: No it is not. That's how the tests have different initialization code than zcashd. :)

File: src/test/transaction_tests.cpp [hunk 53]
```diff
@@ -356,21 +350,23 @@ BOOST_AUTO_TEST_CASE(test_basic_pour_verification)
...
     {
         // Ensure that it won't verify if the root is changed.
-        auto test = CPourTx(p, scriptPubKey, uint256(rt), inputs, outputs, 0, 0);
+        auto test = CPourTx(*p, pubKeyHash, rt, inputs, outputs, 0, 0);
         test.anchor = GetRandHash();
-        BOOST_CHECK(!test.Verify(p));
+        BOOST_CHECK(!test.Verify(*p, pubKeyHash));
     }
+
+    delete p;
```
Comment (defuse) [inline src/test/transaction_tests.cpp]: I wonder if this will leak memory if one of the `BOOST_CHECK`'s fail. If it does, does it matter?

Comment (ebfull) [inline src/test/transaction_tests.cpp]: I don't think it matters in the tests, but `BOOST_CHECK` continues execution when it fails. Uncaught exceptions that occur during these tests will cause a leak though.

File: src/wallet/rpcwallet.cpp (hunk 19 above)
Comment (defuse) [inline src/wallet/rpcwallet.cpp]: Yeah I just copy/pasted that line without knowing what it was for, lol.

Comment (defuse) [inline src/wallet/rpcwallet.cpp]: Actually the one I copy/pasted is the one for the benchmarks.

File: src/wallet/rpcwallet.cpp [hunk 54]
```diff
@@ -2454,67 +2456,72 @@ Value zc_raw_receive(const json_spirit::Array& params, bool fHelp)
...
     assert(pwalletMain != NULL);
-    libzcash::MerklePath path;
+    std::vector<boost::optional<ZCIncrementalWitness>> witnesses;
     uint256 anchor;
-    auto found_in_chain = pwalletMain->WitnessBucketCommitment(commitment, path, anchor);
-
-    CAmount value_of_bucket = decrypted_bucket.getValue();
+    uint256 commitment = decrypted_note.cm();
+    pwalletMain->WitnessBucketCommitment(
+        {commitment},
```
Comment (defuse) [inline src/wallet/rpcwallet.cpp]: Why are the `{` `}` braces here?

File: src/test/transaction_tests.cpp (hunk 53 above)
Comment (ebfull) [inline src/test/transaction_tests.cpp]: For what it's worth, I've considered that `Unopened()` and `Generate()` could return `unique_ptr`s but I'd like to leave that to future work since it infringes somewhat on how those variables are initialized in our daemon.

File: src/wallet/rpcwallet.cpp (hunk 54 above)
Comment (defuse) [inline src/wallet/rpcwallet.cpp]: Nevermind, I see this PR changes the `WitnessBucketCommitment` API.

File: src/wallet/rpcwallet.cpp [hunk 55]
```diff
@@ -2563,99 +2570,97 @@ Value zc_raw_pour(const json_spirit::Array& params, bool fHelp)
...
+
+            vpourin.push_back(JSInput(*witnesses[i], notes[i], keys[i]));
+        }
+    }
+
+    while (vpourin.size() < ZC_NUM_JS_INPUTS) {
+        vpourin.push_back(JSInput());
     }
 
     BOOST_FOREACH(const Pair& s, outputs)
```
Comment (defuse) [inline src/wallet/rpcwallet.cpp]: Do we loop over the outputs in the same order as they were provided to the API? When we're sending note ciphertexts out of band we need to know the order.

Comment (defuse) [inline src/wallet/rpcwallet.cpp]: (Because the API takes a JSON object, not a list, the order may be undefined).

File: src/wallet/wallet.cpp [hunk 56]
```diff
@@ -1051,14 +1051,13 @@ bool CWalletTx::WriteToDisk(CWalletDB *pwalletdb)
     return pwalletdb->WriteTx(GetHash(), *this);
 }
 
-bool CWallet::WitnessBucketCommitment(uint256 &commitment,
-                                      libzcash::MerklePath &path,
+void CWallet::WitnessBucketCommitment(std::vector<boost::optional<uint256>> commitments,
+                                      std::vector<boost::optional<ZCIncrementalWitness>>& witnesses,
                                       uint256 &final_anchor)
```
Comment (defuse) [inline src/wallet/wallet.cpp]: Why is the first parameter a vector of optionals? What situation would you provide a vector with some elements not present?

Comment (defuse) [inline src/wallet/wallet.cpp]: Would it be better for these to be a `boost::array` of length ZC_NUM_INPUTS?

File: src/wallet/rpcwallet.cpp (hunk 55 above)
Comment (ebfull) [inline src/wallet/rpcwallet.cpp]: We will absolutely. The JoinSplit class will be responsible for ensuring the ordering is correct, and it has an out parameter with notes ordered correctly for this API to leverage.

File: src/zcash/Address.cpp [hunk 57]
```diff
@@ -0,0 +1,23 @@
+#include "Address.hpp"
```
Comment (defuse) [inline src/zcash/Address.cpp]: This is where I left off.

File: src/wallet/wallet.cpp (hunk 56 above)
Comment (ebfull) [inline src/wallet/wallet.cpp]: Hm, you would never, so this API is kind of funky. It's meant to optimize away comparisons once we've witnessed some or all of the commitments, but that isn't very helpful anyway, so I'll just remove it.

File: src/test/test_bitcoin.cpp (hunk 52 above)
Comment (daira) [inline src/test/test_bitcoin.cpp]: Renaming these variables to include "test" would set my mind at ease about whether they could be confused with the ones in `init.cpp` (either by the compiler/linker or by a human reader of the code).

File: src/primitives/transaction.h (hunk 17 above)
Comment (daira) [inline src/primitives/transaction.h]: Now I'm confused as to what I was thinking here. The order is ..., commitments, ephemeral key, ciphertexts, ...

Comment (daira) [inline src/primitives/transaction.h]: Oh it got fixed and rebased. Shouldn't github say that the comment was on an outdated diff? Anyway, `ephemeralKey` is missing.

File: src/primitives/transaction.h (hunk 18 above)
Comment (daira) [inline src/primitives/transaction.h]: `ephemeralKey` is missing here as well.

File: src/zcash/circuit/commitment.tcc (hunk 40 above)
Comment (daira) [inline src/zcash/circuit/commitment.tcc]: It would be preferable to be able to redundantly constrain them and then have redundant constraints automatically removed, as I think bellman does.

File: src/gtest/test_noteencryption.cpp (hunk 13 above)
Comment (defuse) [inline src/gtest/test_noteencryption.cpp]: What about using a `size_t i` then `message[i] = i & 0xff;` or something

File: src/primitives/transaction.cpp (hunk 47 above)
Comment (defuse) [inline src/primitives/transaction.cpp]: Yes, it's right, assuming `h_sig` takes its arguments in the same order as the spec.

File: src/test/sighash_tests.cpp (hunk 48 above)
Comment (defuse) [inline src/test/sighash_tests.cpp]: (This doesn't matter because we're just testing encoding/signature stuff right, i.e. it's never actually used as a public key?)

File: src/test/sighash_tests.cpp (hunk 51 above)
Comment (defuse) [inline src/test/sighash_tests.cpp]: Opened #926.

File: src/test/test_bitcoin.cpp (hunk 52 above)
Comment (defuse) [inline src/test/test_bitcoin.cpp]: +1 to renaming this to include "test."

Comment (defuse) [inline src/test/test_bitcoin.cpp]: I'm confused, @ebfull says above that this is the same variable but the variable is defined in `init.cpp` so if we're not linking against that then what this line does is re-define it? C++ is so confusing.

File: src/wallet/rpcwallet.cpp (hunk 55 above)
Comment (defuse) [inline src/wallet/rpcwallet.cpp]: (I don't fully understand why I wrote my original comment (it was during my pairing with Daira), I need to come back and re-review this code later.)

File: src/zcash/Address.cpp (hunk 25 above)
Comment (defuse) [inline src/zcash/Address.cpp]: Yes, @ebfull should set the setting in his editor to make it do that :)

File: src/zcbenchmarks.cpp [hunk 58]
```diff
@@ -42,64 +44,52 @@ double benchmark_sleep()
...
-    );
-    libzerocash::ZerocashParams zerocashParams = libzerocash::ZerocashParams(
-        INCREMENTAL_MERKLE_TREE_DEPTH,
-        &pk_loaded,
-        &vk_loaded
-    );
-    return timer_stop();
-}
 
-double benchmark_create_joinsplit()
```
Comment (defuse) [inline src/zcbenchmarks.cpp]: I was confused because the diff is kinda wonky here, the `+` lines are still part of `benchmark_parameter_loading()`.

File: src/zcbenchmarks.cpp (hunk 38 above)
Comment (defuse) [inline src/zcbenchmarks.cpp]: Yeah, it's probably insignificant.

File: src/zcbenchmarks.cpp [hunk 59]
```diff
@@ -42,64 +44,52 @@ double benchmark_sleep()
...
+    assert(pourtx.Verify(*pzcashParams, pubKeyHash));
     return ret;
 }
 
 double benchmark_verify_joinsplit(const CPourTx &joinsplit)
 {
     timer_start();
-    joinsplit.Verify(*pzerocashParams);
+    // TODO: #808
+    uint256 pubKeyHash;
```
Comment (defuse) [inline src/zcbenchmarks.cpp]: This times the `uint256` constructor, which I think is fast, but may be non-negligible compared to `joinsplit.Verify()`. Move this line above the `timer_start()`.

File: src/zcash/Address.hpp [hunk 60]
```diff
@@ -0,0 +1,53 @@
...
+class ViewingKey : public uint256 {
+public:
+    ViewingKey(uint256 sk_enc) : uint256(sk_enc) { }
+
+    uint256 pk_enc();
+};
+
+class SpendingKey : public uint256 {
+public:
+    SpendingKey() : uint256() { }
```
Comment (defuse) [inline src/zcash/Address.hpp]: Where do we use this 0-argument constructor? Should it be removed (or made private) to avoid accidentally using zero-valued SpendingKeys, i.e. force them to do `SpendingKey(uint256())` instead?

Comment (defuse) [inline src/zcash/Address.hpp]: Unless we're deserializing one according to section 7.4 of the spec (which is not implemented yet), spending keys should always be random, right? So the only way to create one of these should be to deserialize a string or to create a new random one.

Comment (ebfull) [inline src/zcash/Address.hpp]: We need to be able to construct a blank one so we can deserialize into it.

File: src/zcash/Address.cpp [hunk 61]
```diff
@@ -0,0 +1,23 @@
...
+uint256 ViewingKey::pk_enc() {
+    return ZCNoteEncryption::generate_pubkey(*this);
+}
+
+ViewingKey SpendingKey::viewing_key() {
+    return ViewingKey(ZCNoteEncryption::generate_privkey(*this));
+}
+
+SpendingKey SpendingKey::random() {
+    return SpendingKey(random_uint256());
```
Comment (defuse) [inline src/zcash/Address.cpp]: Eventually I want `SpendingKey` to have its 4 leading bits 0, and then the PRF to check that those bits are 0, instead of just masking them off.

Comment (ebfull) [inline src/zcash/Address.cpp]: This is captured by #899 correct?

File: src/zcash/JoinSplit.cpp (hunk 28 above)
Comment (defuse) [inline src/zcash/JoinSplit.cpp]: Yeah, I misinterpreted the name of this function while reading some code down below that calls it. To me "preload" means "complete the loading, in advance of performing the operation that needs it." So I thought the actual loading would happen here.

File: src/zcash/JoinSplit.cpp [hunk 62]
```diff
@@ -0,0 +1,344 @@
...
+    void loadVerifyingKey(std::string path) {
+        loadFromFile(path, vk);
+    }
+    void saveVerifyingKey(std::string path) {
+        if (vk) {
+            saveToFile(path, *vk);
+        } else {
+            throw std::runtime_error("cannot save verifying key; key doesn't exist");
+        }
+    }
```
Comment (defuse) [inline src/zcash/JoinSplit.cpp]: Nitpick: Should the API's for loading verifying key and proving key be the same, so that there aren't two different ways of loading to understand?

Comment (ebfull) [inline src/zcash/JoinSplit.cpp]: I put a "TODO: #789" in `JoinSplit.hpp` so we could talk about this API another time.

File: src/zcash/Note.cpp (hunk 7 above)
Comment (ebfull) [inline src/zcash/Note.cpp]: This is done. (I assert the size after loading the plaintext is zero.)

File: src/primitives/transaction.cpp (hunk 16 above)
Comment (ebfull) [inline src/primitives/transaction.cpp]: I'm splitting this kind of stuff into #927 so that I don't need to break serialization again in this PR; we're also not done adding fields and making changes yet anyway.

File: src/primitives/transaction.h (hunk 17 above)
Comment (ebfull) [inline src/primitives/transaction.h]: (copied and pasted) I'm splitting this kind of stuff into #927 so that I don't need to break serialization again in this PR; we're also not done adding fields and making changes yet anyway.

File: src/zcash/Address.cpp (hunk 25 above)
Comment (ebfull) [inline src/zcash/Address.cpp]: I'll make my editor do this when I'm done with this PR so that I don't add spurious newlines in every fixup commit I make.

File: src/zcash/circuit/commitment.tcc (hunk 40 above)
Comment (ebfull) [inline src/zcash/circuit/commitment.tcc]: Bellman doesn't do that, if a variable is boolean constrained it becomes a different type.

File: src/zcash/JoinSplit.hpp [hunk 63]
```diff
@@ -0,0 +1,98 @@
+#ifndef _ZCJOINSPLIT_H_
```
Comment (defuse) [inline src/zcash/JoinSplit.hpp]: I'm up to here in my review.

File: src/zcash/JoinSplit.cpp (hunk 30 above)
Comment (defuse) [inline src/zcash/JoinSplit.cpp]: I haven't seen anywhere else that we use `i0`.

File: src/zcash/JoinSplit.cpp [hunk 64]
```diff
@@ -0,0 +1,344 @@
...
+
+        // Encrypt the ciphertexts containing the note
+        // plaintexts to the recipients of the value.
+        {
+            ZCNoteEncryption encryptor(h_sig);
+
+            for (size_t i = 0; i < NumOutputs; i++) {
+                // TODO: expose memo in the public interface
+                boost::array<unsigned char, ZC_MEMO_SIZE> memo;
+                memo[0] = 0xF6; // invalid UTF8 as per spec
```
Comment (defuse) [inline src/zcash/JoinSplit.cpp]: According to boost docs, "passing no initializer list means that the elements have an indetermined initial value". The rest of the bytes of `memo` may be filled with uninitialized memory, which could potentially contain secrets which would get sent to whoever you're sending the note. Let's do:

```
boost::array<unsigned char, ZC_MEMO_SIZE> memo = { { 0xF6 } };
```

...which guarantees the other elements are default-initialized.

http://www.boost.org/doc/libs/1_60_0/doc/html/array/rationale.html

File: src/zcash/JoinSplit.cpp [hunk 65]
```diff
@@ -0,0 +1,344 @@
...
+        uint256& ephemeralKey,
+        const uint256& pubKeyHash,
+        uint256& randomSeed,
+        boost::array<uint256, NumInputs>& macs,
+        boost::array<uint256, NumInputs>& nullifiers,
+        boost::array<uint256, NumOutputs>& commitments,
+        uint64_t vpub_old,
+        uint64_t vpub_new,
+        const uint256& rt
+    ) {
```
Comment (defuse) [inline src/zcash/JoinSplit.cpp]: It's really unclear which of these are output parameters and which aren't. :(

File: src/zcash/JoinSplit.cpp [hunk 66]
```diff
@@ -0,0 +1,344 @@
...
+}
+
+template<size_t NumInputs, size_t NumOutputs>
+uint256 JoinSplit<NumInputs, NumOutputs>::h_sig(
+    const uint256& randomSeed,
+    const boost::array<uint256, NumInputs>& nullifiers,
+    const uint256& pubKeyHash
+) {
+    unsigned char personalization[crypto_generichash_blake2b_PERSONALBYTES]
+        = {'Z','c','a','s','h','C','o','m','p','u','t','e','h','S','i','g'};
```
Comment (defuse) [inline src/zcash/JoinSplit.cpp]: is strlen("ZcashComputehSig") == crypto_generichash_blake2b_PERSONALBYTES? Yes it is.

File: src/zcash/JoinSplit.cpp (hunk 65 above)
Comment (ebfull) [inline src/zcash/JoinSplit.cpp]: If it's `const` it's an input, if it's not it's an output, with the exception of `vpub_old` and `vpub_new`.

File: src/zcash/Note.cpp [hunk 67]
```diff
@@ -0,0 +1,92 @@
...
+{
+    auto plaintext = decryptor.decrypt(ciphertext, ephemeralKey, h_sig, nonce);
+
+    CDataStream ss(SER_NETWORK, PROTOCOL_VERSION);
+    ss << plaintext;
+
+    NotePlaintext ret;
+    ss >> ret;
+
+    assert(ss.size() == 0);
```
Comment (defuse) [inline src/zcash/Note.cpp]: I won't be able to make this fail and crash your node because something else is supposed to check the note ciphertext size before this function ever gets called, right?

Comment (ebfull) [inline src/zcash/Note.cpp]: `plaintext` is `boost::array<unsigned char, 201>`, and if `NotePlaintext` doesn't deserialize exactly that much, its serialization code must be written wrong. Thus, it's a local assertion and not input dependent, so long as the `NotePlaintext` deserialization length is not input dependent, which I have checked and it is not.

File: src/zcash/circuit/commitment.tcc [hunk 68]
```diff
@@ -0,0 +1,104 @@
+template<typename FieldT>
```
Comment (defuse) [inline src/zcash/circuit/commitment.tcc]: Up to here now.

**Comment by ebfull** [comment]
I've fixed the nits so far, let me know if you think I missed something.

File: src/zcash/circuit/prfs.tcc [hunk 69]
```diff
@@ -0,0 +1,107 @@
+template<typename FieldT>
```
Comment (defuse) [inline src/zcash/circuit/prfs.tcc]: I've reviewed everything up from the bottom until here.

File: src/zcash/JoinSplit.cpp (hunk 30 above)
Comment (daira) [inline src/zcash/JoinSplit.cpp]: We use it in ``src/zcash/prf.{cpp,h}``.

File: src/zcash/Note.cpp [hunk 70]
```diff
@@ -0,0 +1,92 @@
...
+
+uint256 Note::cm() const {
+    unsigned char discriminant = 0xb0;
+
+    CSHA256 hasher;
+    hasher.Write(&discriminant, 1);
+    hasher.Write(a_pk.begin(), 32);
+
+    std::vector<unsigned char> value_vec(sizeof(value), 0);
+    libzerocash::convertIntToBytesVector(value, value_vec);
```
Comment (defuse) [inline src/zcash/Note.cpp]: This has the wrong endianness. The spec says "All integers in Zcash-specific encodings are unsigned, have fixed bit length, and are encoded in little-endian byte order." But `convertIntToBytesVector's code is...

```
void convertIntToBytesVector(const uint64_t val_int, std::vector<unsigned char>& bytes) {
     for(size_t i = 0; i < bytes.size(); i++) {
         bytes[bytes.size()-1-i] = (val_int >> (i * 8));
    }
}
```

...which is big endian.

File: src/zcash/circuit/utils.tcc [hunk 71]
```diff
@@ -0,0 +1,55 @@
...
+        input_v,
+        output_bv
+    );
+
+    return output_bv;
+}
+
+std::vector<bool> uint64_to_bool_vector(uint64_t input) {
+    std::vector<unsigned char> num_bv(8, 0);
+    libzerocash::convertIntToBytesVector(input, num_bv);
```
Comment (defuse) [inline src/zcash/circuit/utils.tcc]: This is probably the wrong endianess, see https://github.com/zcash/zcash/pull/908/files#r62951908

**Comment by defuse** [comment]
ACK after these comments are addressed:

- Wrong endianness: https://github.com/zcash/zcash/pull/908/files#r62951908
- Wrong endianness 2: https://github.com/zcash/zcash/pull/908#discussion_r62951956
- Two global variables with the same name: https://github.com/zcash/zcash/pull/908/files#r62763508

**Comment by defuse** [comment]
FYI, I'm not familiar with the libsnark API yet, so I didn't do a thorough review of the circuit.

**Comment by defuse** [comment]
Also, either we should ticket the unfinished TODO item (write h_sig tests) or add them to this PR.

File: src/zcash/Note.cpp (hunk 70 above)
Comment (ebfull) [inline src/zcash/Note.cpp]: Hm, yes this should be changed to match the spec. I retained the same behavior and encoding from the old implementation.

File: src/test/test_bitcoin.cpp (hunk 52 above)
Comment (ebfull) [inline src/test/test_bitcoin.cpp]: There is no duplicated global variable; `init.cpp` is not linked into the test framework, but `init.h` declares an external `zcashParams`, which the test framework provides. I think the test framework could eventually initialize it using a generated circuit -- for now it does nothing. However, it will cause linker errors if we don't declare it.

**Comment by ebfull** [comment]
**TODO**

- [ ] Add `h_sig` test vectors.
- [ ] Switch endianness of values around, or come up with a good reason why we shouldn't do that in this PR.
- [ ] Rebase PR and get @daira's final review pass through.

File: src/zcash/Note.cpp (hunk 70 above)
Comment (daira) [inline src/zcash/Note.cpp]: Let's make the name of the conversion function explicitly say that it is little-endian. That way the endian-correctness of both the conversion function and its uses can be analysed locally.

File: src/zcash/circuit/utils.tcc [hunk 72]
```diff
@@ -0,0 +1,55 @@
...
+    std::vector<bool> num_v(64, 0);
+    libzerocash::convertBytesVectorToVector(num_bv, num_v);
```
Comment (daira) [inline src/zcash/circuit/utils.tcc]: Note that byte->bit conversion is most-significant-bit first, so only change the name of `convertIntToBytesVector` to reflect that it is little-encroach, not the name of `uint64_to_bool_vector` (which is mixed-endian) or `convertBytesVectorToVector`. Although the latter is a terrible name for other reasons (it should say that it's converting to bits).

File: src/test/test_bitcoin.cpp (hunk 52 above)
Comment (daira) [inline src/test/test_bitcoin.cpp]: Oh, I see. Please add a comment saying exactly that.

File: src/zcash/JoinSplit.cpp [hunk 73]
```diff
@@ -0,0 +1,344 @@
...
+    LOCK(cs_ParamsIO);
+
+    std::stringstream ss;
+    ss << obj;
+    std::ofstream fh;
+    fh.open(path, std::ios::binary);
+    ss.rdbuf()->pubseekpos(0, std::ios_base::out);
+    fh << ss.rdbuf();
+    fh.flush();
+    fh.close();
```
Comment (daira) [inline src/zcash/JoinSplit.cpp]: Closing implicitly flushes.

File: src/zcash/JoinSplit.cpp [hunk 74]
```diff
@@ -0,0 +1,344 @@
...
+CCriticalSection cs_InitializeParams;
+
+template<typename T>
+void saveToFile(std::string path, T& obj) {
+    LOCK(cs_ParamsIO);
+
+    std::stringstream ss;
+    ss << obj;
+    std::ofstream fh;
+    fh.open(path, std::ios::binary);
```
Comment (daira) [inline src/zcash/JoinSplit.cpp]: Does this need an `is_open` check similar to line 50?

File: src/zcash/JoinSplit.cpp [hunk 75]
```diff
@@ -0,0 +1,344 @@
...
+}
+
+template<typename T>
+void loadFromFile(std::string path, boost::optional<T>& objIn) {
+    LOCK(cs_ParamsIO);
+
+    std::stringstream ss;
+    std::ifstream fh(path, std::ios::binary);
+
+    if(!fh.is_open()) {
```
Comment (daira) [inline src/zcash/JoinSplit.cpp]: Nitpick: `if (`.

File: src/zcash/JoinSplit.cpp (hunk 65 above)
Comment (daira) [inline src/zcash/JoinSplit.cpp]: This needs to be obvious at call sites as well as declarations and implementations. Prepend `out_` to names of output parameters.

File: src/zcash/JoinSplit.cpp [hunk 76]
```diff
@@ -0,0 +1,344 @@
...
+
+        // Compute h_sig
+        uint256 h_sig = this->h_sig(randomSeed, nullifiers, pubKeyHash);
+
+        // Sample phi
+        uint256 phi = random_uint256();
+
+        // Compute notes for outputs
+        for (size_t i = 0; i < NumOutputs; i++) {
+            // Sample r
```
Comment (daira) [inline src/zcash/JoinSplit.cpp]: Rename this to `r_i` (or `r_i0`).

File: src/zcash/JoinSplit.cpp [hunk 77]
```diff
@@ -0,0 +1,344 @@
...
+}
+
+JSOutput::JSOutput() : addr(uint256(), uint256()), value(0) {
+    SpendingKey a_sk(random_uint256());
+    addr = a_sk.address();
+}
+
+JSInput::JSInput() : witness(ZCIncrementalMerkleTree().witness()),
+                     key(random_uint256()) {
+    note = Note(key.address().a_pk, 0, random_uint256(), random_uint256());
```
Comment (daira) [inline src/zcash/JoinSplit.cpp]: It's not strictly necessary to generate a_pk from a_sk for a dummy input; it could just be a random uint256 (which is indistinguishable from a PRF_addr output). The commitment does have to be consistent with the chosen a_pk though, so perhaps it's easier to do it this way for now. Incidentally, I think `cm()` is recomputing a_pk which it shouldn't need to do. Maybe we should cache it, but I'm not sure it's significant for performance anyway.

Comment (daira) [inline src/zcash/JoinSplit.cpp]: `cm()` is not recomputing a_pk so that's not a problem.

File: src/zcash/Note.hpp [hunk 78]
```diff
@@ -0,0 +1,73 @@
...
+
+class NotePlaintext {
+private:
+    uint64_t value;
+    uint256 rho;
+    uint256 r;
+
+public:
+    boost::array<unsigned char, ZC_MEMO_SIZE> memo;
+
```
Comment (daira) [inline src/zcash/Note.hpp]: Why the different access for `memo` vs the other fields?

File: src/zcash/circuit/gadget.tcc [hunk 79]
```diff
@@ -0,0 +1,349 @@
...
+                "unpacker"
+            ));
+        }
+
+        // We need a constant "zero" variable in some contexts. In theory
+        // it should never be necessary, but libsnark does not synthesize
+        // optimal circuits.
+        // 
+        // The first variable of our constraint system is constrained
+        // to be one automatically for us, and is known as `ONE`.
```
Comment (daira) [inline src/zcash/circuit/gadget.tcc]: Switch around this comment so that the part about `ONE` doesn't appear to be associated with the `ZERO.allocate(pb);`.

File: src/zcash/circuit/gadget.tcc [hunk 80]
```diff
@@ -0,0 +1,349 @@
...
+        }
+
+        for (size_t i = 0; i < NumOutputs; i++) {
+            // Witness the output information.
+            zk_output_notes[i]->generate_r1cs_witness(outputs[i]);
+        }
+
+        // [SANITY CHECK] Ensure that the intended root
+        // was witnessed by the inputs, even if the read
+        // gadget overwrote it. This allows the prover to
```
Comment (daira) [inline src/zcash/circuit/gadget.tcc]: I don't understand "even if the read gadget overwrote it". How could that happen?

File: src/zcash/circuit/gadget.tcc [hunk 81]
```diff
@@ -0,0 +1,349 @@
...
+
+    static r1cs_primary_input<FieldT> witness_map(
+        const uint256& rt,
+        const uint256& h_sig,
+        const boost::array<uint256, NumInputs>& macs,
+        const boost::array<uint256, NumInputs>& nullifiers,
+        const boost::array<uint256, NumOutputs>& commitments,
+        uint64_t vpub_old,
+        uint64_t vpub_new
+    ) {
```
Comment (daira) [inline src/zcash/circuit/gadget.tcc]: The inputs here have to be in the same order as in the `joinsplit_gadget` constructor, correct? If we can't remove the code redundancy, can we instead move this method up next to the constructor as a hint to readers that they're supposed to be related?

File: src/zcash/circuit/merkle.tcc [hunk 82]
```diff
@@ -0,0 +1,60 @@
...
+
+        authvars->generate_r1cs_constraints();
+        auth->generate_r1cs_constraints();
+    }
+
+    void generate_r1cs_witness(const MerklePath& path) {
+        // TODO: Change libsnark so that it doesn't require this goofy
+        // number thing in its API.
+        size_t path_index = libzerocash::convertVectorToInt(path.index);
+
```
Comment (daira) [inline src/zcash/circuit/merkle.tcc]: Huh. Yeah that's just odd.

File: src/zcash/circuit/note.tcc [hunk 83]
```diff
@@ -0,0 +1,253 @@
...
+    void generate_r1cs_constraints() {
+        for (size_t i = 0; i < 64; i++) {
+            generate_boolean_r1cs_constraint<FieldT>(
+                this->pb,
+                value[i],
+                "boolean_value"
+            );
+        }
+
+        r->generate_r1cs_constraints();
```
Comment (daira) [inline src/zcash/circuit/note.tcc]: This constrains bitness, right?

File: src/zcash/circuit/note.tcc [hunk 84]
```diff
@@ -0,0 +1,253 @@
...
+    }
+
+    void generate_r1cs_witness(const Note& note) {
+        r->bits.fill_with_bits(this->pb, uint256_to_bool_vector(note.r));
+        value.fill_with_bits(this->pb, uint64_to_bool_vector(note.value));
+    }
+};
+
+template<typename FieldT>
```
Comment (daira) [inline src/zcash/circuit/note.tcc]: This is much better than the monolithic approach of the old code :-)

File: src/zcash/circuit/note.tcc [hunk 85]
```diff
@@ -0,0 +1,253 @@
...
+        spend_authority->generate_r1cs_constraints();
+        expose_nullifiers->generate_r1cs_constraints();
+
+        commit_to_inputs->generate_r1cs_constraints();
+
+        // value * (1 - enforce) = 0
+        // Given `enforce` is boolean constrained:
+        // If `value` is zero, `enforce` _can_ be zero.
+        // If `value` is nonzero, `enforce` _must_ be one.
+        generate_boolean_r1cs_constraint<FieldT>(this->pb, value_enforce,"");
```
Comment (daira) [inline src/zcash/circuit/note.tcc]: Nitpick: space before `""`.

File: src/zcash/circuit/prfs.tcc (hunk 69 above)
Comment (daira) [inline src/zcash/circuit/prfs.tcc]: I've reviewed everything from the top until here.

File: src/zcash/circuit/prfs.tcc (hunk 44 above)
Comment (daira) [inline src/zcash/circuit/prfs.tcc]: What does it do if `y` is `boost::none`?

Comment (daira) [inline src/zcash/circuit/prfs.tcc]: I guess I find it odd that `y` is optional rather than explicitly passing zeroes.

File: src/zerocash/Address.cpp [hunk 86]
```diff
@@ -1,132 +0,0 @@
...
-
-    uint256 a_sk_u(a_sk);
-
-    uint256 sk_enc = ZCNoteEncryption::generate_privkey(a_sk_u);
-
-    PrivateAddress addr_sk(a_sk_u, sk_enc);
-    return Address(addr_sk);
-}
-
-} /* namespace libzerocash */
```
Comment (daira) [inline src/zerocash/Address.cpp]: Yay negative code! WHEEE! <3

Comment (daira) [inline src/zerocash/Address.cpp]: rollercoaster gif

File: src/zerocash/MintTransaction.cpp [hunk 87]
```diff
@@ -1,75 +0,0 @@
...
-
-const CoinCommitmentValue& MintTransaction::getMintedCoinCommitmentValue() const{
-	return this->externalCommitment.getCommitmentValue();
-}
-
-uint64_t MintTransaction::getMonetaryValue() const {
-    return convertBytesVectorToInt(this->coinValue);
-}
-
-} /* namespace libzerocash */
```
Comment (daira) [inline src/zerocash/MintTransaction.cpp]: Bye bye Mint transactions! :-)

**Comment by daira** [comment]
This review was fun :-)

There are a few unresolved comments, other than that it's looking fantastic.

File: src/zcash/circuit/gadget.tcc (hunk 80 above)
Comment (ebfull) [inline src/zcash/circuit/gadget.tcc]: The merkle read gadget will copy into `rt`, a verifier input. It might overwrite the root we thought we were witnessing, in which case the constraint system will fail here instead of during verificiation. This same thing happens with the SHA256 gadget.

There is a better way to perform these sanity checks: compute the witness map and assign the verifier inputs to them, but we can do that later.

File: src/zcash/circuit/gadget.tcc (hunk 81 above)
Comment (ebfull) [inline src/zcash/circuit/gadget.tcc]: They don't have to be; this is a static that's kept here for consistency/organizational reasons.

File: src/zcash/circuit/note.tcc (hunk 83 above)
Comment (ebfull) [inline src/zcash/circuit/note.tcc]: Yep! It's all the digest_variable gadget does, afaik.

File: src/primitives/transaction.h (hunk 18 above)
Comment (ebfull) [inline src/primitives/transaction.h]: (copied and pasted) I'm splitting this kind of stuff into #927 so that I don't need to break serialization again in this PR; we're also not done adding fields and making changes yet anyway.

File: src/wallet/rpcwallet.cpp (hunk 22 above)
Comment (ebfull) [inline src/wallet/rpcwallet.cpp]: It will be around the time chained pours are added.

File: src/zcash/JoinSplit.cpp (hunk 30 above)
Comment (ebfull) [inline src/zcash/JoinSplit.cpp]: I think we should just keep `i` for variables we can locally reason about being 0-indexed. I don't mind adding it to headers though.

File: src/zcash/circuit/commitment.tcc (hunk 39 above)
Comment (ebfull) [inline src/zcash/circuit/commitment.tcc]: (Added a comment.)

**Comment by ebfull** [comment]
TODO list complete, and PR is squashed. Please do a final review pass to make sure everything has been addressed!

**Comment by defuse** [comment]
Sean squashed this in a funky way so I double checked that the contents before the rebase and after the rebase are the same (except a newline, which got added during the rebase).

**Comment by ebfull** [comment]
@zkbot try

**Comment by ebfull** [comment]
@zkbot try

**Comment by ebfull** [comment]
@zkbot force

**Comment by ebfull** [comment]
@zkbot try

**Comment by ebfull** [comment]
Can you just work please?

@zkbot try

**Comment by ebfull** [comment]
@zkbot retry

**Comment by ebfull** [comment]
@zkbot retry

**Comment by ebfull** [comment]
@zkbot try

**Comment by ebfull** [comment]
@zkbot retry

**Comment by ebfull** [comment]
The failing performance test is unrelated to this PR, please still review/ACK and I'll `r+` once buildbot is working properly.

**Comment by str4d** [comment]
@zkbot retry

**Comment by ebfull** [comment]
@zkbot retry

**Comment by daira** [comment]
Doing another review pass.

File: src/gtest/test_circuit.cpp [hunk 88]
```diff
@@ -0,0 +1,78 @@
...
+{
+    default_r1cs_ppzksnark_pp::init_public_params();
+    typedef Fr<default_r1cs_ppzksnark_pp> FieldT;
+    test_value_equals<FieldT>(0);
+    test_value_equals<FieldT>(1);
+    test_value_equals<FieldT>(3);
+    test_value_equals<FieldT>(5391);
+    test_value_equals<FieldT>(883128374);
+    test_value_equals<FieldT>(173419028459);
+    test_value_equals<FieldT>(2205843009213693953);
```
Comment (daira) [inline src/gtest/test_circuit.cpp]: Add a test for ``1<<64 - 1`` = 9223372036854775808.

File: src/zcash/circuit/utils.tcc [hunk 89]
```diff
@@ -0,0 +1,71 @@
...
+    into.insert(into.end(), num.begin(), num.end());
+}
+
+template<typename T>
+T swap_endianness_u64(T v) {
+    if (v.size() != 64) {
+        throw std::length_error("invalid bit length for 64-bit unsigned integer");
+    }
+
+    for (size_t i = 0; i < 4; i++) {
```
Comment (daira) [inline src/zcash/circuit/utils.tcc]: Add a comment saying what this is doing (swap the byte endianness, preserving bit order within each byte).

File: src/zcash/circuit/utils.tcc [hunk 90]
```diff
@@ -47,9 +46,26 @@ void insert_uint64(std::vector<bool>& into, uint64_t from) {
...
+}
+
 template<typename FieldT>
-linear_combination<FieldT> packed_addition(pb_variable_array<FieldT>& input) {
+linear_combination<FieldT> packed_addition(pb_variable_array<FieldT> input) {
+    auto input_swapped = swap_endianness_u64(input);
+
     return pb_packing_sum<FieldT>(pb_variable_array<FieldT>(
-        input.rbegin(), input.rend()
+        input_swapped.rbegin(), input_swapped.rend()
```
Comment (daira) [inline src/zcash/circuit/utils.tcc]: Hmm, this is ugly. The input is represented as mixed-endian. When I accepted the switch from being consistently little-endian, to using little-endian byte order but with the MS bit first in a byte, I hadn't anticipated that we'd need to do that. I had thought that we'd keep all the value fields in some consistent order (doesn't matter which), and do the swapping only for the representation of v in the commitment input.

File: src/zcash/JoinSplit.cpp (hunk 74 above)
Comment (daira) [inline src/zcash/JoinSplit.cpp]: I think this needs fixing.

File: src/zcash/circuit/gadget.tcc (hunk 43 above)
Comment (daira) [inline src/zcash/circuit/gadget.tcc]: And now up to here in my re-review.

File: src/zcash/circuit/gadget.tcc (hunk 80 above)
Comment (daira) [inline src/zcash/circuit/gadget.tcc]: I'm mildly disturbed that anything can get overwritten in an API that should have been pure-functional, and I still don't quite understand this. I guess that making the prover fail early is not essential to security, though, so I'm fine with this for now.

File: src/zcash/circuit/gadget.tcc (hunk 81 above)
Comment (daira) [inline src/zcash/circuit/gadget.tcc]: I meant the order of ``insert_uint256``/``64``s.

File: src/zcash/circuit/merkle.tcc (hunk 82 above)
Comment (daira) [inline src/zcash/circuit/merkle.tcc]: Please open a ticket for this.

File: src/zcash/circuit/gadget.tcc (hunk 81 above)
Comment (ebfull) [inline src/zcash/circuit/gadget.tcc]: The ordering does need to be the same, I can definitely move it around for cleanliness but can we avoid blocking this ticket on that?

File: src/zcash/circuit/merkle.tcc (hunk 82 above)
Comment (ebfull) [inline src/zcash/circuit/merkle.tcc]: https://github.com/scipr-lab/libsnark/issues/34

File: src/zcash/circuit/prfs.tcc (hunk 44 above)
Comment (daira) [inline src/zcash/circuit/prfs.tcc]: I still think it would be clearer to have the code for the ``!y`` case in ``PRF_addr_a_pk_gadget``.

Comment (ebfull) [inline src/zcash/circuit/prfs.tcc]: You're right, that would be a bit simpler. This is accurate for now and I made [a ticket](https://github.com/zcash/zcash/issues/930) to clean that up. (I want to be careful not to disturb the constraint system when reorganizing this later.)

**Comment by daira** [comment]
ACK! None of my recent comments are blockers. I do think it would be clearer to avoid the mixed-endian arithmetic and do the byte-swapping only for the v input to the commitment, though.

**Comment by defuse** [comment]
ACK, I didn't give it a full separate review pass but I think I checked all the individual issues I cared about.

**Comment by ebfull** [comment]
Great! I want to see the performance buildbot thing working first and this can be merged.

File: src/zcash/JoinSplit.cpp (hunk 74 above)
Comment (ebfull) [inline src/zcash/JoinSplit.cpp]: Not too critical I think; we only use this code for the `GenerateParams` binary right now.

**Comment by ebfull** [comment]
Buildbot should be working now. This has been reviewed and ACK'd, merging. Thanks!

@zkbot r+

**Comment by ebfull** [comment]
@zkbot retry

**Comment by ebfull** [comment]
@zkbot force

**Comment by ebfull** [comment]
@zkbot r+

**Comment by ebfull** [comment]
@zkbot r+
