### PR TITLE
Make Equihash solvers cancellable

### LINKED ISSUE #1055: All mined blocks are stale
All of the blocks that `zcashd -gen` manages to mine for me, which happens every few minutes, turn out to be stale:

```
2016-06-25 12:31:14 CreateNewBlock(): total size 1000
2016-06-25 12:31:14 Running ZcashMiner with 1 transactions in block (274 bytes)
2016-06-25 12:31:34 UpdateTip: new best=57fb9e387420d8e936a19237b866dc24412f4c5d73c00cde1ac0d73d99de205e  height=7674  log2_work=17.093479  tx=7690  date=2016-06-25 13:25:42 progress=1.000000  cache=0.0MiB(3tx)
2016-06-25 12:32:45 UpdateTip: new best=24c9f7c5d58babc029b4d6824fb9f8694a12561938eb0c7386920e5973d6b9e7  height=7675  log2_work=17.0935  tx=7691  date=2016-06-25 12:31:46 progress=1.000000  cache=0.0MiB(4tx)
2016-06-25 12:33:54 UpdateTip: new best=42498a8926f057a6e53ea3868b80643e102aded4e003e99e670b2cf09438d15b  height=7676  log2_work=17.093521  tx=7692  date=2016-06-25 12:32:51 progress=1.000000  cache=0.0MiB(5tx)
2016-06-25 12:34:03 ZcashMiner:
2016-06-25 12:34:03 proof-of-work found  
  hash: 50cefaa3ab8a2d0e3758870d6265ef3e3fbcca9f207ad7b1c47fcbbbf700e9ff  
target: 75c28e0000000000000000000000000000000000000000000000000000000000
2016-06-25 12:34:03 CBlock(hash=50cefaa3ab8a2d0e3758870d6265ef3e3fbcca9f207ad7b1c47fcbbbf700e9ff, ver=4, hashPrevBlock=425655fe7074053901bb0e4d14873e4649a87cafb9bc7513ceab3fd94595e65e, hashMerkleRoot=d0e789d8896321951f94bb78ad912620607a848e6be5245a5f78feab28986cf1, hashReserved=0000000000000000000000000000000000000000000000000000000000000000, nTime=1466857874, nBits=2075c28e, nNonce=0000000000000000000000000000000000000000000000000000000000000001, vtx=1)
  CTransaction(hash=d0e789d889, ver=1, vin.size=1, vout.size=2, nLockTime=0)
    CTxIn(COutPoint(0000000000, 4294967295), coinbase 02fa1d0101)
    CTxOut(nValue=3.83700000, scriptPubKey=037c5fa12ad4b93feacc3f1ace9bc3)
    CTxOut(nValue=0.95925000, scriptPubKey=OP_HASH160 6708e6670db0b950dac)

  vMerkleTree:  d0e789d8896321951f94bb78ad912620607a848e6be5245a5f78feab28986cf1

2016-06-25 12:34:03 generated 3.837
2016-06-25 12:34:03 ERROR: ZcashMiner: generated block is stale
```

This might very well be user error or such, but while we're at this early stage of the project I hope it's OK to use GitHub issues for tracking of things like this. Please feel free to close this issue if it's in fact not with the code.

### PR DESCRIPTION
**Pull request by str4d**
The miner only cancels the solver when chainActive.Tip() changes.

Closes #1055

### CODE REVIEW

File: src/crypto/equihash.cpp [hunk 1]
```diff
@@ -203,6 +205,8 @@ std::set<std::vector<eh_index>> Equihash<N,K>::BasicSolve(const eh_HashState& ba
     X.reserve(init_size);
     for (eh_index i = 0; i < init_size; i++) {
         X.emplace_back(N, base_state, i);
+        // Slow down checking to prevent segfaults (??)
+        if (i % 10000 == 0 && cancelled()) throw solver_cancelled;
```
Comment (nathan-at-least) [inline src/crypto/equihash.cpp]: Let's define a constant for all the ``10000``'s involved in cancellation.

**Comment by nathan-at-least** [comment]
I don't see any tests of cancellation. There are many cancellation branches and I'd prefer if each were tested, although I'm not sure how feasible that is without the cancel callback somehow being aware of the internal mining state.

**Comment by zookozcash** [comment]
Good catch! It is not okay with me to commit code branches that aren't tested.

File: src/crypto/equihash.cpp (hunk 1 above)
Comment (daira) [inline src/crypto/equihash.cpp]: "To prevent segfaults"? Wait what!?

**Comment by str4d** [comment]
@nathan-at-least Gah! I had a comment here that I wanted a concept ACK before figuring out how to test it, but it must have not sent (probably due to my internet connectivity issues yesterday).

File: src/crypto/equihash.cpp (hunk 1 above)
Comment (str4d) [inline src/crypto/equihash.cpp]: @daira legitimately yes >_< Without this (in the same place in the optimised solver) the miner would consistently segfault after about five seconds of generation. Doesn't happen at any other checkpoint. The comment was so I didn't forget to investigate.

**Comment by defuse** [comment]
ACK on the concept, +1 on signaling cancellation by throwing an exception. Needs tests and more investigation of the segfault thing as already noted.

File: src/crypto/equihash.cpp (hunk 1 above)
Comment (daira) [inline src/crypto/equihash.cpp]: Does running it under valgrind shed any light on this?

**Comment by str4d** [comment]
This is very weird - I can no longer recreate the segfaults...

**Comment by str4d** [comment]
No wait, it's back again. Checked with gdb, and it is segfaulting inside `chainActive.Tip()` (which is a single line). My best guess is that it's some kind of memory access violation around when the tip is updated. Looks like I'll have to add another thread to properly avoid this...

**Comment by daira** [comment]
Remember that ``chainActive.Tip()`` must be called only when a lock is held. (I haven't looked at the details, but there's upstream documentation of their locking policy iirc.)

**Comment by str4d** [comment]
@daira thanks, I was unaware of that. My solution leverages another angle that should be more efficient.

**Comment by str4d** [comment]
Tests in place, and segfault should be fixed.

**Comment by daira** [comment]
+1 for the general approach, but why do we need the ``EhSolverCancelCheck`` argument? We don't actually use the information as to where the cancellation occurred, do we?

File: src/gtest/test_equihash.cpp [hunk 2]
```diff
@@ -0,0 +1,184 @@
...
+        ASSERT_THROW(Eh48_5.OptimisedSolve(state, [=](EhSolverCancelCheck pos) mutable {
+            if (triggered)
+                return pos == StartCulling;
+            if (pos == FinalColliding) {
+                triggered = true;
+                return true;
+            }
+            return false;
+        }), EhSolverCancelledException);
+    }
```
Comment (daira) [inline src/gtest/test_equihash.cpp]: This doesn't seem to test that the FinalColliding check causes the solver to cancel any earlier. (It could complete FinalColliding normally and only cancel at StartCulling, and this test would still pass.) I suppose that's ok.

Comment (daira) [inline src/gtest/test_equihash.cpp]: Never mind, I understand it after reading the tests.

File: src/crypto/equihash.cpp [hunk 3]
```diff
@@ -458,6 +472,7 @@ std::set<std::vector<eh_index>> Equihash<N,K>::OptimisedSolve(const eh_HashState
     std::set<std::vector<eh_index>> solns;
     eh_index recreate_size { UntruncateIndex(1, 0, CollisionBitLength + 1) };
     int invalidCount = 0;
```
Comment (daira) [inline src/crypto/equihash.cpp]: If these initialisations were hoisted above the preceding loop, would it be ok to use ``if (cancelled(FinalColliding)) goto cancel solver;`` above, thus simplifying the test?

Comment (daira) [inline src/crypto/equihash.cpp]: I can also see two other options to avoid the memory leak:
1. Wrap the whole thing in a try/catch that deletes the elements of ``partialSolns`` in the catch, and rethrows.
2. Use a container whose destructor deletes its elements for ``partialSolns``.

Comment (str4d) [inline src/crypto/equihash.cpp]: I think so. I can test and confirm.

**Comment by str4d** [comment]
That does make it simpler. Thanks @daira :smile:

**Comment by str4d** [comment]
> 2. Make the element type of partialSolns a smart pointer type, rather than a raw eh_trunc*, so that the elements are deleted when the vector is.

Actually, I like this idea more.

**Comment by ebfull** [comment]
Why are we using `std::mutex` instead of Bitcoin's `CCriticalSection`?

**Comment by ebfull** [comment]
By the way, awesome, awesome tests.

**Comment by str4d** [comment]
I tried `CCriticalSection` first, but couldn't get it to work with lambdas (issues with capturing). A `std::mutex` is what the Boost docs recommended.

File: src/miner.cpp [hunk 4]
```diff
@@ -534,7 +555,11 @@ void static BitcoinMiner(CWallet *pwallet)
                     SetThreadPriority(THREAD_PRIORITY_NORMAL);
                     LogPrintf("ZcashMiner:\n");
                     LogPrintf("proof-of-work found  \n  hash: %s  \ntarget: %s\n", pblock->GetHash().GetHex(), hashTarget.GetHex());
-                    ProcessBlockFound(pblock, *pwallet, reservekey);
+                    if (ProcessBlockFound(pblock, *pwallet, reservekey)) {
+                        // Ignore chain updates caused by us
+                        std::lock_guard<std::mutex> lock{m_cs};
+                        cancelSolver = false;
```
Comment (daira) [inline src/miner.cpp]: There's a race condition where a chain update (not by us) happens between the one caused by ``ProcessBlockFound`` and taking the lock. It doesn't affect correctness; it will just result in a stale block, if we're really unlucky. I don't think that's a problem. It might be fixable by taking the lock before calling ``ProcessBlockFound``, but that would only work if locks are reentrant.

**Comment by daira** [comment]
ACK.

File: src/miner.cpp (hunk 4 above)
Comment (str4d) [inline src/miner.cpp]: Yeah, I decided the additional effort and complexity want worth the gain. This PR reduces the issues by >95%, which is good enough for now. We can revisit if this is still noticeable in later releases.

**Comment by str4d** [comment]
@zkbot r+
